### ISSUE TITLE
Icon change

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1015]
At some point in the last few publishes, the icon for "watch" in the teaching page changed from what you see in the first image to what you see in the second image. The first image is what is expected in Figma.
<img width="715" alt="Screen Shot 2022-06-21 at 2 31 31 PM" src="https://user-images.githubusercontent.com/48295718/174862214-32527163-abbb-44e1-a500-98c1b330261b.png">

<img width="1176" alt="Screen Shot 2022-06-21 at 2 31 15 PM" src="https://user-images.githubusercontent.com/48295718/174862228-712573ad-7b00-48e9-a9e2-d05522a28dcc.png">

**Comment by georgevicbell** [comment]
This is to fix the YouTube issues int he doc you sent me…

They didn’t like our icon…

I figured it was easier to change it than to explain it to them...

**Comment by lucastbelem** [comment]
Ah. Gotcha.

**Comment by georgevicbell** [comment]
This is to fix the YouTube issues int he doc you sent me…

They didn’t like our icon…

I figured it was easier to change it than to explain it to them...

On Jun 21, 2022, at 10:34 AM, Lucas Belem ***@***.******@***.***>> wrote:



At some point in the last few publishes, the icon for "watch" in the teaching page changed from what you see in the first image to what you see in the second image. The first image is what is expected in Figma.
[Screen Shot 2022-06-21 at 2 31 31 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fassets%2F48295718%2F32527163-abbb-44e1-a500-98c1b330261b&data=05%7C01%7C%7C5e5c4afcbde044f9131508da53ac5444%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637914296855953350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lgr9JmBjFyh8dj0iks2Nt9W7LGJr20X6UcjUvv%2BomDI%3D&reserved=0>

[Screen Shot 2022-06-21 at 2 31 15 PM]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fassets%2F48295718%2F712573ad-7b00-48e9-a9e2-d05522a28dcc&data=05%7C01%7C%7C5e5c4afcbde044f9131508da53ac5444%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637914296855953350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wnba9ilxi2gFN5A70ES%2FbRmgYWtAUj8tQ%2BL8kU9Omrk%3D&reserved=0>
