### ISSUE TITLE
Regional changes

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1023]
As we move to regional setup, here are some things we can be doing:

- regional page design
- regional shortcuts (Toronto.themeetinghouse.com)
- merging events into a Toronto event list
- ability to see all Toronto homechurches
- merging social media (insta, Facebook, etc)
- merging staff list - all Toronto staff
- improvements to online church - including an online having its own page, staff list, links, social media etc.

**Comment by georgevicbell** [comment]
Do we have any more direction on this? Timing etc?

**Comment by lucastbelem** [comment]
Working on some of that now, but most requires a bit more research on our part plus direction from SLT on what's actually happening on the regional model.
