### ISSUE TITLE
Replace all staff photo

### ISSUE THREAD

**Issue by georgevicbell** [themeetinghouse/web#1026]
....we took a new photo, lets get it on the site (404 page, and about us page)

**Comment by lucastbelem** [comment]
@laurengermain can you pls update as @georgevicbell indicated? We'll also be getting all of the new staff headshots in the next few days. @georgevicbell for this, you'll likely need to clear cache because the image names can't be different than the existing ones. 

Make sense?

**Comment by lucastbelem** [comment]
@laurengermain all staff shot is here: https://www.dropbox.com/sh/2zsn7cdun3vlujh/AACSadfAs9S_BNuuGrLhRYHYa?dl=0

**Comment by GeorgeBellTMH** [comment]
Let me know when done and I will clear the cache...

**Comment by georgevicbell** [comment]
@laurengermain you can now clear the cache!
