### ISSUE TITLE
Page Editor Stuff to do

### ISSUE THREAD

**Issue by georgevicbell** [themeetinghouse/web#1027]
- [X] Show existing page in editor
- [X] Add Edit buttons to each component and open Edit modal
- [X] Add delete buttons to each component and delete component
- [X] Add add button at top
- [X] Add modal - should list all components
- [x] Add re-order buttons - and reorder
- [X] Hero - editable fields - json file
- [X] Hero - stateful
- [X] Content -editable fields - json file
- [X] Content -stateful
- [ ] Other types ?/? - editable fields - json file
- [ ] Other types - stateful
- [X] Text, Array, Object, Picker, Number field editor
- [ ] Image editor - (needs work)
- [ ] Image moving lambda?
- [ ] Other editors?
- [x] Ability to save json
- [x] JSON lambda
- [ ] Ability to schedule json
- [x] Ability to open existing json
- [x] Figure out what stays on VSCode/AWS
- [x] Ability to delete existing json
- [ ] Ability to search existing json
- [ ] Replace all?
- [ ] JSON Validator
- [x] Handle bad JSON gracefully in editor
- [x] Permission Checks
- [x] new page
- [x] Maintain History

**Comment by georgevicbell** [comment]
@lucastbelem this is now live...you can test it...

1. Whatever you save it as is what it will show up as - so if you save test1 then tmh.com/test1 will be it...
2. If there is an existing file in static/content - it takes preference...so you would need to delete it from there...
3. Filename is not remembered when you load a file
4. Image uploading is rough
5. Only content and hero work correctly right now...let me know if you have priorities for the others

There are lots of other bugs...but it's live now so we can do some testing and figure out priorities...

**Comment by georgevicbell** [comment]
It's in the admin bar->Editor

**Comment by lucastbelem** [comment]
@itbel let's work on this too.

**Comment by lucastbelem** [comment]
I have a better idea now of how we'll need this to work. Here is what I'm proposing:

- When I click "Editor" I see a text map of the website, or a tree jack of all webpages. This should be structured perhaps like a directory with folders and "files" inside. Orphan pages should be in their own "folder".
- I should be able to edit any of the items in the tree jack by clicking on it (each item is essentially a page, so when I click on one, I'm effectively editing that page)
- Once I'm in the page, the UI should change to a split screen (if split screen doesn't work, it can be full screen with a "preview" button that then displays a full screen modal of the website for the user to see their change in admin before going live). 

Left side
- A structure of the page arranged as components that are displayed in order (i.e. Hero - content - list, etc ). 
- Clicking on any of the items should provide an interface for the admin to interact with and add data to that component (perhaps in a modal where the user can choose the "type", "style", select the image/pdf from the image/pdf database in admin itself, indicate if something is a link or button and enter the url and title for that hyperlink, etc).
- Please note: when selecting an image/pdf, user should be able to upload a new item as well as select from the admin database. They can probably do this by navigating through the folders of the website as a directory, if that's the simplest UI possible).
- User should be able to re-order components easily, perhaps by drag-and-drop. Some iconography way of indicating this is possible.
- The page should also have space for entering metadata (i.e. keywords, OG tags, pageconfig, etc).

Right side
- Display the preview of what the user is building as they build it (i.e. save the modal). OR;
- Display a full-screen modal of the page being edited once the save the edit modal for the component.

Actions needed
- Preview
- Go Live
- Edit
- Create

**Comment by lucastbelem** [comment]
Must be able to upload/edit/delete files within the editor.
