### ISSUE TITLE
Where should the Blog RSS feed live?

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/web#1029]
Blog RSS feed is live at [www.themeetinghouse.com/static/sitemap2.xml](https://www.themeetinghouse.com/static/sitemap2.xml)

I created a redirect from https://themeetinghouse.com/blog/feed but this doesn't work as intended when adding to RSS reader. Any ideas on how to accomplish routing for this? 
Is it even necessary?

**Comment by lucastbelem** [comment]
@itbel I'd love to help, but this seems a bit more technical. @GeorgeBellTMH any insights?

**Comment by georgevicbell** [comment]
Why does the RSS reader not like it?

I think if it's a valid RSS feed it should be ok at that location...we will need to probably put an RSS Icon and link on the page so people can make use of it...

**Comment by georgevicbell** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.themeetinghouse.com%2Fstatic%2Fsitemap2.xml

Seems to have a few warnings...but otherwise fine...it doesn't like it when redirecting...

**Comment by georgevicbell** [comment]
(also doesn't like it when ommitting the www.
