### ISSUE TITLE
Missing title, meta tags

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/web#1031]
The video player and blog pages are missing the title and meta tags. This is important for SEO for video and blog content. 

![image](https://user-images.githubusercontent.com/42515854/178313026-c3874e27-e3d9-41bd-8b68-da9a655a4140.png)

I also noticed we have a [component](https://github.com/themeetinghouse/web/blob/master/src/components/RenderRouter/OgTags.tsx) `<OgTags/>`, but it doesn't seem to be in use/working (?) causing #925 

Do you know anything about this component?

**Comment by georgevicbell** [comment]
So there is some crazy backend stuff going on to make this work...

1) We catch whatever the client is (Facebook, google, twitter) 
2) we redirect them to socialBotHandler function
3) Return a dummy page with all the meta data correctly
4) the OGTags is where we get the meta data...(in some cases, and in others we generate it from the DB, or other locations)

**Comment by georgevicbell** [comment]
You can test by setting your client to whatever it is that you want to test (Facebook, twitter or google bots - not sure exactly what the naming convention is)
