### ISSUE TITLE
Regional landing pages

### ISSUE THREAD

**Issue by georgevicbell** [themeetinghouse/web#1040]
Creating toronto.themeeetinghouse.com and Hamilton.themeetinghouse.com

- [x] Domains created and pointed
- [x] Code to redirect to /toronto and /hamilton when they exist...

Probably a few others need to be done...can update the list as we go...

**Comment by lucastbelem** [comment]
@georgevicbell why Toronto? I mean, the regional model may require the subdomains, and I get Hamilton as they're launched already, but did you hear something about Toronto specifically?

**Comment by georgevicbell** [comment]
Nope, just figured they were the first two that would happen based on yesterdays WASM...Toronto can redirect to the homepage for now...

**Comment by georgevicbell** [comment]
(but needed two to be able to test)

**Comment by georgevicbell** [comment]
I'm going to leave both of these as is (pointing to the homepage) until we have landing pages for Hamilton and Toronto...the code is relatively straight forward once we have them in place...

**Comment by georgevicbell** [comment]
But for future reference, we can add any other subdomains in the future if we want...

cc: @GarnetMason

**Comment by GeorgeBellTMH** [comment]
ok, the domain thing works...so Toronto is live...will do the rest later tonite...

**Comment by GeorgeBellTMH** [comment]
The following are created - please verify content:

  "toronto.themeetinghouse.com",
                        "waterloo-region.themeetinghouse.com",
                        "hamilton.themeetinghouse.com",
                        "peel.themeetinghouse.com",
                        "london.themeetinghouse.com",
                        "newmarket.themeetinghouse.com",
                        "ottawa.themeetinghouse.com",
                        "parry-sound.themeetinghouse.com",
                        "richmond-hill.themeetinghouse.com",
                        "alliston.themeetinghouse.com",
                        "sandbanks.themeetinghouse.com",
                        "global.themeetinghouse.com"

**Comment by GeorgeBellTMH** [comment]
I've also added:
youth.themeetinghouse.com 
kidmax.themeetinghouse.com
christmas.themeetinghouse.com 
easter.themeetinghouse.com
