### ISSUE TITLE
Global Community Page has incorrect staff...

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1051]
Staffing needs to be updated on global community page...currently showing Mike Slack...

**Comment by GeorgeBellTMH** [comment]
Should Chris Chase be added to this list?

**Comment by GeorgeBellTMH** [comment]
I guess the question is - is there a difference between online and global?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH def add Chris and remove Slack. I think we're very near to merging online and global as one thing.

**Comment by lucastbelem** [comment]
@laurengermain did we do this? Does Chris appear under global/online?

**Comment by laurengermain** [comment]
Yup!
