### ISSUE TITLE
Region Updates

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1052]
We need the following information for: 

Facebook ID going forward
Instagram ID going forward
List of staff (create new regional groups)
List of compassion (create new regional groups)
Borders (someone get out a map and draw the borders)
Locations they are meeting
  - Address
  - Is Accesible
  - Has changing/nursing
  - Has gender neutral bathrooms
  - Transit, Parking and Bike info
  - Which communities are regularly meeting
  - Kids and youth program info (time/meeting location)
  - If local teaching is being recorded, where is it being put online
 
Home Church grouping update in F1

We need this for:

Waterloo Region
Kitchener Community
Waterloo Community
Cambridge Community
Hamilton Region
Ancaster Community
Downtown Hamilton Community
Brantford Community
East Community
Toronto Region
Downtown Toronto Community
High Park Community
Uptown Community
East Toronto Community
Halton-Peel Region
Oakville Community
Brampton Community
Milton Community
Mississauga Community
Burlington Community
Distance Region
London Community
Newmarket Community
Ottawa Community
Parry Sound Community
Richmond Hill Community

**Comment by GeorgeBellTMH** [comment]
Waterloo is confusing because there are two of the same...one is a region and one is a community...

ie themeetinghouse.com/waterloo becomes confusing..

**Comment by GarnetMason** [comment]
Let's update all regional pages to include the word Region afterward.

ex. themeetinghouse.com/waterlooregion for the regional page

and

themeetinghouse.com/waterloo for the community (if they have their own
pages)


Regards,

*Garnet Mason*

Marketing Manager, The Meeting House

2700 Bristol Circle | Oakville, ON | L6H 6E1

p: (289) 795-9561 | e: ***@***.***

www.TheMeetingHouse.com <http://www.themeetinghouse.com/>



“Glory to God, who is able to do far beyond all that we could ask or
imagine by his power at work within us” – Ephesians 3:20



*This email, including attachments, is for the sole use of the intended
recipient and may contain confidential information.  If you are not the
intended recipient, any disclosure, copying or distribution of the
information is prohibited.  If this email was received in error, please
notify us by reply email and delete the original message.*

**Comment by lucastbelem** [comment]
Closing this as the information has evolved from this.
