### ISSUE TITLE
Domain updates

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1053]
Need to create the following sub domains of the meetinghouse.com pointing to the same setup as existing Toronto.themeetinghouse.com:

Waterloo
Hamilton
Toronto
Peel
HaltonPeel
Halton
Distance
Global
Online
London
Newmarket
Ottawa
ParrySound
RichmondHill

**Comment by branden-eyk** [comment]
Hi George, sorry for the delay. Haven't paid much attention to GitHub (or at least TMH's repositories) these days. I've done as you asked and added all these sub domains and directed them to www.themeetinghouse.com like Toronto was.
