### ISSUE TITLE
Region Updates for Staff

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1054]
Please go through the staff.json file, and the coordinators file and add the following to sites depending on what region the staff is a member of (keep the existing communities for now):

Waterloo_Region
Toronto_Region
Peel_Region
Hamilton_Region
Distance_Region
Online_Region

**Comment by GeorgeBellTMH** [comment]
cc: @lucastbelem

**Comment by laurengermain** [comment]
@GeorgeBellTMH should I add the region for all volunteer coordinators as well?

**Comment by GeorgeBellTMH** [comment]
Yup

**Comment by laurengermain** [comment]
@GeorgeBellTMH Okay thanks! I have updates these.

**Comment by GeorgeBellTMH** [comment]
@lucastbelem this is ready, you just have to change the staff components on each page...
