### ISSUE TITLE
Do not publish or push

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1067]
There is currently a problem with amplify whereby it always does a full publish...this wipes out our hosting config...and the website goes offline...

I am trying to work with them to resolve the issue, but until it is, I have to rebuild the hosting manually after each publish...so please don't push or publish until it's fixed.

**Comment by GeorgeBellTMH** [comment]
Unless there are urgent publishes, I will be publishing on Mondays going forward until this is fixed...if there is an urgent publish please let me know with as much advanced notice as possible so I can be free...the resetting of the hosting takes about an hour...

**Comment by itbel** [comment]
Understood.

**Comment by GeorgeBellTMH** [comment]
Ok I think this is resolved...
