### ISSUE TITLE
Series image not displaying

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1069]
<img width="1428" alt="Screen Shot 2022-10-13 at 3 34 41 PM" src="https://user-images.githubusercontent.com/48295718/195678478-ca60d2f7-228c-42b0-9fb2-e46afa467ba5.png">
<img width="1115" alt="Screen Shot 2022-10-13 at 3 34 50 PM" src="https://user-images.githubusercontent.com/48295718/195678500-11114231-d5cc-4a9d-87a3-3340d74e36a1.png">

**Comment by GeorgeBellTMH** [comment]
This should be resolved.
