### ISSUE TITLE
New filter for staff

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1070]
Can we use a version of this design in the staff component so we can see people in teams? We can use the site field to determine this (i.e. Toronto Region, Communications, Operations, etc)

<img width="1438" alt="Screen Shot 2022-10-13 at 4 25 50 PM" src="https://user-images.githubusercontent.com/48295718/195691341-0908a4ce-db8e-4892-a8b0-f20c484e4422.png">

**Comment by lucastbelem** [comment]
@itbel there is an issue...not super detailed, here you go.

**Comment by GeorgeBellTMH** [comment]
I changed this to dropdowns.

**Comment by lucastbelem** [comment]
Hey George,

Why did you change them? I'd rather go with the tabs cause we have that
design elsewhere. But if there is a good reason to change it, it'd be good
to know.
