### ISSUE TITLE
Add the following to data/compassion.json

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1071]
Address:
Phone:
Email:
Social (twitter, fb, insta, TikTok)
Ensure rest of details are correct
GPS:

**Comment by laurengermain** [comment]
Hey @GeorgeBellTMH can you let me know if I am on the right track before I update all the compassion partners? Here is the first one I have done.
![Screen Shot 2022-10-25 at 12 16 59 PM](https://user-images.githubusercontent.com/89869101/197828449-acec6b8b-8697-4f04-ba5f-ca4757348e4e.png)

**Comment by georgevicbell** [comment]
Yup this is good. You can add another field address: “123 sesame st” as well…Sent from my iPhoneOn Oct 25, 2022, at 12:19 PM, laurengermain ***@***.***> wrote:﻿
Hey @GeorgeBellTMH can you let me know if I am on the right track before I update all the compassion partners? Here is the first one I have done.

**Comment by laurengermain** [comment]
@GeorgeBellTMH thanks. A few more questions when you have a moment:
- I've added social handles, but do I include Twitter/FB too? If so, how?
- Some of the addresses Megan provided are mailing addresses (i.e., post office boxes). Do I include those or leave blank?
- All compassion partners should keep their site aside from Hamilton & Toronto, right? Do I change those to regions? "sites": ["Hamilton_Region"], and "sites": ["Toronto_Region"]

**Comment by georgevicbell** [comment]
1. Just the @whatever for twitter…and the fb is the full url for their page.
2. Leave them blank
3. Likely need to discuss with the regions if they want to make them regional or not…I suspect in Toronto some may be regional, some may not…but they should retain the community in any case so they show up on that page…

G



On Oct 26, 2022, at 12:20 PM, laurengermain ***@***.***> wrote:



@GeorgeBellTMH<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGeorgeBellTMH&data=05%7C01%7C%7C9e781b5bd96b4870f7c208dab76e10f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638023980598353741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A5FnpndchH2%2ByTWEAWbSe45IjTY0hgm718UmnE2PseI%3D&reserved=0> thanks. A few more questions when you have a moment:

  *   I've added social handles, but do I include Twitter/FB too? If so, how?
  *   Some of the addresses Megan provided are mailing addresses (i.e., post office boxes). Do I include those or leave blank?
  *   All compassion partners should keep their site aside from Hamilton & Toronto, right? Do I change those to regions? "sites": ["Hamilton_Region"], and "sites": ["Toronto_Region"]

**Comment by lucastbelem** [comment]
@laurengermain is this done?
