### ISSUE TITLE
Overseers.json not updated

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#1079]
@GeorgeBellTMH you may already be aware of this issue but flagging just in case -- Lucas removed the resigned overseers on Saturday but it hasn't updated on the website (Carole Ann and Jennifer are still appearing).

**Comment by lucastbelem** [comment]
I wonder if this is connected to the issue of coordinators not updating
either.

**Comment by GeorgeBellTMH** [comment]
Did you remove them from the db or the json?

**Comment by lucastbelem** [comment]
Json

**Comment by georgevicbell** [comment]
We moved over to using the db…so need to remove them from there...

On Nov 14, 2022, at 11:17 AM, Lucas Belem ***@***.***> wrote:


Json

**Comment by lucastbelem** [comment]
We did do that didn't we? Well, there we have it.  This is just a case of
my brain failing me 🤦😂

Thanks for setting us straight George.

Lauren, did we talk about the new people feature on /signin?

**Comment by laurengermain** [comment]
Haha, no we haven't! Is this why the Coordinators.json isn't working then?

**Comment by lucastbelem** [comment]
Yep

My bad!
