### ISSUE TITLE
Testing Log

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1083]
- [ ] Editor
- [ ] Editor fixes
- [ ] "Sites" to "Teams"
- [ ] Locations

**Comment by GeorgeBellTMH** [comment]
- [ ] https://github.com/themeetinghouse/web/pull/1119
- [ ] https://github.com/themeetinghouse/web/pull/1123
- [ ] https://github.com/themeetinghouse/web/pull/1124
- [ ] https://github.com/themeetinghouse/web/pull/1118

**Comment by lucastbelem** [comment]
@laurengermain can you pls test these as soon as possible? I'll walk you through it, but we're gonna need these functions for the story telling project next Saturday.
