### ISSUE TITLE
Clear Cache button in admin not working

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#1087]
I renamed some community pages and used the "Clear Cache" button in admin, but the original url is still accessible. For example, I changed "ancaster.json" to "z-ancaster.json"...

https://www.themeetinghouse.com/ancaster
https://www.themeetinghouse.com/z-ancaster

**Comment by lucastbelem** [comment]
It sounds like the "clear cache" function isn't working and not clearing S3.

**Comment by itbel** [comment]
404 page seems to not be working right now though... Maybe something to do with the backend split

**Comment by itbel** [comment]
The clear cache button in admin did not create an invalidation for me and the lambda timed out... @GeorgeBellTMH
