### ISSUE TITLE
V2 of serialized and tagged blogs

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1113]
Design can be found here: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=796%3A11260&t=Eg7J3JHBoe0O7VYZ-1

UI is under "Similar Blog posts" at the bottom of the blog post screen.

- [x] Implement UI as per approved Figma designs

This implementation will be used for serialized and tagged blogs. Blogs may optionally be added to a series, but must always be receive a tag.

Serialized blogs (should display in any blog post that is part of a series)
- [x] Section should be called "More from this series"
- [x] Use "publish date" to determine series order for this implementation
- [x] When this is the first post in a series, the next 2 posts should appear
- [x] When this is the last post in a series, the previous 2 posts should appear
- [x] When this is not the first or last post in a series, the previous and next posts should appear

Tagged blogs (should always appear when there is more than one blog post in that tag)
- [x] title of section should be "Similar blog posts"
- [x] Only 2 blogs should display
- [x] Use "publish date" to determine series order for this implementation
- [x] When this is the first post in a tag, the next 2 posts should appear
- [x] When this is the last post in a tag, the previous 2 posts should appear
- [x] When this is not the first or last post in a series, the previous and next posts should appear

**Comment by itbel** [comment]
Similar blog posts/Tagged blogs was implemented in #562 
I will work on your other requested changes
