### ISSUE TITLE
New Environment Test/Issues list

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#1116]
- [ ] F1 not working
- [x] Users need to be unlocked
- [x] Need a note on web/app to use reset pw function
- [x] Images
- [x] test.themeetinghouse.com is redirecting to cloudfront

**Comment by GeorgeBellTMH** [comment]
- [ ] Test a content change/sync
- [ ] Test a db change (add video?)
- [ ] Test blogs
- [ ] Test notes
- [ ] Test redirects

**Comment by GeorgeBellTMH** [comment]
- [ ] Test logins
- [ ] Test password reset Web
- [ ] Test password reset App
- [ ] Homechurches are updating
- [ ] F1 info in user login (backend test)

**Comment by GeorgeBellTMH** [comment]
- [ ] Search on web working
- [ ] Search on app working

**Comment by lucastbelem** [comment]
@GeorgeBellTMH awesome! Thank you!

@laurengermain can you prioritize these tests pls? This is part of the work George is doing to split TMH and JC in AWS.

**Comment by GeorgeBellTMH** [comment]
Logins should be working now.

**Comment by GeorgeBellTMH** [comment]
The login messages are just publishing now...

**Comment by laurengermain** [comment]
@GeorgeBellTMH I created notes for this Sunday in admin -- the header image isn't loading.

![Screen Shot 2023-01-19 at 3 32 44 PM](https://user-images.githubusercontent.com/89869101/213554183-5a5270eb-46b8-4e9d-b7f8-56cd5acc26cf.png)
![Screen Shot 2023-01-19 at 3 33 03 PM](https://user-images.githubusercontent.com/89869101/213554187-a0e5e12c-3f9b-4f8f-92ae-1c747c86f1df.png)

**Comment by laurengermain** [comment]
@GeorgeBellTMH also in the notes, I am not able to create a PDF. It says "error generating PDF."

**Comment by GeorgeBellTMH** [comment]
Ok, I've updated all the functions to the latest versions of everything and now I'm going to run through them all and test them...goal is to get things back to working order by tomorrow...(except for f1, which will be later this week)

**Comment by lucastbelem** [comment]
Thanks George.

Can we meet up tomorrow? What time works for you?

Can Igor work on the backend yet? Can you give us login access to the new
AWS?

**Comment by GeorgeBellTMH** [comment]
I'll call you. I think for now no access to push. Just a lot of stuff still to fix and if two people pushing it has bigger overhead time wise. Plan for next week. I will get you AWS access tonite.
