### ISSUE TITLE
Locations manager in admin

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1121]
Time for us to get this built. Here is what I'm proposing. Would love input. I think we can have Regions and communities co-exist without presetting a hierarchy.

Build a new experience in admin for management of locations on the website as follows:
- [ ] User can create new location. Fields available to user:
- Location name
- Address (display in black box in hero for that location) 
- Create a code (to go with the site codes we have already, like TOBC for East Toronto)
- Select a person as the pastor for this location. This should auto populate the "contact a pastor" info
- Meeting frequency (weekly, bi-weekly, monthly)
- Meeting day (days of the week)
- Gathering time. The combination of the 3 above pieces of info should auto populate the "add to calendar" 
- "Show in dropdown" checkbox (which would automatically add this location to the "Find a location" dropdown throughout the website)
- "Show in location map" checkbox (which would automatically add this location to the "/find-sunday-morning" page)
- "Community" or "Region" checkbox
- Automatically create a new location page with the url themeetinghouse.com/locationname. Page should automatically display the following structure (but through the editor later admins should be able to customize the page if needed):
- Hero with black box
- Regional Map (if Region)
- "Our Team" Component where all people associated with that location will display
- Instagram component
- Kids and youth component (example can be seen in any location page atm)
- Find home church component
- Make a difference component
- Sign up for newsletter component

UX:
1. Admin creates location and provides information
2. Coming soon, once editor is finished.

**Comment by lucastbelem** [comment]
- [ ] Creating a new location should create a new permission group in Cognito for that location (i.e. creating "Whitby" as a location now creates "Whitby" as a permission in Cognito)

**Comment by GeorgeBellTMH** [comment]
There is likely some connectivity we need to do to make sure new locations work with F1...specifically with the home churches...
