### ISSUE TITLE
Clean up admin screen

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1135]
We'll detail the requirements a bit later, but I just want to capture that this is work we need to do.
Things like:

- Double menu bar
- Wonky or unclear UI in certain screens
- UI uniformity for different screen sizes
- Extra, unnecessary empty screens
- Other things

**Comment by GeorgeBellTMH** [comment]
- All the items in the menu can be moved into a dropdown under admin...this is a relatively easy change and will simplify a lot...
