### ISSUE TITLE
Favicon went white?

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1153]
<img width="396" alt="Screen Shot 2023-02-17 at 3 33 40 PM" src="https://user-images.githubusercontent.com/48295718/219787593-90172c7d-e0dc-4fd5-aa28-13763db7e640.png">

**Comment by itbel** [comment]
Is this issue still occurring?

**Comment by itbel** [comment]
This is working as intended for me based on user's light/dark theme system options..
