### ISSUE TITLE
Toolbar moved to top

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1154]
Would it be possible to move the text editing toolbar to the top rather than the bottom of notes (and I think blogs too)?
<img width="1296" alt="Screen Shot 2023-02-17 at 3 35 30 PM" src="https://user-images.githubusercontent.com/48295718/219787909-edcd69d8-997f-4229-9b3c-70374809a3e3.png">

**Comment by itbel** [comment]
yes
