### ISSUE TITLE
Location specific admin management

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1165]
We'd like to give people access to their specific locations. Please create the following permission groups:

- Oakville
- Brampton
- Burlington
- Halton-Peel (this permission should include access to the 3 above locations) 
- Downtown Toronto
- East Toronto
- High Park
- Toronto (this permission should include access to the 3 above locations) 
- Newmarket
- London
- Parry Sound
- Richmond Hill
- Sandbanks
- Alliston
- Online
- Ottawa
- Distance (this permission should include access to the 8 above locations) 
- Hamilton
- Waterloo

Having any of these permissions should give you limited access to the following permissions: 
- People
- Announcements
- Locations
- Home Churches

But they should only be given access to each of the items above that pertain to their own location. I.e. if given the "Oakville" permission, I should be able to access "People" but I could only click to view and edit data for those with the "OAKV" or "Oakville" location tag. Same applies to "Announcements", "Locations", and "Home Churches".

**Comment by GeorgeBellTMH** [comment]
These permission groups should be already auto-set when you pick a location in the app...there is no way to pick a location in the web...but there should be....

**Comment by GeorgeBellTMH** [comment]
If we want to have admin groups for locations then we can create groups, but they should be in the form of: Admin-[location]

**Comment by GeorgeBellTMH** [comment]
@itbel you can look at the amplify post login lambda hook and figure out what is happening, but we add the groups dynamically...if we need to update the logic that is fine, or if we need to rename groups we can do that too but need to make sure it happens everywhere (including json files for app, which can include permission logic)
