### ISSUE TITLE
Add "Teams" to admins

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1176]
I'm wondering about the possibility of adding "teams" management. Here is what I'm thinking:

- [ ] #1202
- [x] Change text field to dropdown
- [x] In dropdown, display all teams that exist
- [x] In dropdown, include a "add new team"option
- [ ] This should be handled in modal somehow
- [x] That team gets added to the dropdown list, which is updated automatically, and allows the admin user to pick that new team for that staff/coordinator

Thoughts?

**Comment by itbel** [comment]
Sounds good.

**Comment by itbel** [comment]
implemented in #1198
