### ISSUE TITLE
Home Church Group ID Locations - seems broken

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1183]
When filtering home churches by "Hamilton", no home churches appear (at /find-homechurch). It appeared that the Home church group ID was incorrect. When correcting it in Locations in Admin, it says it changed successfully, but the home churches still don't appear. @GeorgeBellTMH reports still seeing the incorrect ID. @itbel can you pls investigate?

**Comment by itbel** [comment]
Home churches(from F1) must have the same home church group id as what is set in the locations manager in order for the filtering to work. This issue stems from the fact that Hamilton does not have a home church group id, and home churches in Hamilton might be using old home church group ids for locations that no longer exist.
