### ISSUE TITLE
People Component on Careers not filtering

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1184]
I.e. I added Darryl Buckle to Waterloo. He displays when I search his name, but if I filter by "Waterloo" he does not display. There are other examples too.

**Comment by itbel** [comment]
In order for the user to show up in the filter selected, the filter ID must match an ID existing in "Sites" belonging to a user.
For example, 
<img width="1916" alt="Screenshot 2023-06-30 at 22 06 14" src="https://github.com/themeetinghouse/web/assets/42515854/ee5383d1-0f7b-4d76-b461-505088595960">
Darryl Buckle has site "WAT", but the filter ID for Waterloo is 'Waterloo_Region' as per the screenshot. To make Darryl apppear for the Waterloo filter 'Waterloo_Region' must be added to Darryl's sites. Or, change the Waterloo filter ID to be "WAT".
