### ISSUE TITLE
Cannot share video

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1186]
When I click "share" when watching a video on the website and select "email", nothing happens. Here is what I see in the console.

![Uploading Screenshot 2023-05-05 at 4.39.23 PM.png…]()

**Comment by itbel** [comment]
Which video? This appears to be working for me..

**Comment by lucastbelem** [comment]
themeetinghouse.com/peacemakers. Try the first video in the carousel.

**Comment by itbel** [comment]
Working for me on Mac on Safari and Chrome. Can you give more details? The screenshot is broken.

**Comment by lucastbelem** [comment]
What happens for me when I click "email" is that the favicon blinks, as though the page is trying to load something, and for a split second, I see a message bottom right (like when you hover on a link in your browser) that says "waiting on youtube.com). But then, nothing happens.

**Comment by itbel** [comment]
Appears to be working...
