### ISSUE TITLE
Staff team not saving

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1191]
Julia Silvestri wasn't appearing under staff or East Toronto (the team she belongs to). 

I checked and saw what you see in the screenshot below. The problem is my colleague assures me that he added her to "TOBC". I've now added her and saved and it now appears to have worked.

I have witnessed this before, where I need to save more than once for it to actually stick. Can you pls investigate?
<img width="1470" alt="Screenshot 2023-06-09 at 1 21 30 PM" src="https://github.com/themeetinghouse/web/assets/48295718/cf15abd5-7bd2-4f66-b1fd-5ec97afd1bc4">

**Comment by itbel** [comment]
Changes have been made to the site input field. It is now a dropdown, this issue most likely does not apply anymore.
