### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#121]
We need to create The Meeting House blog. Go here for the blog design and specs: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI---GitHub-Sharing?node-id=796%3A11260

**Comment by GeorgeBellTMH** [comment]
- should pull data from amazon dynamodb (schema is stored under amplify/backend/api/themeetinghouse/schema.graphql)
- only users in group [blog] should be able to post
- should integrate with search
- should be embedded in multiple pages/locations throughout site
- note this is a large feature with lots of moving parts - please coordinate work with George (ie to get amazon database tables created etc.)

**Comment by GeorgeBellTMH** [comment]
Suggested steps:
1. Create dynamodb schema for Blogs
1a. @auth should allow anyone in [blog] group to create /edit/delete
1b. @search should be enabled so it gets put into elastic search
2. Create a new route /blog/[articleId] and pull from Amplify/dynamoDB
2a. Likely need to create a new renderRouter component and static page to display blogs (this whole section is very much like the video player)
3. Create simple admin interface for creating blogs
4. Choose a wysiwyg editor component
5. Create some blog list renderrouter components (or update existing) for including on other pages
6. Update Search component to return results from blog schema
7. Enhanced features (sorting, listing, tagging, etc. etc.)

**Comment by JonEsparaz** [comment]
I'm working on the text editor. Right now I have it configured to allow the following inline styling:
- bold
- italics
- underline
- insert link
- header

This pretty much allows what you to make a post like the example on Figma.

@deeinstereo do you think this is good? Or do we need more/less features?

**Comment by georgevicbell** [comment]
Can it add photos and video? Can it change font size? I think those are likely needed as well. Probably emojis as well...

Sent from my iPhone

On May 13, 2020, at 8:49 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

I'm working on the text editor. Right now I have it configured to allow the following inline styling:

  *   bold
  *   italics
  *   underline
  *   insert link
  *   header

This pretty much allows what you to make a post like the example on Figma.

@deeinstereo<https://github.com/deeinstereo> @lucastbelem<https://github.com/lucastbelem> @GeorgeBellTMH<https://github.com/GeorgeBellTMH> do you think this is good? Or do we need more/less features?

**Comment by JonEsparaz** [comment]
Added those features to the config. Emojis are of course included 👌

**Comment by deeinstereo** [comment]
@JonEsparaz yes emojis! To @georgevicbell's point, yes on picture embed but for adding videos we would only ever embed YouTube videos if that. I hate those website generated video players blah. But for now hosting video is not a priority.

**Comment by JonEsparaz** [comment]
@lucastbelem how are baby hero images currently handled for videos? Would the same system work for blogs?

**Comment by JonEsparaz** [comment]
Here's a small update...

Text input area:
![image](https://user-images.githubusercontent.com/48423418/81988142-f571c480-9608-11ea-8196-aa28785af41f.png)

Rendered preview of blog at the bottom of the page (I'm trying to make this a separate window, but that might be a "nice-to-have" until everything else is done):
![image](https://user-images.githubusercontent.com/48423418/81988316-3ec21400-9609-11ea-86ad-53475fe1acef.png)

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH images have to be inserted via URL at the moment. I think local upload is possible, but not preferable. Is there a way a user could upload to media.themeetinghouse.com and get a URL to insert their image?

**Comment by GeorgeBellTMH** [comment]
I have an example in GitHub.com/jesus-collective/mobile where they can be uploaded via Amplify Storage to S3...this is the ideal as we can use the amplify authentication we already have in the admin module to ensure only people in the bloggers group can upload images...it also gets us the re-rendering to multiple sizes depending on screen size for free.

**Comment by GeorgeBellTMH** [comment]
I've added you to the admin group on tmhprod - so you should be able to login to the tmh.com/admin now....I also added you to the new bloggers group...

**Comment by GeorgeBellTMH** [comment]
If you make a PR with your schema changes I can push it...and I'll setup the storage so it's writable only by that group and readable by public...

**Comment by JonEsparaz** [comment]
Sounds good - thanks George. I'll try and get that PR up tomorrow.

**Comment by deeinstereo** [comment]
Thanks @JonEsparaz! This is looking great! We'll definitely need to find a way to insert pictures, looking forward to the solution! One other thing I noticed: how do we want to handle tagging and SEO type stuff? We should be able to add or indicate the tags and topics of each blog, and it would be a missed opportunity if we couldn't add keywords as we're adding blogs. 

Also:
- Can we make sure that Graphik is the only font that can be used for the blog posts?
- What thoughts do we have about how we separate between proper blogs, and notes that we're creating using the blog post module?

Thanks for all your work!

**Comment by GeorgeBellTMH** [comment]
So the way it works...you can use Storage.put and Storage.get in Amplify - there is a new lambda trigger that gets run on Amazon after you do a storage put...so you can validate the file uploaded is an image, move it around, size it, run facial recognition on it...whatever you want to do...I think it's fine if we put things in the public or protected folder (there is also a private folder, which you can read about on the Amplify site)...maybe have an upload folder and a final folder...move things over if they are good... Commit is here: https://github.com/themeetinghouse/web/commit/7a375abb9de25fc9d7ba25a4b5d8763e8d402fb4

**Comment by GeorgeBellTMH** [comment]
Right now it doesn't route through Cloudfront(CDN)...once we get some images in there we can experiment with setting up the permissions and routing...

**Comment by JonEsparaz** [comment]
> Thanks @JonEsparaz! This is looking great! We'll definitely need to find a way to insert pictures, looking forward to the solution! One other thing I noticed: how do we want to handle tagging and SEO type stuff? We should be able to add or indicate the tags and topics of each blog, and it would be a missed opportunity if we couldn't add keywords as we're adding blogs.
> 
> Also:
> 
> * Can we make sure that Graphik is the only font that can be used for the blog posts?
> * What thoughts do we have about how we separate between proper blogs, and notes that we're creating using the blog post module?
> 
> Thanks for all your work!

@deeinstereo 

For tags (and associating blogs with video series, blog series, etc) I'll add some input fields similar to the video import tool.

They can't select font, but it will render always in Graphik Web regardless.

For notes, I think we can finish up the blog, check if there's any issues, then port everything over. It will be pretty much the same, expect under a new route /notes/id instead of /blog/id perhaps the text editor can be a bit more flexible too.

**Comment by JonEsparaz** [comment]
> It's all setup...So the way it works...you can use Storage.put and Storage.get in Amplify - there is a new lambda trigger that gets run on Amazon after you do a storage put...so you can validate the file uploaded is an image, move it around, size it, run facial recognition on it...whatever you want to do...I think it's fine if we put things in the public or protected folder (there is also a private folder, which you can read about on the Amplify site)...maybe have an upload folder and a final folder...move things over if they are good... Commit is here: [7a375ab](https://github.com/themeetinghouse/web/commit/7a375abb9de25fc9d7ba25a4b5d8763e8d402fb4)

Just tested this out - works great!

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH I think we need to edit some parameters in the S3 bucket to make the download links non-expiring. How about I set all blog images to save in a public folder /bloguploads and we can just edit the parameters for that folder?

**Comment by JonEsparaz** [comment]
@deeinstereo I'd like to add default images in case a blog post is missing images. We need three images: something for the banner images that show up on the homepage, baby-hero and square. Let me know what direction you want to take this.

**Comment by deeinstereo** [comment]
@JonEsparaz hey! we'll make sure it's never missing an image. No image no blog! (Y)

**Comment by georgevicbell** [comment]
Instead of an image per blog, it might be doable to have one per “topic” - ie kids, teaching, compassion, leadership, current events, etc.

Either a photo, or maybe an icon/stylized thing.

Sent from my iPhone

On May 28, 2020, at 11:58 AM, David Siekanowicz <notifications@github.com> wrote:

﻿

@JonEsparaz<https://github.com/JonEsparaz> hey! we'll make sure it's never missing an image. No image no blog! (Y)
