### ISSUE TITLE
Location pages bugs

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1211]
Events, Instagram, and Kids and Youth aren't loading properly. Data is missing, UI is broken, events aren't loading.

**Comment by lucastbelem** [comment]
@itbel I know I said don't do "investigate" issues. But can you take a look at this to determine what is causing it and let me know before addressing it?

**Comment by itbel** [comment]
This is possibly an issue with facebook credentials. The API key that is used for these features has been deactivated.

**Comment by lucastbelem** [comment]
Ignore my previous question regarding your publish.
