### ISSUE TITLE
Community page - video playlist is attempting to load as events...and failing

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1219]
<img width="1457" alt="Screenshot 2023-10-17 at 9 02 21 AM" src="https://github.com/themeetinghouse/web/assets/48295718/b461dae9-c666-4b8d-906d-a0dca2c992b8">

**Comment by itbel** [comment]
Which site is this?

**Comment by lucastbelem** [comment]
Not a site...it's the community page under /community

**Comment by itbel** [comment]
I have been unable to replicate this issue. Can you confirm whether it is still occurring after these latest changes? Which browser are you using?

**Comment by lucastbelem** [comment]
Issue seems resolved.
