### ISSUE TITLE
Marquee Alert System for Snowdays - V2

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#122]
We need to create a marquee alert system for weather related service cancellations. Go here for the approved design: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI---GitHub-Sharing?node-id=220%3A6248

Please note the marquee alert has an alert dialogue that needs to appear when someone clicks on "click here" on the alert across the top of the site.

**Comment by GeorgeBellTMH** [comment]
- Need to add a yellow modal window (black and white already exist)
- Need to add a yellow header that only displays on homepage and location (ie. Oakville, Hamilton) pages
- Use existing configuration in json files "weatherAlert":false

**Comment by GeorgeBellTMH** [comment]
Can we close? I think we will need another system given the live stream is now at the top...

**Comment by lucastbelem** [comment]
Yeah, closing.
