### ISSUE TITLE
Testing Outcomes

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1222]
## **Editor**
- [x] Remove unused location pages (with Lucas)
- [x] Give admins ability to edit text only on /give
- [x] Add filters for the communities pages to remove the user's ability to edit non-editable components
- [x] When the user attempts to delete an image without adding another, can you provide a user error? https://user-images.githubusercontent.com/48295718/249495809-c565346e-26da-4e99-8f69-84643a4da98f.png
- [x] Re-add Communities to the pages editor
- [x] When someone receives both "staff" and "coordinator", they appear twice in the "Team" component on location pages. This should not be. Person should be staff or coordinator, not both.
- [x] Hide "teacher" from people options
- [x] Publishing a page navigates to the "Scheduled Pages" directory. (introduced in #1238)
- [x] Component preview is off (image below)
<img width="1152" alt="Screenshot 2023-11-03 at 1 28 02 PM" src="https://github.com/themeetinghouse/web/assets/48295718/0114ce01-d8d1-4cc9-b4c1-3657403ecf03">

- [x] Pages deleted from web editor are still displaying in the public pages list. But when I click delete it says they're already deleted. I.e. oakville.json. It appears to be a refresh issue. As long as I refresh after each delete, they get deleted properly.

## **Donations**
- [x] When giving via the account portal, user does not receive email receipt.
- [x] Redirect from profile page is broken
- [x] Failed to add a payment method. Error in console: POST https://api.stripe.com/v1/payment_methods 400 (Bad Request). Then noticed my profile was missing a country. Attempted to add a payment method again and succeeded. If this was in fact what prevented me from adding a payment method originally, it'd be good to prompt the user somehow with an error message.
- [x] When attempting to give once, I was prompted to add a payment method. I did and clicked "add new credit card". However, after a few seconds "loading" nothing happened. Console returned the following error: _Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received. When I attempted to click "give now" instead, it failed and the console returned the following error: "User is not a valid object." typename: "StripeAddPaymentResponse_. When I already had a payment method linked to my account (I switched accounts to my admin account for this) I was able to select it and process a donation that way.
- [x] Can you add a spinner to the "loading" in the buttons for give? Like, once I click "save" in confirming details or processing a payment, the button changes to "loading" but there is no motion to tell me something is actually happening. Because it takes a good 10 seconds to process, it'd be good to have a spinner in motion there.
- [x] I don't know if this is a problem or not, but when I set up a recurring donation, it worked very well. However, in Stripe, there was a log indicating some issues. Take a look at the subscription I created in my TMH email in Stripe.
<img width="901" alt="Screenshot 2023-11-10 at 2 37 10 PM" src="https://github.com/themeetinghouse/web/assets/48295718/ceb364d5-fda6-486e-8329-587428c2a995">

- [x] I ended up creating recurring gifts 3 times. On the third time, I noticed something odd. I was not able to set up the gift. I got an error message. In the console I saw "variable 'startDate' has an invalid value". So that prompted me to look at the start date. When I did I noticed the same thing I already noted as an issue here (Starting date in recurring donations displays random set of numbers), but this time the numbers were different. A long string of numbers but this time it had a period and 3 more numbers after. I changed the date and then was able to process the recurring gift. Image below:
<img height="400" alt="Screenshot 2023-11-10 at 2 45 00 PM" src="https://github.com/themeetinghouse/web/assets/48295718/05caf18c-66ee-4958-b6de-4fd7b4e72d42">

- [x] Starting date in recurring donations displays random set of numbers. Image below:
<img width="1458" alt="Screenshot 2023-11-03 at 5 29 47 PM" src="https://github.com/themeetinghouse/web/assets/48295718/318c784c-c941-40d6-956d-758f2946a9b0">

## **Render Router**

- [x] Can you please double check that sizes are in spec? The black box in the hero seems larger than before. The spacing between lines of text also seem large. Image below: 
<img width="1469" alt="Screenshot 2023-11-03 at 3 05 14 PM" src="https://github.com/themeetinghouse/web/assets/48295718/c399ba47-d007-4745-bcae-fc124903e6b1">

- [x] Perhaps related, perhaps not, but I also noticed that the search bar for teaching videos, while returning results as expected, it is not loading the thumbnails.  - check if related. (Thumbnails were never displayed here) -- Igor
<img width="1462" alt="Screenshot 2023-11-03 at 3 16 14 PM" src="https://github.com/themeetinghouse/web/assets/48295718/6c8d04c0-a794-46d0-ac28-fe081df35e78">

- [x] Spaces also seem off on mobile. I.e. look at the star content component on the home page. Lots of space between text and image.

## **Location and blog specific Permissions**
- [x] When the user creates an account and an admin gives that user the appropriate permissions (in this case, user received bloggers and location manager), upon logging in, user does not see the menu. To see the menu, I had to complete my profile. We need to make the user see the menu regardless or we need to force the user to complete their profile before proceeding.
- [x] Need to add the compassion partner table to the locations manager
- [x] User cannot see anyone who already exists. User should be able to see anyone who is on their "team" regardless of role (i.e. staff, coordinator, etc)
- [x] User cannot create a person. When attempting to create a user, the console returns the following: "An error occurred while creating a new user" and the error type was "unauthorized".
- [x] Cannot seem to save changes to social media on location manager
- [x] Updating lat and lon are broken
- [x] Oakville Sunday location is the same as a home church and youth location. The Sunday location should supersede the others.

## Other
- [x] Reported issue regarding creating a series: (WITH LUCAS)
> Couldn't create a series for livestream-services called "ACTS". Note that a series called "ACTS" already exists for sunday-services. I decided to try creating a Livestream series called "Acts" instead of "ACTS". And that turned out fine.
>  So currently all the [Sunday Livestream] services are part of the "Acts" series; whereas the [Sunday Teaching] services are part of the "ACTS" series.
> I wonder if the "livestream-services-Title" convention somehow avoided this problem.
**#1227** 
- [x] If a user searches for a keyword and hits "enter", the search page closes and the user is returned to the home page.
- [x] Random issue - the /ottawa url does not redirect to /communities/ottawa

**Comment by itbel** [comment]
I'll try to get it done tomorrow.

**Comment by itbel** [comment]
## Can you provide more context? 

> **Donations**
> * [ ]  Redirect from profile page is broken

- 1. Does this error occur in the account portal or the give experience page? 
- 2. Which redirect? Is it a button to navigate away or was an action expected but not performed after doing something on the page? 


> * [ ]  Failed to add a payment method. Error in console: POST https://api.stripe.com/v1/payment_methods 400 (Bad Request). Then noticed my profile was missing a country. Attempted to add a payment method again and succeeded. If this was in fact what prevented me from adding a payment method originally, it'd be good to prompt the user somehow with an error message.
- 1. Does this error occur in the account portal or the give experience page?

> * [ ]  When attempting to give once, I was prompted to add a payment method. I did and clicked "add new credit card". However, after a few seconds "loading" nothing happened. Console returned the following error: _Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received. When I attempted to click "give now" instead, it failed and the console returned the following error: "User is not a valid object." typename: "StripeAddPaymentResponse_. When I already had a payment method linked to my account (I switched accounts to my admin account for this) I was able to select it and process a donation that way.
- 1. Does this error occur in the account portal or the give experience page?

**Comment by lucastbelem** [comment]
> ## Can you provide more context?
> > **Donations**
> > 
> > * [ ]   Redirect from profile page is broken
> 
> * 1. Does this error occur in the account portal or the give experience page?
> This error was reported by you, so I'm not sure. But I believe it is referencing the give experience page as that's when the user would be required to fill up their profile info. I reported under "permissions" that the user does not get automatically redirected to fill up their profile info, which prevents them from actually seeing the menu.
> * 2. Which redirect? Is it a button to navigate away or was an action expected but not performed after doing something on the page? 
> See above
> > * [ ]   Failed to add a payment method. Error in console: POST https://api.stripe.com/v1/payment_methods 400 (Bad Request). Then noticed my profile was missing a country. Attempted to add a payment method again and succeeded. If this was in fact what prevented me from adding a payment method originally, it'd be good to prompt the user somehow with an error message.
> 
> * 1. Does this error occur in the account portal or the give experience page?
> I believe this occurred when first creating an account, by going through the give experience page.
> > * [ ]   When attempting to give once, I was prompted to add a payment method. I did and clicked "add new credit card". However, after a few seconds "loading" nothing happened. Console returned the following error: _Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received. When I attempted to click "give now" instead, it failed and the console returned the following error: "User is not a valid object." typename: "StripeAddPaymentResponse_. When I already had a payment method linked to my account (I switched accounts to my admin account for this) I was able to select it and process a donation that way.
> 
> * 1. Does this error occur in the account portal or the give experience page?
> Sadly, I'm unsure now. I believe it was within the portal, but may need to retest.

**Comment by lucastbelem** [comment]
> * Cannot seem to save changes to social media on location manager

Let me know when you've published this fix...I'll need this to try and finish the Oakville instagram issue.

**Comment by itbel** [comment]
> Pages deleted from web editor are still displaying in the public pages list. But when I click delete it says they're already deleted. I.e. oakville.json. It appears to be a refresh issue. As long as I refresh after each delete, they get deleted properly.

This is working as intended for me...

**Comment by lucastbelem** [comment]
Ok, let's check it off then.
