### ISSUE TITLE
Video import made a video disappear

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1223]
User reports that the a video (id = 2sjCeJ7Iwsc) appeared on the import section of admin and assigned the common meta descriptors, but upon checking /teaching, the video did not appear to load. When the user returned to admin to see what went wrong, the video seemed to have disappeared altogether. 

I looked for the video in DynamoDB and did not find it. The user checked other video categories thinking that perhaps they made a mistake in selecting the category. The video was not in the wrong category.

**Comment by itbel** [comment]
Videos are now manually imported via youtube video ID.
