### ISSUE TITLE
Completion of Location Maps

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1226]
Maps should load the following data related to that location:

- [x] Sunday location
- [ ] Youth midweek location
- [x] Home church locations
- [x] Compassion partner locations - Cancelled

Here is where this data is available:

- Sunday locations are in the locations manager
- Youth midweek locations are in the locations manager
- Home church locations are in the F1 sync
- Compassion partner locations are in the compassion partner table (used to be "compassion.json" under data when managed in Visual Code)

**Comment by itbel** [comment]
Youth location does not have Latitude and Longitude fields... are they the same as the parent location?

**Comment by lucastbelem** [comment]
@itbel youth locations are usually different than Sunday locations, but should also be in the location manager.
