### ISSUE TITLE
Event Summary Page

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#123]
We need to create an events summary page so that when someone clicks on the event on the location page (themeetinghouse.com/oakville) they are taken to this summary page, which will have more detail on the event, as well as give the user the ability to share the event, add to calendar, get directions to the event, and register to the event (if applicable). 

You can find the approved design for this page here: https://www.figma.com/file/pm8jTuHb1eshVL2HkwRQS9/TMH-UI-Jen?node-id=681%3A8206

For v1, this page needs to pull data from the Facebook event page where the event is created.

**Comment by lucastbelem** [comment]
Hey Andrew,

Thanks for connecting. It seems to work on my end, but it does require you to create a Figma account. Is the Figma login page not what you see? That's strange.

**Comment by lucastbelem** [comment]
Let me see if I can share the link with you in a different way.

**Comment by andrew-mcintosh** [comment]
Hi Lucas, 

I do have a Figma account and I'm logged in. So not sure about that. 

But this is what I'm seeing. 
![Screen Shot 2020-01-15 at 12 34 00 AM](https://user-images.githubusercontent.com/20049923/72407901-1abff600-372f-11ea-9b76-0df670bb2008.png)
What is the permission on the file? As it is saying I don't have permission to access the file. 

I'm seeing the 404 on the Blog Figma link. 

Cheers,
Andrew

**Comment by lucastbelem** [comment]
Hey Andrew,

Thanks for helping us sort this out. I'm gonna try sharing the link with you directly from within Figma to see if that solves the permission issue. Let me know if it's still a problem.

Thank you!

**Comment by deeinstereo** [comment]
Hey @andrew-mcintosh it was a permission issue! Sorry! I copied over the file so that you can now view it. This will work:  https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI---GitHub-Sharing?node-id=681%3A8206

Let me know if you have any questions!

**Comment by GeorgeBellTMH** [comment]
Duplicate of #127

**Comment by deeinstereo** [comment]
@GeorgeBellTMH but is it? This one deals with the actual event when clicked on, the other issue is the way the events are listed on the church's page on the website.

**Comment by deeinstereo** [comment]
hey @andrew-mcintosh just wanted to check in on this. Is this something you're still tinkering with or working on?

**Comment by GeorgeBellTMH** [comment]
I'm wondering if this is still needed?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH unless we want to continue using Facebook indefinitely, yeah, we still need to do it. But not high priority. This may next year's project.

**Comment by GeorgeBellTMH** [comment]
Closing in favour of #892
