### ISSUE TITLE
Custom Playlist (Two Series/Category)

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#124]
Currently, we can only add a video to one playlist. We need the ability to add videos to multiple playlists.

**Comment by JonEsparaz** [comment]
So not to break our existing infrastructure, could we add a new type, AdditionalCategories that is pretty much the same as Series, and create a many-to-many connect between AdditionalCategories and Videos? @georgevicbell thoughts?

**Comment by JonEsparaz** [comment]
As I just found out in #223, the above won't work. Thinking of other solutions...

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH @lucastbelem do we want a limit on the number of series per video?
