### ISSUE TITLE
Mobile UI for Go Campaign Page Fix

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#125]
When the Go Campaign page is scaled down to mobile the content that is near the bottom of the page, under the 2020 Regional Events section, doesn't work well. The header becomes super small and the gap between the bottom of the last photo with Bruxy and the community sitting down and the top of "Going beyond ourselves is too wide. I attached some screen shots to help show the difference. 
![](https://storage.www.wrike.com/filemeta/thumb100/F125932293.A623666)![](https://storage.www.wrike.com/filemeta/thumb100/F125932292.A623666)

┆Attachments: <a href="https://storage.www.wrike.com/attachments/125932292?accountId=623666">Screen Shot 2020-01-20 at 4.50.36 PM.png</a> | <a href="https://storage.www.wrike.com/attachments/125932293?accountId=623666">Screen Shot 2020-01-20 at 4.51.01 PM.png</a>

**Comment by deeinstereo** [comment]
Just go to http://www.themeetinghouse.com/go to see for yourself and compare between desktop and mobile.
