### ISSUE TITLE
Testing Outcomes - Round 2

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#1257]
Editor
- [x] User needs to be able to edit the links on the /give page as well as the text
- [x] Need to add the compassion partner table to the locations manager

Permissions Modal
- [x] This isn't happening all the time, but a couple of times now, when I go to the permissions modal, the text box is not scrolling properly. Image below:
<img width="1233" alt="Screenshot 2023-11-13 at 4 47 50 PM" src="https://github.com/themeetinghouse/web/assets/48295718/02955a30-e4f2-4205-8559-7a544874cce7">

- [x] Spirituality and Community pages sometimes load the incorrect component with the correct data. For example, the "starting questions" videos on spirituality sometimes loads the staff component. The horizontal video carousel in community sometimes load as the starting questions video component. This is resolved by refreshing the page.

**Comment by itbel** [comment]
>This isn't happening all the time, but a couple of times now, when I go to the permissions modal, the text box is not scrolling properly. Image below:
I have not experienced this and am unable to replicate the issue.

**Comment by lucastbelem** [comment]
Maybe just an internet issue on my part. Ignore it.

**Comment by lucastbelem** [comment]
> [ ] Spirituality and Community pages sometimes load the incorrect component with the correct data. For example, the "starting questions" videos on spirituality sometimes loads the staff component. The horizontal video carousel in community sometimes load as the starting questions video component. This is resolved by refreshing the page.

@itbel This issue is still occurring.

**Comment by itbel** [comment]
Should be fixed.
