### ISSUE TITLE
Events Feed Module - Local Church Pages

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#127]
The events feed on every single local church page should follow the final UI design on Figma, with unique layouts for desktop, tablet, and mobile. The events should also be organized from nearest to further in the future. Clicking on each event should open the Event Summary Page for said event. UI design here: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI-GitHub-Sharing?node-id=571%3A655

**Comment by JonEsparaz** [comment]
I'll chip away at this over the next few weeks.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH while working on the UI for this, I noticed that there's an issue with the query for the videos. The Spiritually Curious videos are displayed in the follow order by episode number: 6,3,4,1,5,2 (I assume it should be ascending).

I was digging around `src/graphql-custom/customQueries.ts` and `src/components/RenderRouter/DataLoader.ts`, but couldn't identify the issue. Any ideas?

**Comment by JonEsparaz** [comment]
@deeinstereo is this a mistake in the design?

![image](https://user-images.githubusercontent.com/48423418/83312370-12e58780-a1e0-11ea-8d90-e6322456cc2f.png)

**Comment by deeinstereo** [comment]
@JonEsparaz lol, yes it is. Good catch!
