### ISSUE TITLE
Get Connected Box "Type" - Local Church Pages

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#128]
The bottom of every local church page features a section that has a full width hero image, with a white box that has black copy that gives the user a chance to sign up for the local newsletter. This "type" or feature has not be created yet. 
See full UI design for desktop, tablet, and mobile here: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI-GitHub-Sharing?node-id=571%3A655

**Comment by nikklassen** [comment]
I'll take a crack at this one
