### ISSUE TITLE
Hamburger Menu Mobile Colour Fix

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#131]
![](https://storage.www.wrike.com/filemeta/thumb100/F125939933.A623666) When mobile user clicks on the hamburger menu it changes colour to blue. It should instead change to black with the three lines being a light grey.

┆Attachments: <a href="https://storage.www.wrike.com/attachments/125939933?accountId=623666">IMG_0863.PNG</a>

**Comment by JonEsparaz** [comment]
I don’t have the permissions to reopen #136, but I personally think that no colour change (as in this pull request) is better than changing to black. Please advise.
