### ISSUE TITLE
Download Audio + Download Video Buttons on Teaching

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#132]
Under teaching, when the user clicks WATCH, the video player launches and they have the opportunity to download the audio, or download the audio of the teaching. Currently clicking either button launches the file, but the user has to right click save as to actually download. It would be great if the content would automatically start to download the second the user click either button. 

Bonus points if you can set up tracking so we know how many people clicked download.

**Comment by GeorgeBellTMH** [comment]
Tracking can be implemented by using the amplify pinpoint service. Search the code for pinpoint to find examples.

**Comment by JonEsparaz** [comment]
Unfortunately, the files are hosted in a different path, so we can't use the `download` attribute from HTML5. Is it possible to have the files hosted in the same path instead of on [media.themeetinghouse.com](url)? (There's other ways triggering the download, but it gets a little messy IMO).

**Comment by GeorgeBellTMH** [comment]
Let me take a look at this, it should be possible with CloudFront. I will test it out on our beta site and get back to you.

**Comment by deeinstereo** [comment]
@GeorgeBellTMH any updates or thoughts on this?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH any updates on this?
