### ISSUE TITLE
Scroll button on teaching playlist not working

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#133]
If you go to [themeetinghouse.com/teaching](https://www.themeetinghouse.com/teaching) and scroll all the way to the bottom, you'll see that in the teaching carousel the arrow to move forward and view past teaching isn't working.

**Comment by JonEsparaz** [comment]
This issue does not persist on my local host. Perhaps a server-side issue?

**Comment by JonEsparaz** [comment]
Also happens on [themeetinghouse.com/teaching-kids-youth](url), but not curiously not on [https://www.themeetinghouse.com/teaching-curated](url). I will compare code and see if I can catch something.

**Comment by andrew-mcintosh** [comment]
Has this issue been fixed? I can't recreate it. 'All Teaching Series' slider works for me, on both FireFox and Chrome browsers.

**Comment by deeinstereo** [comment]
@andrew-mcintosh @JonEsparaz yup! works now! Yay for fixing!
