### ISSUE TITLE
Enable right click > copy email address for "Contact the Pastor" button

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#139]
On local site pages, the "Contact the Pastor" button is unusable if the user does not have the native mail application setup on their OS. 

Examples:
- On Windows, clicking the button opens the Outlook desktop application (which most users don't setup)
- On iOS, I use the Gmail app, but clicking the button prompts me to re-download the native mail app
- On Manjaro Linux, the button does nothing
 
Allowing users to right click > copy email address is a good solution imo.

**Comment by deeinstereo** [comment]
@JonEsparaz this makes sense, wanna give it a shot? @GeorgeBellTMH thoughts?

**Comment by JonEsparaz** [comment]
> @JonEsparaz this makes sense, wanna give it a shot? @GeorgeBellTMH thoughts?

I'll try it out and make a PR when I get the chance.
