### ISSUE TITLE
Double horizontal scrollbar on Firefox

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#140]
Two horizontal scrollbars appear on the Teaching, Spiritually and Community pages. This issue only shows on Firefox (Windows, 72.0.2) in my testing.

![double_scrollbar_firefox](https://user-images.githubusercontent.com/48423418/73236102-2ebc1c80-415f-11ea-94c4-7db97b99dc0b.PNG)

**Comment by deeinstereo** [comment]
@JonEsparaz great catch! Thanks for adding the issue!
