### ISSUE TITLE
Search results hidden on mobile

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#144]
Go to [themeetinghouse.com/search](https://www.themeetinghouse.com/search) on mobile.

When you search something, the results are hidden behind the keyboard.

**Comment by JonEsparaz** [comment]
@deeinstereo kinda brand related. Would you consider hiding the "Find a home church" and "Videos" images on mobile (at least in vertical mode, I'm not too sure about horizontal) to allow search results to appear above the user's keyboard?

**Comment by deeinstereo** [comment]
@JonEsparaz yup! Still need to clean up the search section on both mobile and desktop. Lemme think about how we can resolve this issue for mobile.

**Comment by JonEsparaz** [comment]
#167 covers this issue more broadly.
