### ISSUE TITLE
New Hamburger Manu Icon + Responsive Design

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#147]
We got the menu to not turn blue when the user clicks (win) but it would be great to have something that indicates when you've clicked on it. I found this awesome solution on another website and would love to know if we can do this: http://www.mikiyakobayashi.com/projects

The hamburger menu changes to an X when engaged. It's awesome! 

Thoughts?

**Comment by JonEsparaz** [comment]
Making some final tweaks. PR coming soon!

![check_this_out_siekanowciz](https://user-images.githubusercontent.com/48423418/75386989-9b3a5080-58b0-11ea-8f56-f4c2d0edfe1e.gif)

**Comment by JonEsparaz** [comment]
@deeinstereo as a nice side-effect, we now have full control over the hamburger menu's styling (see [here](https://github.com/cameronbourke/react-hamburger-menu) for what we can change). 

Let me know if you want to change colour, animation timing, etc.

**Comment by deeinstereo** [comment]
@JonEsparaz this is perfect! Jon! THANK YOU! I feel like it's Christmas morning! @GeorgeBellTMH @georgevicbell can we merge this PR? Please!
