### ISSUE TITLE
Social media share website preview

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#165]

**Comment by GeorgeBellTMH** [comment]
Suggest using the public/static/content/*.json to add optional metadata:[] similar to pageConfig:{} settings that inject the proper meta-data...https://developers.facebook.com/docs/sharing/webmasters/

Special work is likely needed for public/static/content/live.json and public/static/content/video-player.json to pull the data dynamically...likely also blogs.

**Comment by JonEsparaz** [comment]
We are having some unanticipated issues with this. Explanation from George:

> it looks like FB doesn't work with single page apps (google does - they use chromium in their crawler, fb - just looks at the static html returned)...

**Comment by GeorgeBellTMH** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/47749730/84364013-881c6980-ab9d-11ea-9cfa-a7501a2fa420.png">
This kinda now works...there are some errors/warnings...we need to add more og:tags...

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH what's our fb:app_id?

**Comment by GeorgeBellTMH** [comment]
This is now done, will create a new ticket for @deeinstereo and @lucastbelem for adding descriptions and ensuring titles/images are what they want, and one for performance improvements.
