### ISSUE TITLE
Teaching Page Design - V2

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#166]
Design of our teaching page needs to be updated to reflect the design in Figma found here: https://www.figma.com/file/BXPAUnmoz9SDF17nhUUWwJ/TMH-UI-GitHub-Sharing?node-id=376%3A8670

**Comment by JonEsparaz** [comment]
- [ ] "Most recent" menu styling (top of page)
- [ ] Latest video runtime (top of page)
- [ ] Watch video button styling
- [ ] Search bar
- [ ] Trending searches
- [ ] "Popular" horizontal scroll list
- [ ] "Suggestions" horizontal scroll list
- [ ] Banner-style promo cards

**Comment by GeorgeBellTMH** [comment]
For suggestions, we may be able to use: https://docs.amplify.aws/lib/analytics/personalize/q/platform/js

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH can you check if the Video type actually has anything in the length field?

**Comment by GeorgeBellTMH** [comment]
Do you mean duration? I think it should be in the YouTube info (YoutubePlaylistItemDetails.duration)...if not we may need to pull it from the YouTube api...I think my intention was to convert the YouTube duration and store it in Video.length if that was necessary...

**Comment by JonEsparaz** [comment]
I tried pulling from duration originally. As far as I can tell, both YoutubePlaylistItemDetails.duration and Video.length are null. I think we indeed need to pull from the YouTube API if we want to display video duration.

**Comment by GeorgeBellTMH** [comment]
I'll see if I can pull it tomorrow...

**Comment by JonEsparaz** [comment]
@deeinstereo @lucastbelem are there plans to start producing these "banner-style" promo cards?

![image](https://user-images.githubusercontent.com/48423418/83961879-9a2c9e00-a865-11ea-8374-caf48049c788.png)

**Comment by lucastbelem** [comment]
Hey Jon,

Yeah, for sure. We'll include it in the graphics plans for series etc.

**Comment by lucastbelem** [comment]
@JonEsparaz can you send me the specs for these graphics?

**Comment by JonEsparaz** [comment]
@lucastbelem 1104x496 or higher (maintaining the aspect ratio of course).

**Comment by deeinstereo** [comment]
@lucastbelem @JonEsparaz so here's the deal. I think the design and use of these is important, but, I think it will be different than what we originally planned. For one, we seldom get teaching series stuff in advance, and even when we do, the click and call to action would be odd because we don't have the video for it. 

Can we reuse this to instead highlight key teaching series we want people to quickly see and have access to? 

We can pick two to start now, make the graphics, and then the click and link would open up said series. 

Thoughts Jon?

**Comment by JonEsparaz** [comment]
@deeinstereo sounds good to me. The component is statically assigned so you just put whatever you want in the JSON file (I can walk you through when the graphics are ready).

We also talked about highlighting some of our podcasts - not sure if this is something we want on the main teaching page though.

**Comment by deeinstereo** [comment]
@JonEsparaz actually, the podcast bit might be a good idea. At least to do this for the after party and then link it to the playlist. For audio podcast, what would we link to? Apple Podcasts? 

Also, which .JSON file? teaching? or is there a specific one?

**Comment by JonEsparaz** [comment]
I thinking linking to Apple Podcasts is probably best for audio.

Yup you edit `teaching.json`. I left an example in the PR: https://github.com/themeetinghouse/web/pull/294

**Comment by deeinstereo** [comment]
@JonEsparaz Perfect. Thank you!

**Comment by JonEsparaz** [comment]
All the UI components are now built, so I'm closing this issue. Please see #370 for specific details on custom playlists.
