### ISSUE TITLE
Search functionality improvement

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#167]
* [ ] UI/UX improvements (recall #144)
* [ ] Improve Elasticsearch results (see [TeachingSearch.tsx](https://github.com/themeetinghouse/web/blob/master/src/components/RenderRouter/TeachingSearch.tsx) for a good starting point)

**Comment by GeorgeBellTMH** [comment]
Some improvement ideas:
- Video - search description and closed captioning
- People - search for people by name
- Events - search events by name/description
- Content - search for content
- Blogs - search for content/name

**Comment by JonEsparaz** [comment]
Adding this here for reference: https://qbox.io/blog/an-introduction-to-ngrams-in-elasticsearch

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH is it possible to setup separate indices for each video type with AWS ES? This way we can have some ranking hierarchy like: 
- Sunday teaching videos (highest)
- After Party
- Teaching Highlights
- BBQs
.
.
.
 - Kids and youth (lowest)

**Comment by georgevicbell** [comment]
Can you boost them in the query?

https://stackoverflow.com/questions/12427449/elasticsearch-boosting-relevance-based-on-field-value

It might be as simple as running the same query 5 times, filtering it on videotype and then boosting each query differently, then merging them...or if there is a way to boost based directly on the videotype, then you don’t need to merge them.



Sent from my iPhone

On Jul 17, 2020, at 4:02 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@GeorgeBellTMH<https://github.com/GeorgeBellTMH> is it possible to setup separate indices for each video type with AWS ES? This way we can have some ranking hierarchy like:

  *   Sunday teaching videos (highest)
  *   After Party
  *   Teaching Highlights
  *   BBQs
.
.
.
  *   Kids and youth (lowest)

**Comment by GeorgeBellTMH** [comment]
Ok, so I'm thinking a bit more about this now....here's the plan:

1. Create a list of search tests where we think specific results should be at the top, or it should give us specific results within the first few returned...this should give us a % of searches that are successful....and we can define tests that must, should, or ideally work...and keep a log over time...
2. Track what is being searched for, so we can add the top searched items into our tests
3. Re-code the search to override commonly searched phrases to return specific items at the top
4. Add more items to elastic search and improve the fuzzy/match/scoring logic
    - also rank videos based on type
5. Improve the design of the search bar and dropdown
6. Re-enable search on homepage

**Comment by GeorgeBellTMH** [comment]
I've added tests/SearchTests.json as a starting point...

**Comment by GeorgeBellTMH** [comment]
cc: @lucastbelem @deeinstereo 

So search is now working with the following: blogs, videos, staff, compassion...

It is currently disabled, but you can turn it on by changing the following file:

src/components/menu/menu.css
--
replace:
display: none;
with:
//display: none;

**Comment by GeorgeBellTMH** [comment]
I have also added customization...here's how it works...

In static/content/search are two files:
beginSearch.json - this is what appears when you click the magnify glass (you can customize it using the same json that works in the rest of the content files...I have left it for you guys to customize)

toronto.json - this will be shown if you type "toronto" in the search bar...right now it is just a copy of the downtown Toronto json from static...but we can modify it to whatever we want...

in toronto.json there is the following section of json:

"searchResult": {
        "hideVideos": true,
        "hideBlogs": true,
        "hideStaff": true,
        "hideCompassion": true,
        "hideShowMenu": true
      }

if you turn these to false, the results from each of those will show up after whatever you put in the json file....

**Comment by GeorgeBellTMH** [comment]
I still have some work to go:
- [ ] Fix video search results
- [ ] Improve styling of search results
- [ ] X moves around
- [ ] Email
- [ ] Compassion should go somewhere?
- [ ] Blogs should go somewhere
- [ ] Missing arrows
- [ ] Animate arrows
- [ ] Search closed captioning

**Comment by GeorgeBellTMH** [comment]
- [ ] Search HomeChurches
- [ ] Search Parishes
- [ ] Search Content
- [ ] Search Notes
- [ ] Search Playlists
- [ ] Add context to videos (teaching, kids etc.)
- [ ] Search Series
- [ ] Logging/stats

**Comment by GeorgeBellTMH** [comment]
I have created a search result renderRouter for the beginSearch.json...I have added three items to it...

**Comment by GeorgeBellTMH** [comment]
- [ ] improve sub-searches (videos, blogs, etc.)

**Comment by JonEsparaz** [comment]
I'd like to point out two issues I noticed:

1. Blogs need to be filtered. Try searching "test", you'll see Test Story, which is an unlisted blog.
2. A more important concern: accessibility. Everything is a `<div>`, which is entirely inaccessible and non-compliant with WCAG standards. Please use buttons and links (and perhaps hide the search feature until this is fixed). @lucastbelem tagging you because I believe this is fairly important.

**Comment by GeorgeBellTMH** [comment]
@lucastbelem suggest we clear out test stuff we don't need...I'll filter the unlisted stuff as well, but that doesn't guarantee it won't show up in other ways...

I'll have everything using buttons etc for tomorrow...

**Comment by GeorgeBellTMH** [comment]
- [ ] search items are buttons
- [ ] search preview items are buttons
- [ ] search field is marked with search role

**Comment by GeorgeBellTMH** [comment]
- [ ] filter unlisted items

**Comment by GeorgeBellTMH** [comment]
- [ ] use the most recently run query instead of the most recently returned query...

**Comment by GeorgeBellTMH** [comment]
- [ ] paging

**Comment by JonEsparaz** [comment]
![image](https://user-images.githubusercontent.com/48423418/120581953-a9531700-c3f9-11eb-80d2-8004dc140e12.png)

The search button's position looks a little off.

**Comment by itbel** [comment]
This should be completed with the exception of custom playlists.. as per #1084
