### ISSUE TITLE
Connect form improvements

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#182]
themeetinghouse.com/connect UI needs improvements to match our final approved design - https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=1099%3A10776

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH what's the best approach here? The iframe is pretty difficult to work with...

**Comment by GeorgeBellTMH** [comment]
Formstack also has an embed...when we were making it I had some trouble with the embed and jquery - so just to get it working I switched to iframe, but I think probably jQuery issue is now resolved...so we could try going back to the embed?

**Comment by JonEsparaz** [comment]
I tried the embed earlier this week. Formstack's embed script uses `document.write`, so it doesn't work when you load the script in `componentDidMount()`...

Might have to use a package for async script loading or get a little creative...

**Comment by JonEsparaz** [comment]
@deeinstereo since we already use Typeform for surveys, do you think we can migrate the connect form away from FormStack and onto Typeform? 

I did some reading, and Typeform looks a lot easier to embed/customize on the website.

**Comment by lucastbelem** [comment]
Hey @JonEsparaz,

here are the typeform links you may need:

Regular share link: https://themeetinghouse.typeform.com/to/PrSsyRXj
Embed code: <div class="typeform-widget" data-url="https://form.typeform.com/to/PrSsyRXj" style="width: 100%; height: 500px;"></div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

**Comment by JonEsparaz** [comment]
Thank you!

**Comment by deeinstereo** [comment]
@JonEsparaz just wanted to make sure this is captured here. In the new connect form, can we make sure that we give people the option to opt in and subscribe to our email list? Seems odd to make them fill out connect, and then subscribe to the list separately. 

Thanks!

**Comment by lucastbelem** [comment]
@JonEsparaz let me know what might need to be added to the form itself to do that. Maybe a checkbox?

**Comment by JonEsparaz** [comment]
@lucastbelem yup add it on the Formstack side. All changes to the actual contents of the form should be done on Formstack.

**Comment by lucastbelem** [comment]
What about in terms of actually enrolling their email to the form? Is that something you do or do I need to that?

**Comment by JonEsparaz** [comment]
Ideally the Typeform should work on its own, so probably something you do if possible.

**Comment by JonEsparaz** [comment]
@deeinstereo @lucastbelem some decisions for you guys to make...

Here's what the form would look like now:
![image](https://user-images.githubusercontent.com/48423418/88358299-671e6b00-cd3c-11ea-8439-262dae384dad.png)

Already an improvement over the old form, but definitely not what's on Figma. If you guys are ok with this look, we can edit the theme of the form to match website and call it a day.

If you guys want something that looks exactly like what's on Figma, we have two options:
- use Typeform's Webhook API (we can create our own frontend for the form, but the submission is still via Typeform)
- a custom solution where we again create our own frontend, but the responses get emailed to someone via AWS Pinpoint or Simple Email Service

The disadvantage of the above two solutions is if someone wants to edit the form, we have to edit what's on the website too (if we aren't planning on editing the form, it's not a problem then). 

Let me know your thoughts and if you have questions...

**Comment by lucastbelem** [comment]
@deeinstereo it's your call. One thing to note is that this form will change once or twice in the coming months. Maybe we keep it as is for now and once things go back to "normal" and we have new copy for the form, we get the webhook stuff done?

**Comment by JonEsparaz** [comment]
@lucastbelem, I was just testing the API and I was mistaken. We can't create a custom interface using Typeform, so we might be stuck with the current look.
