### ISSUE TITLE
White header on some windows

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#186]
To recreate: On mobile, go to https://www.themeetinghouse.com/, then click the yellow COVID-19 Update button.

Screenshot:
<img src="https://user-images.githubusercontent.com/48423418/81030296-57d30400-8e56-11ea-9d53-162bf9cd0804.png" height="400">

The issue will not manifest if you go directly to https://www.themeetinghouse.com/covid19.

I have determined that this bug was created by #171 (my bad). The white box is actually the navbar rendering in the incorrect colour. This issue appears on other pages (the video player in particular), but without a definite pattern. After a lot of debugging, I can't get a proper fix.

@GeorgeBellTMH please advise. Should we remove the commit? Alternatively, safer, but a little tedious, I can make a PR that essentially undoes #171.

**Comment by GeorgeBellTMH** [comment]
I think we probably need to figure out why it's happening...there is a black and a white version of the header...one has white logo and text, the other has black...so it's likely we're just having a white background with white foreground...

**Comment by JonEsparaz** [comment]
Last commit without issue: [https://github.com/themeetinghouse/web/pull/171/commits/d9f278b2afa6271e697fb4e9109f6bb5ade82418](https://github.com/themeetinghouse/web/pull/171/commits/d9f278b2afa6271e697fb4e9109f6bb5ade82418)

**Comment by lucastbelem** [comment]
The same white bar is seen in the watch window as described here: When you select a teaching video to watch, there’s now a white bar that appears across the top. Is that solved in this PR as well?

**Comment by JonEsparaz** [comment]
> The same white bar is seen in the watch window as described here: When you select a teaching video to watch, there’s now a white bar that appears across the top. Is that solved in this PR as well?

Yup.
