### ISSUE TITLE
Menu Plus Button Improvements

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#191]
To fix:
- Background turns grey on click
- Size on mobile
- Background in statically grey and + is white on some pages: 
![image](https://user-images.githubusercontent.com/48423418/81134434-b9f93b00-8f22-11ea-856b-d6946ee9f972.png)

Additional (from David's email): The only edit I have is for them to appear right away on the home page. Right now you have to go one click deep before you notice them, so please make sure they are accessible on desktop homepage. 

@deeinstereo can you clarify the last one?l

**Comment by deeinstereo** [comment]
@JonEsparaz hmm, not a fan of that grey box, is there a way to get rid of it all together? If we followed the same system as what we have on hamburger menu where the plus becomes an x that would be my first pick. Either way, that grey box just looks bad, i'd prefer to get rid of it. 

Also, it's currently static grey on home church search and doesn't look very good (desktop).

**Comment by JonEsparaz** [comment]
> @JonEsparaz hmm, not a fan of that grey box, is there a way to get rid of it all together? If we followed the same system as what we have on hamburger menu where the plus becomes an x that would be my first pick. Either way, that grey box just looks bad, i'd prefer to get rid of it. 
> 
> 
> 
> Also, it's currently static grey on home church search and doesn't look very good (desktop). 
> 
> 

Yup definitely will get rid of the grey box issue. I was hoping for some clarification on: “The only edit I have is for them to appear right away on the home page. Right now you have to go one click deep before you notice them, so please make sure they are accessible on desktop homepage.”
