### ISSUE TITLE
Create beta.themeetinghouse.com infrastructure and DNS

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#2]

**Comment by GeorgeBellTMH** [comment]
Temporary web server is up and running on amazon elastic ip: 3.209.71.20. Branden to add DNS.

**Comment by branden-eyk** [comment]
An A record pointing beta.themeetinghouse.com has been created. One externally at our hosting provider (DreamHost) and one on our internal DNS server.
