### ISSUE TITLE
Header bug persists on live site, but not localhost

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#204]
#186 was supposed to be solved by #189, but the issue seems to persist on the live site, but not localhost. @GeorgeBellTMH thoughts on this? I'm at a loss at this point.

**Comment by GeorgeBellTMH** [comment]
Clear your cache?

**Comment by JonEsparaz** [comment]
Just tried that. Issue still persists 🙁

**Comment by GeorgeBellTMH** [comment]
On a specific page? It's working fine for me on Covid page...

**Comment by JonEsparaz** [comment]
https://www.themeetinghouse.com/covid19 only if I access via the yellow button on the homepage. 

Also when I play videos.

Same as before pretty much, but I can definitely see other changes I made in that PR.

Safari on iOS 13.4.1

**Comment by GeorgeBellTMH** [comment]
It’s only there when you click from the homepage…when you refresh it is fine…

Likely some state variable is not getting set when navigating, but is when coming from the url…

G

**Comment by GeorgeBellTMH** [comment]
this line seems suspect in home menu.tsx...<div className={"navbar-custom " + this.state.logoColor} id="navbar"> ...there is no class navbar-custom.blac...

**Comment by GeorgeBellTMH** [comment]
So just as an additional bit of info, it uses the modal styles only if going to it from another page...if you just go to the url directly it loads it as a page...so I think the modal style sheet is overriding the header color...
