### ISSUE TITLE
Admin Improvements

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#210]
The following are requests for improvements to the admin interface of the TMH website.

* [x] Series names should be alphabetized
* [ ]  "Sunday short cuts" needs to be renamed to "Teasers"
* [ ] "Teasers" needs to be renamed to "Trailers"
* [ ] We need the ability to track analytics on "Download Video" and "Download Audio"
* [ ] We need an event creation interface so users can create events without dependance on Facebook events.
* [x] We need errors to return clearer results. For most users something like "Not Authorized to access publishedAt on type YoutubeSnippet" won't mean much.
* [x] Currently, when all metadata is added for a video and the user saves, an error is returned. However, the error doesn't make sense because the saving actually works.
* [x] New Series popup box not placed properly. Save button not fully visible.
* [ ] When you press "Add all new" to add new videos from youtube, there is no indication to the user that anything is happening on the page. The only way I know is by pressing function + f12 and seeing the console details. It'd be great if somehow the user knew something was happening in the background.
* [ ] Additionally to the above, it'd be great if when there are issues pulling videos from youtube, the errors that appear on the console get sent to you guys, or at least appears for the user, so the user can connect with you.
* [ ] Eventually, we'll need to talk about clearer permissions. I.e. the ability to allow someone to only allocate episodes for particular playlists; the ability to only see the blog if that's your permission and not the videos, etc.
* [ ] We need the ability to remove videos from unlisted that don't need to go to the website (i.e. private videos or the pandemic response video).
* [ ] We need the ability to remove a video that was accidentally placed in the wrong "type".

**Comment by JonEsparaz** [comment]
> We need errors to return clearer results. For most users something like "Not Authorized to access publishedAt on type YoutubeSnippet" won't mean much.

I've been dealing with something similar for blogs and notes. This error really shouldn't appear and doesn't really concern the user - will fix.

**Comment by GeorgeBellTMH** [comment]
Closing this as a lot of it is done, or not needed anymore...@lucastbelem, if there is anything in here that still needs to be done please create separate tickets and prioritize.
