### ISSUE TITLE
Order of staff on staff page and site pages

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#211]
Currently, staff/volunteers appear by first populating the Lead pastor of a site and then everyone else, in alphabetical order. This is pulling from the staff.json file and then from the coordinators.json file for volunteers. We have 2 extended family churches whose pastors don't appear on our staff.json file because they are partners, not staff. What this means however, is that when it comes to their site pages, they get pulled in from the coordinators.json list and therefore don't appear as the first person on their site pages. The reason we haven't added them to our staff.json file is that they would appear on our Staff page, which we don't want to have occur. We need a solution to get them to appear first on their pages without making them appear on our staff page.

**Comment by lucastbelem** [comment]
They are:

Sandbanks - Brent Babcock and Don Walcott.
Alliston - Michael Kotsopoulos.

**Comment by JonEsparaz** [comment]
We can just move them so that they are the first to appear for their site in the JSON file.
