### ISSUE TITLE
Highlight Reels (Watch Page)

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#215]
Highlights are currently stored as `adult-sunday-shortcut`, but they are all stored under a single series, which makes adding them to the watch page infeasible. Ideally, highlights should be associated with their respective teaching series.

Additionally, many highlights seem like they are missing and/or uncategorized.

**Comment by lucastbelem** [comment]
@JonEsparaz do you need all videos assigned before you make this a thing? I have someone who has been assigning videos to the shortcut playlist but they're not done...I just wanted to confirm whether we need to have it all done before this can become a thing or if we can make it happen and the highlights reel only appears for series that have them.

**Comment by JonEsparaz** [comment]
There will be logic to check if a series has a valid highlight reel, so it doesn't have to be all done.

**Comment by lucastbelem** [comment]
Ok, cool. If that's the case, this is probably ready to added (once you get back to TMH stuff).

**Comment by JonEsparaz** [comment]
I'm just taking a look at this. Things are working! Only thing I'm not sure about is the episode numbers... Sometimes there's multiple highlights per teaching example: 1, 1, 2, 2, 2, 3, which appears a little odd. I could hide the episode numbers for highlights - let's discuss at the Tuesday check-in.
