### ISSUE TITLE
Pull Video Duration from YouTube API

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#216]

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH I'd like to rewrite the importer so we can handle this. Turns out the `playlistItems` resource doesn't include video duration in `contentDetails`...

Is it ok if I call `youtube/v3/playlistItems` to get `contentDetails.videoId`, then call `/youtube/v3/videos` for each `videoId` to get the rest of the data? Just want to make sure I don't eat up our API quota.

While I'm at it I can add some logic to properly deal with #255.

**Comment by GeorgeBellTMH** [comment]
Yup, just make a new set of VTL files...

The API quota has been expanded twice so far...we can maybe do it again, but best to keep usage as minimal as possible...I had a list of playlists to ignore, we can add more to it (maybe anything older than 2 years)...

**Comment by GeorgeBellTMH** [comment]
(I'll add the key on my side)

**Comment by JonEsparaz** [comment]
PR (#300) is up with the VTL and schema changes.

New plan to keep the quota down: I'll just call the videos resource once for each video in the DB to get the missing data, then re-write the importer so that it only calls the videos resource to get `contentDetails.duration` for new videos (since I assume the video duration won't magically change).
