### ISSUE TITLE
Remove non-functional horizontal scroll bars on teaching page

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#220]
As far as I can tell, these...

![image](https://user-images.githubusercontent.com/48423418/81750780-2670be80-947c-11ea-90e6-ecb7a34a1263.png)

...are non-functional and kill the design.

@deeinstereo, can I remove them?

**Comment by deeinstereo** [comment]
@JonEsparaz yeah that's odd, remove! Thanks!
PS>> all your buttons are looking so great! Job well done man!
