### ISSUE TITLE
Fixing Disappearing Buttons on Give Page

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#232]
Chatted with @JonEsparaz about this. When you click one of the other ways to give the GIVE NOW button disappears. 

1. Make sure give now button never disappears. 
2. Create something to indicate which of the two other ways to give options people have clicked on. 
3. Make it so that when they click on it again the pop out box disappears instead of remaining persistent.

**Comment by JonEsparaz** [comment]
@deeinstereo here's what I got.

Give now button is static. On desktop, selected option becomes bold. On mobile, selected option gets underlined. Clicking on the selected option closes the popup.

Desktop:
![desktop_give_page](https://user-images.githubusercontent.com/48423418/82510222-112d0d00-9ad8-11ea-94de-dd74c2f8bde6.gif)

Mobile:
![mobile](https://user-images.githubusercontent.com/48423418/82510299-39b50700-9ad8-11ea-8c19-c6db968ac5b8.gif)

**Comment by deeinstereo** [comment]
@JonEsparaz this is perfect! Thank you! Let's push push push if we're good to go!
