### ISSUE TITLE
Convert/Reuse Blogs infrastructure for Notes

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#234]
Steps:

* [x] Create new schema
* [x] Determine how notes should be associated with a teaching before the video exists
* [x] Modify admin page
* [x] Modify frontend
* [x] Setup router for /notes/teaching-id

**Comment by JonEsparaz** [comment]
@deeinstereo I'm going to get started on this soon. 

A couple questions: 
- Is the idea to have notes look exactly the same as blogs on the frontend or are you thinking of having something different? 
- Currently, the notes URL is added manually for each teaching, yeah?

**Comment by JonEsparaz** [comment]
@deeinstereo another thought. Is the intention to still have a PDF version of the notes available? If so, will this be generate away from the website or do you want some way to export a PDF of the web-based notes?

**Comment by deeinstereo** [comment]
Hey @JonEsparaz sorry for the delayed response. Here's our thinking so far:

- Im 100% fine with notes looking exactly like blogs. Why not? Do you have any modifications you would make? Once we get the new PDF template from Jen we can modify accordingly. But for now this is the best place to start. 
- Yes, there are two URLS. One is for the most recent note http://media.themeetinghouse.com/podcast/handouts/Notes.pdf Then we also create a version which has the full date and sermon number and upload that to the RSS feed, which then populates the website when we link it. 
- We also want PDF still available that is correct. So you can view the notes on the website, or scroll to the top or bottom and click download and you get the PDF. We also need the PDF for the RSS feed which we use in the podcast description each week. 

Does this help?

**Comment by JonEsparaz** [comment]
Hey @deeinstereo, yup this is helpful.

In terms of modifications, I was wondering about this banner image: 
![image](https://user-images.githubusercontent.com/48423418/83072220-5e5f3080-a03c-11ea-95ed-2831ed1fe164.png)

Would you still want an image like this to appear above the title on the web-based notes?

**Comment by deeinstereo** [comment]
@JonEsparaz I'm not sure. We could try it there, or we could make it a hero image, or lose it all together. A part of me wants to cut it out so we get right to the notes.

**Comment by JonEsparaz** [comment]
Let's just leave it for now, and we can make changes if necessary. You can put an image in the text area anyways, so there's already some limited functionality for this.
