### ISSUE TITLE
Enhanced Blog Features

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#236]
Once the blogs ecosystem has matured a little, we should:

* [x] Through blog series we are able to create blog modules in certain pages that only pull particular blog entries related to that blog series. However, all blogs end up in the main blog index. Is it possible to mark a blog entry to NOT appear in the main index? The reason for this request is that we want to repurpose the blog functionality to tell stories as part of our new Go strategy. However, these don't fit into the blog strategies for the main index.
* [x] Most times we will only display 2 blogs in the home page module. However, for some applications, we may want to display 4 or more. Can we make it so that setting the limit on blog entries determines how many blogs appear in that module?
* [x] ~~"Popular" blogs on /blog~~ (not currently feasible given issue with Pinpoint)
* [x] Create blog-specific search function for /blog
* [x] Add "Similar Blog Posts" to blog reader
* [ ] Add blog to watch page
* [x] Queries for blogs by blog series
* [ ] Queries for blogs by video series 
* [x] Add blog to global search
* [x] Highlight and share (see Figma)
* [x] Image upload outside of wysiwyg text editor

**Comment by lucastbelem** [comment]
@JonEsparaz can you tackle this one? Just mark complete whatever you're able to get through during reading week and I'll re-assign whatever is left at the end. I ordered these in a priority sequence, but if from a development perspective it makes sense to do these in a different order, that's all good. The first 2 are the most important ones right now as we're trying to get this new Go page off the ground and those changes will support it.

Thanks.

**Comment by JonEsparaz** [comment]
Yup I can get on these.

Copied from closed issue, https://github.com/themeetinghouse/web/issues/536#issuecomment-721898563:

> For popular posts, we need to setup a Kinesis stream to a Lambda that records the analytics data in DynamoDB.
> 
> https://docs.amplify.aws/lib/analytics/streaming/q/platform/js

**Comment by georgevicbell** [comment]
I’ll take a look at this tonite.

Sent from my iPhone

On Nov 6, 2020, at 2:08 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

Yup I can get on these.

Copied from closed issue, #536 (comment)<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fissues%2F536%23issuecomment-721898563&data=04%7C01%7C%7Cb72acca9ad7241f421d508d88287581c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637402865089508421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DTx2xZn7J9FYyyisMl1%2FTmZd1624LGE4AfFQRGvwmwk%3D&reserved=0>:

For popular posts, we need to setup a Kinesis stream to a Lambda that records the analytics data in DynamoDB.

https://docs.amplify.aws/lib/analytics/streaming/q/platform/js<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.amplify.aws%2Flib%2Fanalytics%2Fstreaming%2Fq%2Fplatform%2Fjs&data=04%7C01%7C%7Cb72acca9ad7241f421d508d88287581c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637402865089518416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kMC6Ieaf5shgWj45WEmcvVN5G3wRrOFmvdSWeKDHDCE%3D&reserved=0>

**Comment by JonEsparaz** [comment]
@lucastbelem what's the next priority here? 

Here's what I can implement immediately:
- Adding similar blogs to the blog reader
- Blog-specific search bar on /blog

There's also some other blog-related issues I could tackle: #387, #384.

There's a couple roadblocks with other feature requests:
- Adding blogs to the video player depends on #351 (requires a bit of backend work)
- Popular blogs requires a good bit of backend work (I haven't played around with Kinesis, so I'm not sure how long this will take us)

**Comment by GeorgeBellTMH** [comment]
I have started recording data for recommendations...we need 1000 data points before it will work...

https://github.com/themeetinghouse/web/commit/f4e00a60ee6a1656ab8ebe13540fd0f5ec886a78

**Comment by GeorgeBellTMH** [comment]
Unfortunately the setup for this is not part of amplify yet...so if we want to create another recommendation dataset or include more fields we have to do it manually in Amazon...

**Comment by GeorgeBellTMH** [comment]
There is definitely more this can do, there are examples where if you show users options A,B,C,D and then they choose B it factors that in to what the suggestions are...but I want to just get to 1000 first so we enable the functionality, then we can create a more complicated version...

**Comment by lucastbelem** [comment]
> Here's what I can implement immediately:
> 
> * Adding similar blogs to the blog reader
> * Blog-specific search bar on /blog
> 
> There's also some other blog-related issues I could tackle: #387, #384.

@JonEsparaz let's tackle these then. In the order you listed them is fine. Then if there is still time, let's tackle #384 followed by #387.
 
Thanks!

**Comment by JonEsparaz** [comment]
The remain two tasks are tracked in #351. 

There are open PRs handle other features requested in this issue.
