### ISSUE TITLE
Don't use view width for font-size adjustments

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#254]
It's probably best not to scale a vertical element (the height of the font) with a horizontal measure. But I'm not sure, CSS is my weakest area. I think the best practices are to use `%` or `em`/`rem` for relative height adjustments,

_Originally posted by @nikklassen in https://github.com/themeetinghouse/web/pull/246/files_

**Comment by georgevicbell** [comment]
https://www.smashingmagazine.com/2016/05/fluid-typography/

It’s fine. Site is designed around a grid which is locked to the width. So almost all heights are related to the width (there are a few exceptions). This allows the font to scale as the width changes but not as the height changes.

Sent from my iPhone

On Jun 4, 2020, at 1:35 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

It's probably best not to scale a vertical element (the height of the font) with a horizontal measure. But I'm not sure, CSS is my weakest area. I think the best practices are to use % or em/rem for relative height adjustments,

Originally posted by @nikklassen<https://github.com/nikklassen> in https://github.com/themeetinghouse/web/pull/246/files

**Comment by JonEsparaz** [comment]
Ah ok.
