### ISSUE TITLE
Prevent private videos from importing

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#255]
After doing some investigated on why some videos aren't appearing, it looks like someone created a video early on YouTube (probably to fill in the description and whatnot), but set it as a private. Looks like these videos get imported anyways, and since the ID does not change after setting the video to public on YouTube, the videos are lost under the unlisted series and have the title "private video" on the admin page.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH just want to confirm, [`Query.getYoutubePlaylistItems.req.vtl`](https://github.com/themeetinghouse/web/blob/master/amplify/backend/api/themeetinghouse/resolvers/Query.getYoutubePlaylistItems.req.vtl) will pull and update the 50 most recent videos from the playlist? If so, we can implement the filter logic in `ImportYoutube.ts`, right?

**Comment by georgevicbell** [comment]
It might be easier/more useful to put a refresh from YouTube button on the video that repulls and replaces the YouTube object....that way we can update other information if we need to as well (even better if we can indicate the ones that are out of sync somehow)...there is so much on that admin page that needs to be improved....some of the inputs don’t even have initial values set...


Sent from my iPhone

On Jun 5, 2020, at 3:26 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@GeorgeBellTMH<https://github.com/GeorgeBellTMH> just want to confirm, Query.getYoutubePlaylistItems.req.vtl<https://github.com/themeetinghouse/web/blob/master/amplify/backend/api/themeetinghouse/resolvers/Query.getYoutubePlaylistItems.req.vtl> will pull and update the 50 most recent videos from the playlist? If so, we can implement the filter logic in ImportYoutube.ts, right?

**Comment by JonEsparaz** [comment]
Yup a refresh button is a good idea. I still think we specifically need to deal with private videos - my reason for opening this issue is @lucastbelem was unable to find some videos that imported as private, so we may need a separate video type for private videos to be partitioned off or don't import them.
