### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#270]
Would be nice to get the blog on feedly or other platforms. 

* [ ] AWS infrastructure
* [ ] create RSS feed
* [ ] add rss icon and link

**Comment by GeorgeBellTMH** [comment]
Looked into what can be done, the RSS can't be done client side....likely solution is to create a lambda that generates the RSS and then return it via API Gateway...will create the AWS side of things with dummy RSS for now...

**Comment by itbel** [comment]
blog RSS feed was implemented in #1012. Generated and uploaded daily to s3. [https://www.themeetinghouse.com/static/sitemap2.xml](https://www.themeetinghouse.com/static/sitemap2.xml)

**Comment by itbel** [comment]
added redirect blog rss lives in https://themeetinghouse.com/blog/feed
