### ISSUE TITLE
Youtube live link in admin

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#274]
Would it be possible to add the ability to update the youtube live link for Sundays via /admin instead of visual code?

**Comment by JonEsparaz** [comment]
Yes we can. @GeorgeBellTMH do you have any apprehension towards reading/writing the link from a DynamoDB table?

**Comment by GeorgeBellTMH** [comment]
Nope, that was always the plan eventually…lets do it…

**Comment by georgevicbell** [comment]
If we can schedule multiple live events ahead of time that would be amazing

- live on homepage time
- preroll video
- stream start time
- live stream video
- end on homepage time
- titles
- menu items
- chat on/off
- show kids on/off

And if we can default most of that stuff for Sunday...that would all be amazing.


Sent from my iPhone

On Jun 11, 2020, at 6:39 PM, George Bell <notifications@github.com> wrote:

﻿

Nope, that was always the plan eventually…lets do it…

**Comment by lucastbelem** [comment]
@JonEsparaz I've changed the priority on this issue - I think it's becoming more and more important for us to be able to customize this page and options within it (we could have different configuration of services, different live events, etc).
