### ISSUE TITLE
Facebook Descriptions

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#278]
All .json file content needs descriptions, and validate title/image is correct.

**Comment by JonEsparaz** [comment]
We also need to figure out how to dynamically set content for blogs, notes and videos.

**Comment by lucastbelem** [comment]
Can you guys give me more details on this? Where do we need to add descriptions?

**Comment by lucastbelem** [comment]
Nevermind, I found it.

**Comment by JonEsparaz** [comment]
> Can you guys give me more details on this? Where do we need to add descriptions?

@lucastbelem whoever is adding the descriptions can look here to quickly see which JSON files got `og-tags` added: https://github.com/themeetinghouse/web/pull/275/files?file-filters%5B%5D=.json

**Comment by deeinstereo** [comment]
@JonEsparaz this is awesome. Thanks again. @lucastbelem should we just set up a tag party one day and fly through all of these?

**Comment by lucastbelem** [comment]
@deeinstereo yep. Is this for every page? Is it something Olivia can help with? Or I can just book something for us in the next week or 2.

**Comment by deeinstereo** [comment]
@lucastbelem yes every page, we can being in Olivia and anyone else who can jump in and help.
