### ISSUE TITLE
Facebook metadata perf improvements

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#279]
If it turns out to continue being a problem, try to speed up the Facebook metadata lambda.

**Comment by JonEsparaz** [comment]
There seems to be an issue scraping images that aren't cached.

Examples...

Outside of the /images folder:

https://github.com/themeetinghouse/web/blob/18a38352f647e3329797cf4a86f01ba6c0e0f408/src/components/RenderRouter/BlogItem.tsx#L80

YouTube thumbnails:

https://github.com/themeetinghouse/web/blob/18a38352f647e3329797cf4a86f01ba6c0e0f408/src/components/RenderRouter/VideoPlayer.tsx#L84

Also, anything using this image: [`/public/static/images/og-logo.jpg`](https://github.com/themeetinghouse/web/blob/master/public/static/images/og-logo.jpg).

**Comment by JonEsparaz** [comment]
It seems that the either the scraper or the Lambda isn't getting past [`VideoOverlay.tsx`](https://github.com/themeetinghouse/web/blob/master/src/components/VideoOverlay/VideoOverlay.tsx), [`Blog.tsx`](https://github.com/themeetinghouse/web/blob/master/src/components/Blog/Blog.tsx) or [`Note.tsx`](https://github.com/themeetinghouse/web/blob/master/src/components/Note/Note.tsx) to the actual file with the tags...

**Comment by georgevicbell** [comment]
Yah...it says there is a problem with gzip compression - but it is turned on...and it is loading the images if you refresh...

Facebook only waits 10 seconds and chromium take 8 seconds to even start.

I am thinking I will rewrite the lambda to just go get the json files directly from s3 and process it...then we need to write a bit for videos/blogs/notes where it goes to dynamo...but that will be more performant and cheeper...

20 seconds of lambda right now and who knows how many times Facebook will try to reindex it...

So ridiculous though that Facebook doesn’t just use chromium on their side....

Sent from my iPhone

On Jun 12, 2020, at 6:10 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

There seems to be an issue scraping images that aren't cached.

Examples...

Outside of the /images folder:

https://github.com/themeetinghouse/web/blob/18a38352f647e3329797cf4a86f01ba6c0e0f408/src/components/RenderRouter/BlogItem.tsx#L80

YouTube thumbnails:

https://github.com/themeetinghouse/web/blob/18a38352f647e3329797cf4a86f01ba6c0e0f408/src/components/RenderRouter/VideoPlayer.tsx#L84

Also, anything using this image: /public/static/images/og-logo.jpg<https://github.com/themeetinghouse/web/blob/master/public/static/images/og-logo.jpg>.

**Comment by JonEsparaz** [comment]
Yup. Let me know if I can help with anything. Static pages are looking good though 🎉
