### ISSUE TITLE
Updates to Live page on website

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#285]
Can we do what was done for the Town Hall with the live page permanently, but for the After Party? Currently, the After Party only exists on YouTube. It'd be great if our live video disappeared after, say, 1:30pm and the live page became a "After Party" (like it did "Town Hall" last night) and had the After Party video, etc.

**Comment by JonEsparaz** [comment]
This should be possible when I’ve got #274 figured out.

**Comment by georgevicbell** [comment]
Yup with the dB changes this should be possible.

Sent from my iPhone

On Jun 15, 2020, at 1:29 PM, lucastbelem <notifications@github.com> wrote:

﻿

Can we do what was done for the Town Hall with the live page permanently, but for the After Party? Currently, the After Party only exists on YouTube. It'd be great if our live video disappeared after, say, 1:30pm and the live page became a "After Party" (like it did "Town Hall" last night) and had the After Party video, etc.

**Comment by lucastbelem** [comment]
@JonEsparaz I've changed the priority on this issue - I think it's becoming more and more important for us to be able to customize this page and options within it (we could have different configuration of services, different live events, etc). 

I've also changed the priority of #274 to line up with this issue.
