### ISSUE TITLE
Kidmax Live playlist

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#286]
This playlist seems to have disappeared from the Kids and Youth page under teaching where it was housed.

**Comment by JonEsparaz** [comment]
@lucastbelem I think this is an admin issue. Looks like Week 6 of Kidmax Live is missing some details.

**Comment by JonEsparaz** [comment]
I just set the missing details and it didn't fix the issue.

Looks like the thumbnail URLs are null... This relates to https://github.com/themeetinghouse/web/issues/255. Since the video imported as private, something weird happened and the thumbnails didn't get set.
