### ISSUE TITLE
SSL forms on the website

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#295]
Not sure if this is an issue but thought GitHub would be a good way to flag it. New and existing forms will be SSL-enabled by default on formstack starting on June 15. Take a look: https://content.formstack.com/webmail/38532/1579238774/0a50e4644226fdfbfd7de154f8fae2c3.

If it's not an issue, feel free to just resolve this.

**Comment by JonEsparaz** [comment]
Thanks for the heads up. Looks like we're already up to date, so this doesn't affect us.
