### ISSUE TITLE
Create a redirect link for the current week's notes

### ISSUE THREAD

**Issue by nikklassen** [themeetinghouse/web#302]
I've gotten feedback that it would be nice to have a bookmarkable link for the current week's notes. If you go to the livestream directly on another device, or you are running Home Church later in the week, you may want to quickly go this week's notes without going through the live stream link.

I can implement this, but I want to confirm that it's ok to have `/notes` redirect to the most recent Sunday's notes.

**Comment by nikklassen** [comment]
I guess it doesn't even have to be a redirect per-se, we could just display the most recent Sunday if the note's ID is empty.

**Comment by JonEsparaz** [comment]
@deeinstereo this is probably a question for you.

**Comment by JonEsparaz** [comment]
@deeinstereo (or @lucastbelem) thoughts on this?

**Comment by deeinstereo** [comment]
@nikklassen sorry for the late reply! Yeah let's do it! Set it up! :) On our end, the notes will aways follow this naming pattern: https://www.themeetinghouse.com/notes/2020-06-21 with the dates representing the Sunday that the teaching falls on. 
Also, just FYI we're redoing the downloadable PDF to update the format. Thanks for your help Nik! 

@JonEsparaz re issue #264 what if we added a button to Nik's notes link that was a submenu item in teaching? Maybe it only existed on Sunday + Monday until the video teaching is up?

**Comment by JonEsparaz** [comment]
@deeinstereo by submenu do you mean in the navigation menu under Teaching?

**Comment by deeinstereo** [comment]
@JonEsparaz sorry, yes that's what I meant. Thoughts?

**Comment by JonEsparaz** [comment]
Sounds good to me.
