### ISSUE TITLE
Admin: Video import not working for all videos

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#306]
As per our conversation on the phone, Jon, old teaching (say, past 2011) is up on YouTube, but isn't getting imported to Admin. Could you look into that please?

Thanks!

**Comment by JonEsparaz** [comment]
@lucastbelem could you send me the YouTube link to a couple of these videos?

**Comment by lucastbelem** [comment]
@JonEsparaz here is the playlist link: https://www.youtube.com/playlist?list=PLB5r2P47beqKLNZ_uTpBi1snugYUMwmBD
Here are a couple of videos in that playlist that don't show up in admin: 
[Series: The Way Revisited; Episode: Overcoming anger](https://youtu.be/ZxUuE3r4PbQ)
[Series: Beyond the Grave; Episode: Hell](https://youtu.be/KDEpptFwMgU)

**Comment by JonEsparaz** [comment]
@lucastbelem let me know if this was resolved.

**Comment by lucastbelem** [comment]
@JonEsparaz I just clicked "add all new" now. Didn't seem to have worked. Here is what I saw on my console:

DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
357instrument.ts:129 Write Youtube: [object Object]
instrument.ts:129 {data: {…}}
instrument.ts:129 Do mutations.createVideo
591instrument.ts:129 Write Youtube: [object Object]
instrument.ts:129 {Error mutations.createVideo: {…}}
instrument.ts:129 {kind: "youtube#playlistItem", etag: "yrJ95M2mfDDZGTngprmPmnFiepg", snippet: {…}, contentDetails: {…}, status: {…}}

**Comment by JonEsparaz** [comment]
@lucastbelem ok I'll take a closer look. If you can leave the playlist public, that'd be great - I'll let you know when we can set it back to unlisted.

**Comment by lucastbelem** [comment]
Sounds good, it'll stay public until you tell me I can take it down. :)

**Comment by JonEsparaz** [comment]
@lucastbelem I mentioned some other videos got imported. Aside from "The Classics", I think the playlists named "Teaching Highlights" and "Q & Eh?" got a bunch of videos imported.
