### ISSUE TITLE
Blog: Alignment on home page

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#307]
Something looks wonky on the blog component of the home page. The side-by-side view isn't lining up properly as seen here: 
<img width="1172" alt="Screen Shot 2020-06-25 at 12 20 16 PM" src="https://user-images.githubusercontent.com/48295718/85758431-513a6d80-b6de-11ea-8ff5-e0f087718dfc.png">

**Comment by deeinstereo** [comment]
@lucastbelem @JonEsparaz I literally just came on here to add this and POOF! It's here! :P Thanks for looking into it boys!
