### ISSUE TITLE
Problems with oneImage and oneImageBlackRight content modules

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#309]
When creating a new page, we need to be able to flip back and forth between the oneImage and oneImageBlackRight modules to help add our content to the page. Right now there is an error when you try to add a oneImage content box under oneImageBlackRight. The top of the oneImage gets covered by the previous oneImageBlackRight on mobile. Same issues happen when I change the order of the content, but need to use it multiple times. It makes it really hard to create new pages that need these modules to house content. 

It's hard to show an example of the issue now but next time it pops up I'll grab a screen shot. Again, it only happens on mobile.

**Comment by JonEsparaz** [comment]
@deeinstereo I think this is what you're talking about:

<img src=https://user-images.githubusercontent.com/48423418/85795918-100a8380-b707-11ea-9252-dde8c466f5bc.png width=40%>

I couldn't recreate the issue until I rolled back the code to a version from a month ago. I suspect I unknowingly fixed this issue when fixing these issues: https://github.com/themeetinghouse/web/issues/228

I'll close this issue for now, but please re-open if you encounter the issue again.

**Comment by deeinstereo** [comment]
@JonEsparaz I think it's still an issue. I encountered this maybe 2-3 weeks ago when I was making the First Nations Pandemic Response page, and making some edits to the home page. If you try to add another grey box under the current COVID-19 adjustments module on the home page, you'll see it persists.

**Comment by JonEsparaz** [comment]
Just tried and still can't recreate. If you could send me a screenshot that'd be great. The change I mentioned that unintentionally fixed this issue was merged a few days after you guys finished up with the FNPR edits, so the issue would've still persisted then.

**Comment by deeinstereo** [comment]
@JonEsparaz awesome! Thanks man! Sorry for the runaround!
