### ISSUE TITLE
Favicon - dark mode

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#312]
In dark mode we have a white square with the logo in it, probably should switch to an SVG with white or black icon with transparent or solid color background...

https://stackoverflow.com/questions/55170708/detect-if-the-browser-is-using-dark-mode-and-use-a-different-favicon

**Comment by JonEsparaz** [comment]
I’m working on this. Works fine on Firefox. A little buggy on Chromium-based browsers.
