### ISSUE TITLE
Trying to load local...

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#313]
Getting this error:

./src/pages/admin/index.tsx
Module not found: Can't resolve '@aws-amplify/ui-react' in '/Users/lucasbelem/Desktop/Code/web/src/pages/admin'

**Comment by JonEsparaz** [comment]
Trying running `npm install`

**Comment by georgevicbell** [comment]
npm install


Sent from my iPhone

On Jun 26, 2020, at 3:02 PM, lucastbelem <notifications@github.com> wrote:

﻿

Getting this error:

./src/pages/admin/index.tsx
Module not found: Can't resolve '@aws-amplify/ui-react' in '/Users/lucasbelem/Desktop/Code/web/src/pages/admin'

**Comment by lucastbelem** [comment]
Thanks friends...and please forgive my dumbness! ;)
