### ISSUE TITLE
Npm start issue

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#319]
/Users/lucasbelem/Desktop/Code/web/src/**mocks**/aws-amplify.ts
TypeScript error in /Users/lucasbelem/Desktop/Code/web/src/**mocks**/aws-amplify.ts(4,14):
Cannot find name 'jest'. TS2304

```
2 |
3 | const Amplify = {
```

> 4 | configure: jest.fn(),
 | ^
 5 | };
 6 | 
 7 | export const API = {

**Comment by georgevicbell** [comment]
Npm install

Sent from my iPhone

On Jun 29, 2020, at 11:12 AM, lucastbelem <notifications@github.com> wrote:

﻿

/Users/lucasbelem/Desktop/Code/web/src/mocks/aws-amplify.ts
TypeScript error in /Users/lucasbelem/Desktop/Code/web/src/mocks/aws-amplify.ts(4,14):
Cannot find name 'jest'. TS2304

2 |
3 | const Amplify = {


4 | configure: jest.fn(),
| ^
5 | };
6 |
7 | export const API = {
