### ISSUE TITLE
Admin: Video loading issue

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#333]
Hey Jon,

Can you look into why the following video isn't showing up? https://youtu.be/Qj_KH_LSpe8
I know it's just one video and it'll likely show up eventually, but it good to know why sometimes a video like this doesn't get imported.

I've clicked "add all new" and reloaded and still no luck.

Thanks.

**Comment by JonEsparaz** [comment]
The video isn't in a playlist on YouTube (probably should be in this one: https://www.youtube.com/watch?v=49znFd6ewMk&list=PLB5r2P47beqJpHmZ0jsLDRVy7jIDLrhTm).

Try adding it to the playlist on YouTube, then do "Add all new" on Admin.

**Comment by lucastbelem** [comment]
Thanks! I should've thought of that. My bad!
