### ISSUE TITLE
Kids and Youth Series showing NaN for year

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#345]
* [x] Fix issues on admin side (add missing startDate and endDate data) @lucastbelem
* [x] Add logic to hide year if value is `NaN`

This issue affects several series and is found in both scroll lists and grid view. Example:

![image](https://user-images.githubusercontent.com/48423418/87827496-00371880-c849-11ea-864f-7bf457146a62.png)

**Comment by lucastbelem** [comment]
@JonEsparaz when you say it affects many series, are you referring specifically to kids and youth videos? I know this is an issues with adult teaching (though the series don't show up at all until I enter a date), but are there other series you know of in kids and youth? I couldn't find any other problems in this category for kids and youth.

**Comment by JonEsparaz** [comment]
Grasping for God is showing 2020-NaN at the moment, but this should fixed with #349. You can still add the endDate if we know what it is though.

There "many" I was referring to:
- `ky-kids-The Story`
- `ky-jrhigh-The Story`
- `ky-youth-The Story` (I believe you fixed this one already)

**Comment by lucastbelem** [comment]
Perfect, thanks!
