### ISSUE TITLE
Blogs to series

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#351]
We need the ability to connect blog posts to series.

To-do:

* [x] update schema
* [x] update admin page
* [x] write/update queries
* [x] add blogs to watch page

**Comment by JonEsparaz** [comment]
To clarify this needs to be many-to-many?

**Comment by lucastbelem** [comment]
We need to be able to associate 1 blog to many series. One-to-many I guess?

Does that clarify this?
