### ISSUE TITLE
New fallback images not loading on prod

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#357]
![image](https://user-images.githubusercontent.com/48423418/88222788-76b28c80-cc34-11ea-893e-233bb65dc63b.png)

Doesn't look like the new images made it into the deployment bucket.

**Comment by lucastbelem** [comment]
@JonEsparaz are these the real images meant to replace the house icon? We have them, but haven't loaded them yet. Is it possible to still display the regular house icons for now?

**Comment by JonEsparaz** [comment]
These aren't the real images. Per #265, I resized the fallback image to match the size of the series image.

This is what we should be seeing for the missing images:
![series-fallback](https://user-images.githubusercontent.com/48423418/88227397-8e414380-cc3b-11ea-84d2-c6232e26e014.jpg)

**Comment by lucastbelem** [comment]
@JonEsparaz sorry I must've missed that somehow! I replaced it with the same file name. It's up now.

**Comment by JonEsparaz** [comment]
No prob. Thanks for fixing it!
