### ISSUE TITLE
Unchanging assets don't appear to be cached

### ISSUE THREAD

**Issue by nikklassen** [themeetinghouse/web#358]
I may be wrong here, but it doesn't look like we are setting a Cache-Control (max-age) header for the long lived assets like fonts, TMH logos, etc. This would probably speed up load times quite a bit

**Comment by GeorgeBellTMH** [comment]
Likely not, we could add it on some folders in cloud front automatically...just need to figure out which ones make sense...

**Comment by GeorgeBellTMH** [comment]
This is now partially done...all dynamic images now get Cache-Control added when they are generated, which is the majority of images on the site...outstanding are the assets and javascript, which I need to write a post deploy script for...I'll create a separate ticket to track those items...
