### ISSUE TITLE
Future admin improvement

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#360]
I wonder if it would be useful to have an interface via /admin to be able to create basic web pages (i.e. go to admin, select specific modules, type copy and add images) rather than using visual code. The usefulness of this would be predicated upon allowing someone other than our team to do something like, not requiring them to understand visual code.

**Comment by lucastbelem** [comment]
@deeinstereo thoughts?

**Comment by GeorgeBellTMH** [comment]
Yes...that was the longterm plan...

**Comment by deeinstereo** [comment]
Yeah one day.

**Comment by GeorgeBellTMH** [comment]
Closing this, not sure it's necessary
