### ISSUE TITLE
Live Page for Local Teaching Sundays

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#362]
We need to make some additions to the live page for the Sundays of August 16 and August 30 only.

The additions are buttons that look like the unite.jesuscollective.com page (this is offline, but George should have the html for this somewhere?) where people had multiple boxes to select which landed them in different zoom rooms. How do we get the code from the unite page and add it here? Can we add it the livestream admin tab as something that can be added to the page?

**Comment by JonEsparaz** [comment]
@lucastbelem should this go above or below the chat?

**Comment by lucastbelem** [comment]
@deeinstereo can you please answer Jon?

**Comment by deeinstereo** [comment]
@JonEsparaz this is confirming below chat. Thanks!
