### ISSUE TITLE
Teaching Page: Create/Add Custom Playlists

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#370]
These playlists are for the "Playlists" and "Suggestions" sections of the teaching page (see highlighted):

![image](https://user-images.githubusercontent.com/48423418/88861021-0fb04d00-d1cb-11ea-94d5-4ab7e46a4df9.png)

To-do:

* [x] Determine what topics/content
* [x] Create graphics for playlists
* [x] Create playlists via the admin interface
* [x] Add playlists to teaching page
* [x] Update code (likely Dataloader.ts, ListItem.tsx) as required

**Comment by GeorgeBellTMH** [comment]
➤ Lucas Belem commented:

Olivia Vanderwal hey friend! Any news on this?

**Comment by lucastbelem** [comment]
@JonEsparaz we're gonna use this a tiny bit differently than planned, just for now. 

We will not be creating graphics for the playlists...instead, most playlists consists of series, so David wants to add that "Playlists" playlist to the curated playlists page. Then, he wants to create multiple of them, each of them with a different playlist category created (i.e. God's News, Relationships, etc). Each playlist would have multiple series anyways, so we are thinking of just using the series graphics to display there as part of the playlist. Maybe we should get on the phone to talk about this? But I don't think it affects what you've done - it just means that we need to create each series as a custom playlist I guess?

**Comment by lucastbelem** [comment]
@JonEsparaz We've got graphics now to execute this as originally planned. We'll also use the secondary solution you devised for us. A 2 for 1 deal ;)

Playlists have all been created. Where do we go from here? Do you need to turn it on? Where should I drop the graphics?

**Comment by JonEsparaz** [comment]
@lucastbelem the filenames for the images aren't consistent with how the series are named in the database, so some of the images aren't loading.

**Comment by JonEsparaz** [comment]
Looks like everything is done. Good work team.
