### ISSUE TITLE
Hero Images Loading Too Slow

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#378]
We need to improve the speed of these images loading. Not sure what the best way is so I leave that with you, but right now it just takes far too long.

**Comment by nikklassen** [comment]
#358 would help after first load, lazy loading of offscreen images might also be an option

**Comment by deeinstereo** [comment]
@nikklassen I was chatting with @georgevicbell about this yesterday and he said he had somethings on his end that could help tackle this.

**Comment by GeorgeBellTMH** [comment]
I believe this is fixed now...let me know if we should re-open.

**Comment by deeinstereo** [comment]
Only time will tell! Can you guys go and have a look? My connection sucks so everything loads slowly these days.
