### ISSUE TITLE
Locations Not Loading From Locations Page

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#379]
If you google "the meeting house oakville" one of your top results takes you to https://www.themeetinghouse.com/locations/oakville/ _but_ it just loads /locations page, if you then scroll down and select Oakville or any other location, it goes to /locations/oakville/oakville which don't exist and continues this pattern forever trapping you in a terrible vortex of being stuck on the locations page forever.

**Comment by nikklassen** [comment]
I'll check if #377 has any effect on it. As for going directly to `/oakville` instead, we could set up a redirect, I'm working on another PR that will improve how we do redirects.

**Comment by deeinstereo** [comment]
@nikklassen awesome! Thanks for looking into that Nik!

**Comment by JonEsparaz** [comment]
I suggest we wipe this result from Google's index via the Search Console since this URL is from the old website.

**Comment by deeinstereo** [comment]
How do we do this? Is this something I could do or is this on George's end?

**Comment by georgevicbell** [comment]
https://search.google.com/u/1/search-console

Click on the hamburger and you should be able to open www.themeetinghouse.com<http://www.themeetinghouse.com>...

This url is not in the index...so not sure what is happening...

Probably wouldn't hurt to make a sitemap at some point...that will improve a lot of the google stuff...


George Bell
Cell: 416-802-6697

________________________________

**Comment by georgevicbell** [comment]
It looks like google may have stopped indexing the video pages, the number of indexed pages has dropped significantly...might be another thing to look at.


George Bell
Cell: 416-802-6697

________________________________

**Comment by JonEsparaz** [comment]
I can look at building the sitemap. Pretty easy to generate for the static pages based on the JSON files, but for videos and blogs we probably need a Lambda...

**Comment by georgevicbell** [comment]
Yup, just a scheduled lambda that writes the file to s3...


George Bell
Cell: 416-802-6697

________________________________

**Comment by nikklassen** [comment]
A site map would also improve our 404 performance, because our code could fetch the site map file and be able to determine if a route exists right away
