### ISSUE TITLE
Urgent Design Issues on Home Page on Mobile: Locations Module Not Functioning

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#380]
Scrolling down on the home page on mobile, the bottom of Go Campaign module does something super odd to the Locations module at the very bottom before the footer. See attached screenshots for reference. After 5+ minutes it finally loads/resolves but it pushes everything else down and creates a very awkward gap. 

![IMG_2502](https://user-images.githubusercontent.com/47831068/90026361-32d80380-dc85-11ea-883d-695853c187df.PNG)
![IMG_2503](https://user-images.githubusercontent.com/47831068/90026363-34093080-dc85-11ea-9221-4d548920ac3a.PNG)
![IMG_2504](https://user-images.githubusercontent.com/47831068/90026364-34a1c700-dc85-11ea-9ced-c9d5dea53680.PNG)

Here is the link to figma for how it should look:
https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=220%3A6248

**Comment by JonEsparaz** [comment]
I can't recreate. Here's what I get on Edge and Safari on iOS (loaded instantly):
<img width=40% src=https://user-images.githubusercontent.com/48423418/90036837-789ac900-dc91-11ea-8e34-d079a2a2c619.PNG>
<img width=40% src=https://user-images.githubusercontent.com/48423418/90036841-79cbf600-dc91-11ea-9283-7b0e1fc72781.PNG>

@deeinstereo more details would be helpful:
- Are you still able to recreate the issue?
- What version of iOS are you using?
- Did this occur on first load? Or did you navigate back to the homepage from elsewhere in the website?
