### ISSUE TITLE
Design Fix on Home Page Mobile: Awkward Large Gap 

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#381]
Right under Covid-19 (star content module) and before we move onto the teaching module, there is a large gap that's not reflected in the original design. This needs to be tightened up. 

Figma link to how it should look: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=220%3A6248

And attached reference images for what it looks like now. 
![IMG_D877B5FFE725-1](https://user-images.githubusercontent.com/47831068/90026732-b265d280-dc85-11ea-9530-5b0bbb796053.jpeg)

**Comment by JonEsparaz** [comment]
Duplicate #514.
