### ISSUE TITLE
Improve page load performance

### ISSUE THREAD

**Issue by nikklassen** [themeetinghouse/web#382]
I've started working on this, I just wanted to create an issue to track it. Main goal is to improve the performance of the initial load of the landing page.  Current performance (according to Chrome's Lighthouse) is 38/100.
First contentful paint: 2.1s
Speed index: 3.4s
Largest contentful paint: 11.2s
Time to interactive: 7.2s

I'd like to get as many of these as possible to green. So far I have performance up to about 73/100

**Comment by deeinstereo** [comment]
@nikklassen yesterday I had a call with @georgevicbell and he mentioned he needed to change some functions on his end. Maybe he'll shed more light on this so your work is not in vain?

**Comment by JonEsparaz** [comment]
@nikklassen how are things going with this? @deeinstereo mentioned page load performance at our meeting today, so I figured I'd see if you made any progress before making changes myself.

**Comment by nikklassen** [comment]
I wrote up some changes, but it was a lot and I never got around to breaking it up. In it's current state it's too big to merge without risking breaking everything. I can push a draft PR if you want to look at all the stuff I did.

**Comment by JonEsparaz** [comment]
A draft PR would be great. Thanks Nik.

**Comment by nikklassen** [comment]
Added #475

**Comment by GeorgeBellTMH** [comment]
#481 did most of this
