### ISSUE TITLE
Improving Live Page NEW Design + Dev

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#383]
themeetinghouse.com/live needs some TLC (mobile especially but desktop also needs an update)

I think we should mimic some of the the designs of our video/teaching watch page 
See here: https://www.themeetinghouse.com/videos/Grasping%20for%20God/xDcAavkhPr0
And original figma designs here: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=278%3A0

Here are some parts needed followed by a link to a mock up I did on figma that you can follow.

1. Width of embedded YouTube Video player on /live needs to be increased to match the watch page.
2. Drop the "livestream" title to appear under the embedded video player and change the title to "Church Livestream". Stylize the title the same way as on the watch page.
3. Disregard the episode title, date, and length, info, and description on current watch page. We don't need that for /live.
4. Add share button to /live (copy the watch page)
5. Move buttons under the video like on on the watch page. Buttons should be NOTES, GIVE, MUSIC, KIDMAX, CONNECT, in that order. NOTES icon should stay the same, the rest of the icons can be found here:  The Design systems is available here: https://www.figma.com/file/g2ArOwt69NbzSWJWx7Eth5/TMH-Website--New-Livestream-Page?node-id=54%3A16  My figma design reference link below will show which icons works with which text. _Also_ is it possible to make the buttons fit with 3 on one line for mobile and not just 2 as in the original design? Again, see new figma live page design below. 
6. Everything below this section shouldn't copy from watch page but be consistent with what we have developed for /live page for Sunday mornings (chat, curriculum videos, or local site buttons for local teaching Sundays). 
7. Re share button. Copy exactly how it works now on the watch page, just chance the copy to reflect "The Meeting House Livestream"

Figma mockup for new live page: https://www.figma.com/file/g2ArOwt69NbzSWJWx7Eth5/TMH-Website-New-Livestream-Page?node-id=289%3A25

**Comment by JonEsparaz** [comment]
> Also is it possible to make the buttons fit with 3 on one line for mobile and not just 2 as in the original design?

@deeinstereo yes, but if might get a little tight on smaller phones (e.g. iPhone 5). I'll see what I can do. 

Also, a thought for the buttons on the actual watch page... Are people actually trying to download the MP3/MP4 on their phone? Can we just display the notes button on mobile? Another option is changing the copy on mobile to "video" and "audio" (without download).

Per the icons, I have some disagreement on the music icon since this is the icon for teaching on the app, which would make for inconsistent iconography. Since music leads to the charts, I think we should have something a little more music theory-related rather than an icon that represents watch/listen.

**Comment by deeinstereo** [comment]
Yeah totally open to what you think is best. 

- Let's go 2 wide to keep it safe. 
- Yeah I guess no one downloads on their phone right. Can we change the copy so that on mobile we drop download?
-Find a better icon from the set and use it, I'm open to what you think is best!

Thanks!

**Comment by deeinstereo** [comment]
Some more thoughts here:

1. Since YouTube chat doesn't function on mobile and tablet, can we remove it for those two designs? Leave it only for desktop?

2. The buttons for site names (local teaching) are a little chunky. Any chance we can make the white boxes a bit more rectangular by taking down the height?
