### ISSUE TITLE
Star Blog for Spiritually Curious Page

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#384]
As per original design on Figma: https://www.figma.com/proto/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=1973%3A15671&scaling=min-zoom

The idea here is that only specific blogs that are written exclusively with the spiritually curious audience in mind would appear here. These blogs can also appear on the main blog page and be pushed to the home page if they are new, but, no other blogs would appear in this section other than these very specific ones we have specified. 

How can we make this happen?

**Comment by JonEsparaz** [comment]
This functionality already exists! 

You should be able to create a blog series, then I can write a query to pull just these blogs.

I recall you mentioned some bugs with creating a blog series, so let me know if you run into issues.

**Comment by deeinstereo** [comment]
Ah, of course. Okay sounds good! I will test and let you know! If everything is good I will close the issue, if I run into errors I'll post them here.

**Comment by deeinstereo** [comment]
Hey @JonEsparaz I created a blog series called "News" that we will use to share news and covid-19 updates. Can you write the query so I have a blog section that only pulls "news" blogs? Thanks!

**Comment by JonEsparaz** [comment]
@deeinstereo yes. Where will this blog section be on the website? Also, do you want the blogs displayed the same way as they are on /blog?

**Comment by deeinstereo** [comment]
@JonEsparaz it will be displayed at /covid i'm fine to have them be displayed the same way. Also, do blogs that get added to a new series also appear under all blogs (on the master blog page)?

**Comment by JonEsparaz** [comment]
Right now, everything (including "News") would appear on on the master blog page and homepage, but we can change this behaviour if desired.

**Comment by deeinstereo** [comment]
No no, that's good. I really like that. 

Thanks! I added the blog section to the /covid page but didn't make it live, I also added the first "news" blog and set the publish date to Tuesday. Let me know what else you need. If you pull the latest updates you'll see the changes I made to the /covid page

**Comment by GeorgeBellTMH** [comment]
Closing...

**Comment by JonEsparaz** [comment]
Reopening as we have not built the component nor have the blog post(s) been written.

**Comment by JonEsparaz** [comment]
@deeinstereo @lucastbelem any timeline on the blog posts? If we won't have the posts ready for a while, I'm going to prioritize #387.

**Comment by lucastbelem** [comment]
@JonEsparaz oh yeah. The posts are coming tomorrow morning. Sorry, I didn't realize you were waiting to see them to finish it.

**Comment by lucastbelem** [comment]
@JonEsparaz ma man, I just realized that this was about this issue. I misunderstood and thought we were still talking about the go page blogs. 

For the star blog, we don't have posts yet, but I think David has a strategy for that, and is just waiting for the the blog to exist to start implementing it. @deeinstereo, if I'm making this up, can you please let Jon know so he focuses instead on #387.

**Comment by JonEsparaz** [comment]
@lucastbelem looks like I only have time to do one of the issues, so I'm going to do #387 since there's no word on the blog posts.

**Comment by lucastbelem** [comment]
@JonEsparaz all good. Thanks for the update.
