### ISSUE TITLE
Staff images don't load if the person has >2 names

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#390]
Not loading for:
- Laura van der Kooi
- Chris van Dijk
- Rentia van der Bijl

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH doesn't look like this resolved on prod. Any idea what might be happening?

**Comment by georgevicbell** [comment]
Likely something with the rerender/caching lambda.

Sent from my iPhone

On Aug 16, 2020, at 6:24 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@GeorgeBellTMH<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGeorgeBellTMH&data=02%7C01%7C%7C10b79364476c4e67fb3308d842332576%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637332134714881288&sdata=4ngQzVRBnGltcH3W41UmoQeAhdN%2F3WyKfQYCeprPfW8%3D&reserved=0> doesn't look like this resolved on prod. Any idea what might be happening?
