### ISSUE TITLE
Improve Home Church Directory Load Time

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#399]
Best solution is probably a scheduled or HTTP trigger Lambda (via the admin page) to copy data from F1 into DynamoDB, then just read data from Dynamo.

**Comment by georgevicbell** [comment]
Ya I think I agree with this. It also allows us to bolt on additional pieces of data when we start to improve the homechurch experience.

Sent from my iPhone

On Aug 16, 2020, at 6:21 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

Best solution is probably a scheduled or HTTP trigger Lambda (via the admin page) to copy data from F1 into DynamoDB, then just read data from Dynamo.

**Comment by GeorgeBellTMH** [comment]
This is now done in the backend, just need to switch over the front end...

**Comment by GeorgeBellTMH** [comment]
Runs once a day at 9am...

**Comment by GeorgeBellTMH** [comment]
For extra information I suggest we create a secondary table and link it to this one using the homechurch ID...since this table  will add/update and potentially delete items in the table based on the information returned from F1...

**Comment by GeorgeBellTMH** [comment]
@lucastbelem and @deeinstereo - please let me know what extra info we want to track...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH awesome!! Off the top of my head, we should collect/track zoom ids so people can enter the home church when it's live.

But people above I think will want to clear this first.

**Comment by GeorgeBellTMH** [comment]
Front end is done and publish...performance improvements are complete. Will close and create a new ticket for other improvements.

**Comment by GeorgeBellTMH** [comment]
#470

**Comment by lucastbelem** [comment]
@GeorgeBellTMH thanks man! It's WAY faster now!
