### ISSUE TITLE
Way for users to trigger location services on find home church

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#400]
If I turn off/disallow location services when the browsers prompts me, there's no way for me to turn it back on (without clearing my cache).

There should be a button on the page that allows users to find home churches near them using location services.

**Comment by nikklassen** [comment]
Given #478 is this still something we want? We can't prompt the user to change their permissions (that would defeat the point of denying a site permissions), but we could add a "Find my location" button that warns the user if they've denied the location permission.

It also seems like if we want a "Find my location" it should zoom in on the map to some radius, maybe like 20km?

**Comment by nikklassen** [comment]
@lucastbelem ?

**Comment by lucastbelem** [comment]
@nikklassen sorry for the delay with this one. Let's proceed with your suggestion, Nik. Let's give the user the button, maybe call it something like "home churches around me". I think it could probably be in line with the "clear all" button.
