### ISSUE TITLE
Search icon change

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#409]
This should be locked to the top of every page so always accessible. (except for dialog boxes, overlays, forms, video player)

Can this go back in a white box. Just concerned that if a photo has a dark area at the top corner, we'll lose the icon. Also, make the icon 40% smaller than current size and make sure it's not sitting edge to edge in a white box. It should have some room around it.

**Comment by lucastbelem** [comment]
@deeinstereo are we good if we make these changes?

**Comment by itbel** [comment]
Need some clarification on this issue. Should the search icon only be visible on large screens and go inside the hamburger menu on tablets and mobile devices? 

This is how it looks currently on Mobile.
![www themeetinghouse com_(iPhone X)](https://user-images.githubusercontent.com/42515854/94620050-f46dc680-027b-11eb-8322-dc465e7238eb.png)

**Comment by GeorgeBellTMH** [comment]
I think it's fine on mobile...

**Comment by deeinstereo** [comment]
Looks good on mobile, right now I don't love how tightly to the edges its positioned on desktop. 
Here's a bigger issue for me: should we just temporarily hide search until we get it working properly. The experience is so poor right now I don't really want people using it only to be disappointed.

**Comment by lucastbelem** [comment]
@deeinstereo I second that David. Let's hide it until we get around to improving it. @itbel can you do this or does George need to do it?

**Comment by itbel** [comment]
I can do it.

**Comment by deeinstereo** [comment]
Awesome! Get it done! :)

**Comment by lucastbelem** [comment]
I think based on the latest comment, there is still an action left in this issue - hide search altogether. But I thought occurred to me - can we do that? Accessibility-wise, can we do that? Not have a search?

**Comment by deeinstereo** [comment]
Well we don't have a working search ATM, so hiding is actual the more honest option in my opinion.

**Comment by GeorgeBellTMH** [comment]
Hid it...
