### ISSUE TITLE
Visit Site Page Button

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#415]
https://www.themeetinghouse.com/find-sunday-morning

![image](https://user-images.githubusercontent.com/48423418/91088430-fced3480-e61f-11ea-9950-bf2926a9dbf6.png)

Positioning is incorrect (I think there's some extra margin). Background should be `#1a1a1a`

**Comment by deeinstereo** [comment]
Can we also change the copy from "visit site page" to "visit page"

**Comment by itbel** [comment]
The approved design does not include the map fullscreen button and calls for the map to fill up the whole width of the viewport. Currently, spanning the map the length of the viewport causes the fullscreen icon to cover the search icon on the top right. 
![localhost_3006_find-sunday-morning](https://user-images.githubusercontent.com/42515854/94701085-3ba29880-030a-11eb-967b-326f3b176d8a.png)

Should the fullscreen button be removed or moved anywhere else? Something like this?

![localhost_3006_find-sunday-morning (1)](https://user-images.githubusercontent.com/42515854/94701102-40ffe300-030a-11eb-98d2-fdbd70620093.png)

**Comment by deeinstereo** [comment]
@itbel Yup! Or add the little white box like in figma.

**Comment by itbel** [comment]
@deeinstereo Requesting further clarification.
What should be done with this button? It conflicts with the approved design as the search button is supposed to be there.
![Screenshot from 2020-09-30 12-49-46](https://user-images.githubusercontent.com/42515854/94716149-6e558c80-031c-11eb-9c56-34830b65e70a.png)
