### ISSUE TITLE
Pull ticketing URL from Facebook Events to Site Pages

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#419]
URL field for tickets/registration should be pulled from Facebook events to our event listing on the site page. Should be masked as REGISTER and then link to that.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH v8.0 of the Graph API definitely handles this with the `ticket_uri` field. I'm not sure about v4.0 though...

**Comment by GeorgeBellTMH** [comment]
This is done and publishing now - link will always say "Register".
