### ISSUE TITLE
When searching in desktop, X moves to left when results are shown...

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#432]
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/47749730/92043487-1db53880-ed4a-11ea-8487-884719b0d259.png">

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH what version of Safari are you running? I can't recreate on my Mac - perhaps an issue with the Big Sur build?

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH does this bug still occur or can we close this issue?

**Comment by GeorgeBellTMH** [comment]
I think we can close since we got rid of search temporarily...
