### ISSUE TITLE
Can't Link to Specific Series from Teaching Archive

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#434]
When users go to: https://www.themeetinghouse.com/archive/series/adult-sunday

Click on a specific series (any series) and then try to share that series the short link disappears. 

For example, I can get https://www.themeetinghouse.com/videos/Grasping%20for%20God/3SLmUqD8NzE from the main teaching page, but not from the archive if I select the series. 

A user informed about this when they tried to share a specific series from two years ago with someone and couldn't do it.

**Comment by JonEsparaz** [comment]
@deeinstereo the above PR should fixes this.

Just to confirm. There's nothing wrong with the share button, the issue is the URL does not change, which prevents copy+pasting the URL, right?

**Comment by deeinstereo** [comment]
@JonEsparaz correct
