### ISSUE TITLE
Stripe Integration

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#452]
High level requirements:

* [ ] Setup one-time and recurring giving options
* [x] Build frontend
* [ ] Setup Cognito user authentication with MFA (determine if we need to create a new user pool)
* [ ] Determine if giving numbers can be added to "customers" via the Stripe Dashboard (if not, build a simple admin page)
* [ ] Write terms of use, legal stuff

User accounts:

* Create a [customer](https://stripe.com/docs/api/customers) for each donor account
* Link the customer ID to the Cognito user
* Allow users to [add a credit card](https://stripe.com/docs/payments/save-and-reuse) for future use or [save during payment](https://stripe.com/docs/payments/save-during-payment)

One-time donations:

* This [example](https://stripe.com/docs/accepting-donations) is the closest to what we want
* If the user does not have an account, request sign up

Recurring donations:

* Create a Stripe [product](https://stripe.com/docs/api/products)
* Setup [subscriptions with ad-hoc pricing](https://stripe.com/docs/billing/prices-guide#ad-hoc) using the above product
* Allow users to edit their recurring giving (behind the scenes, we need to delete the original plan and make a new one)

**Comment by georgevicbell** [comment]
https://aws.amazon.com/blogs/security/how-to-use-new-advanced-security-features-for-amazon-cognito-user-pools/

Should be able to set different MFa settings based on client. So MFA off for iOS and on for web? I’ll play around with turning it on tomorrow.

Sent from my iPhone

On Sep 12, 2020, at 6:13 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

High level requirements:

  *    Setup one-time and recurring giving options
  *    Build frontend
  *    Setup Cognito user authentication with MFA (determine if we need to create a new user pool)
  *    Determine if giving numbers can be added to "customers" via the Stripe Dashboard (if not, build a simple admin page)
  *    Write terms of use, legal stuff

User accounts:

  *   Create a customer<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstripe.com%2Fdocs%2Fapi%2Fcustomers&data=02%7C01%7C%7C3a5b612f91bc4a0fbb0908d857691979%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637355456187832000&sdata=irZjVgGmb7FvSmNAZgYWyqmmKnzXM5tWq%2BIHTGHLpy0%3D&reserved=0> for each donor account
  *   Link the customer ID to the Cognito user
  *   Allow users to add a credit card<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstripe.com%2Fdocs%2Fpayments%2Fsave-and-reuse&data=02%7C01%7C%7C3a5b612f91bc4a0fbb0908d857691979%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637355456187841998&sdata=OZ1l%2BeegXGUckM5am87J8IL4teVeMk3lKBYAupa%2F54M%3D&reserved=0> for future use or save during payment<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstripe.com%2Fdocs%2Fpayments%2Fsave-during-payment&data=02%7C01%7C%7C3a5b612f91bc4a0fbb0908d857691979%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637355456187851994&sdata=Ff0vpIJ3c8YMhgfx8kzfE47hv3BNUwdJo%2BR3WSAVzuA%3D&reserved=0>

One-time donations:

  *   This example<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstripe.com%2Fdocs%2Faccepting-donations&data=02%7C01%7C%7C3a5b612f91bc4a0fbb0908d857691979%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637355456187851994&sdata=mCFFetKjBoMH4VJRZ%2BHzlxeSADqdpnHSiQq%2Fhah3o2w%3D&reserved=0> is the closest to what we want
  *   If the user does not have an account, collect billing/tax information

Recurring donations:

  *   Create a Stripe product<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstripe.com%2Fdocs%2Fapi%2Fproducts&data=02%7C01%7C%7C3a5b612f91bc4a0fbb0908d857691979%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637355456187861990&sdata=KMP0kNqQwnimiMRr%2FD3%2FTP8YRJ3YoWfnfIsVCbFqdCc%3D&reserved=0>
  *   Setup subscriptions with ad-hoc pricing<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstripe.com%2Fdocs%2Fbilling%2Fprices-guide%23ad-hoc&data=02%7C01%7C%7C3a5b612f91bc4a0fbb0908d857691979%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637355456187871986&sdata=huqpWj09qfdbaMtx%2B5k7hx5H%2BFcwvZw9eO3AukcObBc%3D&reserved=0> using the above product
  *   Allow users to edit their recurring giving (behind the scenes, we need to delete the original plan and make a new one)

**Comment by JonEsparaz** [comment]
Yeah I read about this in the docs. Advanced security features have a not insignificant cost though (US$0.050/monthly active user), which they conveniently don't mention in that blog.

**Comment by georgevicbell** [comment]
Of course....how long does it remember devices for? If we have MFA on the web it’s fine cuz the only login will be for donating and admin...and if the MFA on device doesn’t pop up every time you open the app it’s fine...I’m ok with it popping up once every couple of months if we can keep the login for mobile alive that long....

Sent from my iPhone

On Sep 12, 2020, at 9:09 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

Yeah I read about this in the docs. Advanced security features have a not insignificant cost though (US$0.050/monthly active user), which they conveniently don't mention in that blog.

**Comment by GeorgeBellTMH** [comment]
I've turned on opt-in for remembering devices (I assume it will need a checkbox on the login page). Also it's setup so MFA is optional per user...so we should only enable MFA if they perform a payment...(at which point we need to verify their phone/email)...once it's enabled they'll have to enter the MFA on the app or if they come back into the website, but once they do that it won't have to be done again if they opt-in to remember device...timeout is 30 days, and it resets to 30 days after each login...we can congigure it higher if we are getting lots of app MFA's....

**Comment by GeorgeBellTMH** [comment]
Timeouts are configurable based on the app client id...and we can add new ones if needed...there is currently a web one starting with 3pxxxxxx..... and the app client is 5hxxxxxx

**Comment by lucastbelem** [comment]
@JonEsparaz can you please add a time tag? Thanks.

**Comment by lucastbelem** [comment]
Stop being so fast!

**Comment by JonEsparaz** [comment]
Done. Current estimate (30 hrs) assumes we don't have to build an admin page for finance.
