### ISSUE TITLE
Find a Home Church Improvements

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#470]
* [ ] Admin interface
* [ ] Ability to set zoom link
* [ ] Welcome/Introduction video?
* [ ] Leader images?
* [ ] Ability for home church leaders to update themselves?
* [ ] Each home church gets a page (with a map, address, share, zoom, welcome video, description, events, contact info, site information (accessibility, dogs, etc.)?
* [ ] Issue #552.
* [ ] Add times back to home church listings as in previous version. (or maybe another pill? too many pills?)

**Comment by GeorgeBellTMH** [comment]
@deeinstereo @lucastbelem - thoughts and ideas....this is just a placeholder until we have a plan...

**Comment by lucastbelem** [comment]
"Think we could add this to our homechurch finder…and let homechurches pick if they have accessible homes, bathrooms etc."

**Comment by GeorgeBellTMH** [comment]
Closing this as most of it is done...@lucastbelem please create new tickets if any missing...
