### ISSUE TITLE
/Live Page Improvements (Monday-Saturday)

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#472]
TBD.

**Comment by lucastbelem** [comment]
@deeinstereo here is the spot for the changes you're thinking of in the Livestream page. Buttons show up early is implemented, so no need to worry about that.

**Comment by deeinstereo** [comment]
@lucastbelem thanks! just to clarify, this is for the Monday-Saturday page?

**Comment by lucastbelem** [comment]
@deeinstereo yeah. We can rename the issue. I originally thought you had changes you wanted implemented for Sunday as well, but now that's all ready, we just need the Mon-Sat changes :)

**Comment by lucastbelem** [comment]
@deeinstereo just checking that you're still adding details to this issue?

**Comment by deeinstereo** [comment]
Yes sorry! I haven't had time to sit down and sketch it out!

**Comment by lucastbelem** [comment]
All good, all good!

I saw you changed the title so wanted to make sure you didn't think you added the details too :)
