### ISSUE TITLE
"What we do" section on /compassion

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#485]
We need to make some changes to this section. Unfortunately, this is a bit of a rush (needs doing in time for Sunday), but I didn't realize that it wasn't editable in visual code. Could someone do one of the following 2 options:

1. Make it so that this component is editable in visual code? OR;
1. Make the following changes:

* [ ] Remove "Discipleship Development"
* [ ] Change the component title to "Our Focus"
* [ ] Change "Peacebuilding" description to: "We are committed to non-violence, peacemaking, and being agents of reconciliation. We invest in peacebuilding because peace is the foundation for all other levels of development to be built on. We do this through pursuing Indigenous reconciliation, refugee sponsorship, restorative justice, relief, and peace literacy."
* [ ] Change "Poverty Alleviation" description to: "We aim to play a part in working against global poverty by partnering with two communities in Malawi: Mposa & Chamba. We’ve been walking with both communities since 2011 investing in education, childhood well-being, healthcare, economic development, and water and sanitation health."
* [ ] Change "Global Church Partnerships" description to: "As a church, we recognize that we are one small part of the larger body of Christ. We partner with like-minded and under-resourced local churches in low to middle income countries in the areas of leadership development, theological development, evangelism, and the persecuted church."
* [ ] Change "Local Engagement" description to: "Parishes embed themselves into their communities to learn and listen to the unique opportunities that are present and then respond relationally and with humility. The result is a grassroots network of Jesus followers working for justice and building relationships with marginalized members of their community."

**Comment by itbel** [comment]
Hey Lucas. These changes can be made by going to these files:
/public/static/content/compassion.json
/public/static/data/compassion.json
