### ISSUE TITLE
Horizontal scrolling occurs

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/web#486]
page content is going out of main view causing unintended horizontal scrolling to occur.
![overflowing](https://user-images.githubusercontent.com/42515854/94317726-df7bf500-ff54-11ea-8159-f2f440f07d32.png)

**Comment by itbel** [comment]
Having trouble finding all the items causing the overflow. Could overflow-x:hidden; be a partial solution to this?

**Comment by GeorgeBellTMH** [comment]
It appears that setting padding:0 on the anchor inside of the items of Teaching resolves the horizontal scroll issue...

**Comment by GeorgeBellTMH** [comment]
Fixed this
