### ISSUE TITLE
Notes Loadings Really Slowly

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#487]
Lots of problems this morning with how long it takes for the notes to load. Got plenty of comments and texts about it this morning. Can we improve the speed of the notes?

**Comment by itbel** [comment]
Requesting some more info on this issue. Is it slow to just load the page, or is it when you download the pdf?

**Comment by deeinstereo** [comment]
@itbel the whole page. Just trying going to: https://www.themeetinghouse.com/notes and see what happens. 

Thanks!

**Comment by JonEsparaz** [comment]
There's a lot of extra data being passed since we now add Bible verses to the notes and add a connection to the video series. My suggestion is writing a custom query that only pulls the data needed for notes on the website.
