### ISSUE TITLE
Popular Highlights - New Playlist

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#507]
A playlist that automatically pulls the top 10 most popular highlights (or clips that have been identified as teaching-shortcut). We judge popularity based on the last 60 days, and pull the 10 that have the most views in that time period. 

Is that doable?

**Comment by JonEsparaz** [comment]
This is certainly doable, but highlights have low view counts (the top 10 from the past 60 days includes videos with ~150 views), so we probably need to record view count for all videos (ie no lower bound for view counts).

If we eliminate the lower bound, we should prevent kids curriculum from recording view count to limit excess DynamoDB operations.

**Comment by deeinstereo** [comment]
@JonEsparaz no I want to focus exclusively on those that we identify as teaching short cuts. The views aren't as low as you think (although I agree, they're not as high as regular teaching). Can we make it so it pulls exclusively from that list? That way how many views they get doesn't matter, it's just based on what are the top 10 most popular ones from this category. The other big win here is that they are short. 

Lemme know!

**Comment by JonEsparaz** [comment]
Ah, gotcha... Misunderstanding on my part. 

My recommendation is we just record view count if the video is in `adult-sunday` or `adult-sunday-shortcut` since these are the only types of videos we actually use view count stats from. This would also partially clear up #506.

**Comment by JonEsparaz** [comment]
I can implement this quickly.

Just so I can do everything in one shot, @deeinstereo:
- what page do you want this on? 
- where on that page?
- what should the header be?

**Comment by deeinstereo** [comment]
@JonEsparaz you're the best!  adult-sunday-shortcut is exactly what I want to focus on! 

- /teaching
-I can move it around but near the top, probably just above all the series.
- Popular Highlights

How's that?

**Comment by JonEsparaz** [comment]
Great thanks. Should be done tonight.

**Comment by deeinstereo** [comment]
Wow, the best. Thanks man!
