### ISSUE TITLE
Suggested Videos Playlists always start with #2 video and not #1

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#510]
See attached images. Why does this happen? Can we fix it? 
![Screen Shot 2020-10-08 at 3 52 18 PM](https://user-images.githubusercontent.com/47831068/95506769-59ad7000-097e-11eb-99ad-b3b357ab46e7.png)
![Screen Shot 2020-10-08 at 3 52 10 PM](https://user-images.githubusercontent.com/47831068/95506777-5c0fca00-097e-11eb-8817-6aacba902b96.png)

**Comment by JonEsparaz** [comment]
I assume it depends on the order in which you guys added the videos. We can sort by date.

**Comment by deeinstereo** [comment]
Yes that would make the most sense. At least that way it would be chronological
