### ISSUE TITLE
OG Tags Not functioning 

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#511]
I didn't realize they stopped. Does anyone know anything about thus?

**Comment by georgevicbell** [comment]
I’ll take a look. Might have wiped out some config.

Sent from my iPhone

On Oct 8, 2020, at 4:13 PM, David Siekanowicz <notifications@github.com> wrote:

﻿

I didn't realize they stopped. Does anyone know anything about thus?

**Comment by deeinstereo** [comment]
Thanks man! I appreciate it! #blessed

**Comment by GeorgeBellTMH** [comment]
Ok they are back...json and videos have been tested and work...still to do: notes, blogs

**Comment by GeorgeBellTMH** [comment]
Ok this is fixed....
