### ISSUE TITLE
📷 I can't make this picture disappear... 📷

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#513]
![Screen Shot 2020-10-14 at 10 09 33 AM](https://user-images.githubusercontent.com/47831068/96021574-a29d7280-0e1d-11eb-9c98-e7092ec61a30.png)

See that photo of Jordan and Andrea? I've changed and updated this photo a long time ago, and it always comes back! Is this a cache thing that needs to be cleared on your end @GeorgeBellTMH or is there something else I'm doing wrong here?

**Comment by deeinstereo** [comment]
And here's another one! I swear I have deleted these from the folder and they keep appearing! 
![Screen Shot 2020-10-14 at 3 58 46 PM](https://user-images.githubusercontent.com/47831068/96054328-6d117d00-0e4f-11eb-97a6-5b72832b111a.png)

**Comment by GeorgeBellTMH** [comment]
Try new file names!

**Comment by deeinstereo** [comment]
Now this, this is the sort of development work I can do! 👍

**Comment by deeinstereo** [comment]
Resolved!
