### ISSUE TITLE
📱 Re-design and edits to CSS for existing page and modules 🖥️

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#514]
**Desktop** 
There's zero space between the locations module and the email/connect module. See attached photo. We need some space here. 
![Desktop Issues 1](https://user-images.githubusercontent.com/47831068/96044925-32074d80-0e3f-11eb-9728-3db4e86f93e6.png)

**Mobile**

1. Big gap between the top of the Teaching module and the bottom of Star Content (this month it's COVID update). I think this needs to be tightened up. See Mobile issue 02
![Mobile_Issue_02](https://user-images.githubusercontent.com/47831068/96045502-0769c480-0e40-11eb-8721-7ea6d3c53e9c.PNG)

2. Big gap between the bottom of Go Campaign update and top of the connect/email module. See Mobile issue 01
![Mobile_issues_01](https://user-images.githubusercontent.com/47831068/96045731-616a8a00-0e40-11eb-9b96-db7c664c1f29.PNG)

**Comment by GeorgeBellTMH** [comment]
This should all be fixed now...

**Comment by GeorgeBellTMH** [comment]
I've added a showFooter=true/false on connect modules....this will be the way going forward...so that when they are at the bottom of a page you can do showFooter=false or if in middle of page you can do showFooter=true....need to duplicate it on all the other components over time...

**Comment by deeinstereo** [comment]
@GeorgeBellTMH WOW! THANK YOUUUUUU! :D THIS MADE MY DAY! 
The desktop looks *kisses finger tips* perfect!  But any chance I can get a few teeny tiny tweaks for mobile? Let me know if this is doable:

Again, JUST FOR MOBILE>> 
1. Spacing under Covid-19 and above teaching >> now it's a tiny bit too close. Any chance you could double the white space? I want to show that it is a different section.
2. Spacing under go campaign and above email >> same thing. It's a teeny tiny bit too tight. Can you just double the white space that's there? 

Let me know! @GeorgeBellTMH

**Comment by deeinstereo** [comment]
@GeorgeBellTMH any ETA on this? Thanks for your work!

**Comment by lucastbelem** [comment]
@mmacedom along with the other issue I assigned to you, would you mind resolving the last couple of requests from David in this one too? 

Thanks!

**Comment by mmacedom** [comment]
@lucastbelem @deeinstereo I just push some fixes to addess the issues mentioned above. Let me know if they are good on your end.

**Comment by deeinstereo** [comment]
Awesome! Will have a look once it syncs!

**Comment by GeorgeBellTMH** [comment]
Can we close?

**Comment by mmacedom** [comment]
@deeinstereo, everything good with the changes?

**Comment by deeinstereo** [comment]
@mmacedom I think so? I didn't check to be honest but if you worked on it and George closed it then I am confident! 👍
