### ISSUE TITLE
New variation of live page

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#517]
For leaders day next Saturday (October 23) I need to set a livestream page, but it needs to be slightly different. Or maybe we can just add these options to the current livestream admin set up?

I need a live page that allows me to group zoom rooms in different breakouts (similar to what we did for Unite back in May). It may just be a matter of letting me set a header before adding zoom rooms so I can create multiple of segments. 

@deeinstereo do you see an issue if this lives at /live given that this is a private event? We could have it there and just not make it appear on the home page, but if someone types the link they'd still find it. Should we have it under /leadersdaylive instead?

**Comment by lucastbelem** [comment]
@itbel would you be able to take this one today please? We can talk about the details around it.

**Comment by itbel** [comment]
Sounds good.

**Comment by lucastbelem** [comment]
- [ ] Clone /live page and make it live on /leadersdaylive
- [ ] Buttons to display (pointing to the same existing urls): Give | Connect @deeinstereo?
- [ ] Remove "Share" option from page
- [ ] Change "Church Livestream" Header to "Leaders Day Livestream"
- [ ] Add a header in the same style above zoom links titled "Breakouts 1 and 3" ([Zoom links here](https://docs.google.com/spreadsheets/d/1qaQj7datwA7gya6gpI8hbE0trRz0ls4LKO7Vn5PYCzc/edit?usp=sharing))
- [ ] Add a second header in the same style below the zoom links titled "Breakout 2" (Zoom link tbd)

**Comment by lucastbelem** [comment]
@itbel Sorry, [USE THIS SPREADSHEET FOR BREAKOUTS](https://docs.google.com/spreadsheets/d/1lmRgTEzEHcr8LPGfm42pXFfIhsF58qd21TOzyygnt8Y/edit?usp=sharing).

**Comment by itbel** [comment]
- Missing zoom links for Oakville and Sandbanks
- Should I omit chatbox
- Is there a youtube live event id?
- Starting time for the event
@lucastbelem

**Comment by itbel** [comment]
What should show if the event isn't live?

**Comment by lucastbelem** [comment]
@itbel:

- I'll let you know about the Oakville and Sandbanks links as soon as I hear back from Louise. 
- Omit chat box
- Youtube link will come tomorrow
- Event goes live at 9am on Saturday, October 24 and ends at 12:30pm
- If the event isn't live, it can just show the main livestream video link.

**Comment by lucastbelem** [comment]
> * Buttons to display (pointing to the same existing urls): Give | Connect @deeinstereo?

Go ahead and leave only Connect for the button.

**Comment by lucastbelem** [comment]
@itbel Sandbanks: https://us02web.zoom.us/j/5484557238

**Comment by lucastbelem** [comment]
@itbel live id: https://youtu.be/UYfFdEZ_v2c

**Comment by lucastbelem** [comment]
@itbel page looks great! No design changes from David. A couple of tweaks from me:

- Breakout 2 Zoom 1 should be called "First Name: A - K"; Here is the link: https://us02web.zoom.us/j/81730640198
- Breakout 2 Zoom 2 should be called "First Name: L - Z"; Here is the link: https://us02web.zoom.us/j/84178766161
- Please rename the link from "/liveleadersday" to "/leadersdaylive"
- Can you please make it "Leaders' Day Livestream" shows before 9am as well so it doesn't say "Leaders Day Livestream Pre-show"?
