### ISSUE TITLE
Clicking "x" while watching a video sends user to home page

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#522]
When a user goes to /teaching and clicks to watch something, the appropriate screen pops up allowing them to watch their video. However, when they click the "x" to leave the page, they're taken back to the home page, rather than the page they were previously on. Can we change this to take the user to the page they were previously on?

**Comment by lucastbelem** [comment]
@nikklassen any chance you can take a look at this one when you have time?

Thanks

**Comment by nikklassen** [comment]
I noticed this the other day too, it's pretty annoying. I should be able to take a look this week.

**Comment by deeinstereo** [comment]
@nikklassen and the masses cry out, "THANK YOU NIK!"
