### ISSUE TITLE
📇 Fix + Redesign Contact Leaders Home Church Pop-up 📇

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#525]
Improve the design of the Contact Leaders Form: https://www.themeetinghouse.com/find-homechurch

1. Make Send Message and Cancel buttons white with black text.
2. Bring buttons over to the left side, Send message first, cancel second. 
3. The black box at the bottom takes up way too much space on mobile and pushes the two buttons down too far.

**Comment by mmacedom** [comment]
@deeinstereo @lucastbelem I just pushed a number of fixes addressing these issues. Let me know if it's all good on your guys' end

**Comment by GeorgeBellTMH** [comment]
Can we close?

**Comment by mmacedom** [comment]
If @deeinstereo and @lucastbelem are good with the changes @GeorgeBellTMH . Yes.
