### ISSUE TITLE
❌ Sharing Link Previews as Error on Social ❌

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#526]
When sharing a blog post or notes (https://www.themeetinghouse.com/posts/Religion%20+%20Politics%20=%20Politics or https://www.themeetinghouse.com/notes/2020-10-25) the preview link on Facebook says "error" and looks like this >> 

![Screen Shot 2020-10-27 at 9 50 59 PM](https://user-images.githubusercontent.com/47831068/97381269-1f5d3180-189f-11eb-87af-858f18de2234.png)

Help!

**Comment by JonEsparaz** [comment]
This is related to https://github.com/themeetinghouse/web/issues/511. Both issues are symptoms of the same problem.

**Comment by GeorgeBellTMH** [comment]
This is fixed.
