### ISSUE TITLE
👨‍🚀 Update Spiritually Curious Video Buttons 👨‍🚀

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#527]
The 6 white boxes on this page that contain the video questions:
https://www.themeetinghouse.com/spirituality

Can we redesign those so that instead it's the thumbnail from the video at lower opacity so that the text is visible, then when you scroll over it, the thumbnail changes to grey and the watch video button appears (same way it works now on desktop). 

We have the thumbnails for these videos, I've uploaded them here. 
![Did Jesus exist?](https://user-images.githubusercontent.com/47831068/97382270-5cc2be80-18a1-11eb-9bd4-ea4863af9d25.jpg)
![Why belong to a curch?](https://user-images.githubusercontent.com/47831068/97382273-5d5b5500-18a1-11eb-8142-848d6116d76c.jpg)
![Why is there so much suffering in the world?](https://user-images.githubusercontent.com/47831068/97382274-5d5b5500-18a1-11eb-973f-f5b3b1bf63eb.jpg)
![Why is there so much violence in the bible?](https://user-images.githubusercontent.com/47831068/97382276-5df3eb80-18a1-11eb-8060-4e496140d041.jpg)
![Why Jesus?](https://user-images.githubusercontent.com/47831068/97382279-5df3eb80-18a1-11eb-98d3-84ceaceed3aa.jpg)
![Why learn from the Bible?](https://user-images.githubusercontent.com/47831068/97382280-5e8c8200-18a1-11eb-8261-4f9e5efee9b9.jpg)

**Comment by JonEsparaz** [comment]
@deeinstereo can we go with a 50% grayscale filter instead? I like this option because the text never changes colour.

Opacity:
![opacity](https://user-images.githubusercontent.com/48423418/97391038-a49f1100-18b4-11eb-833b-aa2e41b1d5fc.gif)

Grayscale:
![greyscale](https://user-images.githubusercontent.com/48423418/97391040-a49f1100-18b4-11eb-8f15-30034dd95b3e.gif)

**Comment by deeinstereo** [comment]
@JonEsparaz GRAYSCALE! Love it! Thanks
