### ISSUE TITLE
Mobile Links in Footer

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#529]
There is a design for adding the android and iOS icon/links in the footer...now that we have mobile apps we should re-enable them.

**Comment by GeorgeBellTMH** [comment]
@deeinstereo let me know when you are ok for us to do this...not sure if there are other changes you want to make to promote the app...

**Comment by GeorgeBellTMH** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/47749730/97809544-69496d00-1c3b-11eb-9229-0b060ace50e0.png">

**Comment by deeinstereo** [comment]
@GeorgeBellTMH that's perfect! What if we added it to the video player, right underneath where we promote the podcasts. Thoughts?

**Comment by deeinstereo** [comment]
@GeorgeBellTMH as far as timelines. Let's get it up on the website by this weekend if possible. 

Thanks!
