### ISSUE TITLE
Styles on Find a Home Church Page

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#538]
* [ ] Buttons on contact leaders form are taller than the background area
![](https://user-images.githubusercontent.com/48423418/97792701-f0550180-1bb7-11eb-8644-7801672b4a58.png)
* [ ] List of home churches overlaps with footer
![](https://user-images.githubusercontent.com/48423418/97792493-5be99f80-1bb5-11eb-832d-4eb73a6ecb88.png)

These issues were mentioned in my review of #523.

**Comment by itbel** [comment]
Which resolution is this? 
I worked on the bottom issue for resolution 1280x720 and should have been fixed by #533

**Comment by JonEsparaz** [comment]
Still 1280x720 (for more context, my screen is 2560x1440 but scaled by 200%). That being said, the browser console says `window.innerHeight` is 550 and `window.innerWidth` is 1280 (as expected).

The above screenshots are from the production site after #533 was deployed.

**Comment by JonEsparaz** [comment]
`calc(88vh - 149px)` is a quick way to fix the second issue. 88vh is the height of the map. 149px is the fixed height of the dropdown menus at the top, and the home church listing should fill the remaining height.

**Comment by itbel** [comment]
Thanks Jon. I'll take a look at it again.
