### ISSUE TITLE
CSS improvements

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#546]
The website has a bunch of sma tweeks needed on mobile.

Here is an example of 1 page, the /oakville page (this is replicated across all site pages):

```
The "livestream" and "contact" buttons are misaligned.
```
![Screenshot_20201108-095810_Chrome.jpg](https://user-images.githubusercontent.com/48295718/98468598-2c382a00-21a9-11eb-832e-42d36e442bf8.jpg)

```
There is a lot of blank space between the home church and the make a difference modules.
```
![Screenshot_20201108-100025_Chrome.jpg](https://user-images.githubusercontent.com/48295718/98468624-5689e780-21a9-11eb-9f56-07438276eb51.jpg)

```
There is a lot of blank space between staff members on the staff page. 
```
![Screenshot_20201108-100238_Chrome.jpg](https://user-images.githubusercontent.com/48295718/98468857-60601a80-21aa-11eb-81b8-f230e0c4faa7.jpg)

```
Again, lots of space between the events module and kids and youth.
```
![Screenshot_20201108-100828_Chrome.jpg](https://user-images.githubusercontent.com/48295718/98468870-6f46cd00-21aa-11eb-8964-17cfad44073d.jpg)

**Comment by lucastbelem** [comment]
@deeinstereo before @mmacedom does anything with this, can you take a look and make sure you agree these changes are needed?

Thanks!

**Comment by deeinstereo** [comment]
Yes these changes are very needed @lucastbelem I'm good with whatever @mmacedom says looks good and needs to happen. Thanks!

**Comment by lucastbelem** [comment]
Awesome! @mmacedom could take this one please?

**Comment by mmacedom** [comment]
@deeinstereo @lucastbelem I just pushed a new PR fixing all of the issues above. Let me know if there's anything else to be done on this log.
