### ISSUE TITLE
Live page refresh

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#551]
Some users report that if they go to the live page earlier than startVideoTime, the video doesn't automatically refresh to the live video. It stays on the pre-roll until they've refreshed the page. Is there a way to make it automatically change?

**Comment by GeorgeBellTMH** [comment]
It does...will need more information to determine the problem:

- Browser/version
- Time they connected to site
- When the admin was updated
- Timezone

**Comment by GeorgeBellTMH** [comment]
Closing unless there are more details

**Comment by lucastbelem** [comment]
@GeorgeBellTMH sorry. I need to circle back with them to get those details.
