### ISSUE TITLE
🏠  Home Church Finder Copy changes 🏠

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#552]
https://www.themeetinghouse.com/find-home-church

Can we make the days singular instead of plural? It reads awkward to always see "Thursdays, Saturdays, etc". 

Also, thoughts about adding an All Parishes option at the top of parish selection?

**Comment by lucastbelem** [comment]
@deeinstereo I don't think the "all parishes" option is needed. That's by default how home churches load if the user doesn't select a parish.

**Comment by georgevicbell** [comment]
I noticed yesterday though that once you select one you can’t undo it and go back to all of them...except by clicking reset...

Sent from my iPhone

On Nov 10, 2020, at 3:36 PM, Lucas Belem <notifications@github.com> wrote:

﻿

@deeinstereo<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeeinstereo&data=04%7C01%7C%7Ce89901c6f3be46402c9f08d885b84b58%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637406373862089149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fvlGXJulUwbwqHk9LPZ2uFxgjHKHdEy3AmOHzqjGypg%3D&reserved=0> I don't think the "all parishes" option is needed. That's by default how home churches load if the user doesn't select a parish.

**Comment by itbel** [comment]
Clear all button doesn't seem to be clearing the day selection field

**Comment by itbel** [comment]
If we have it for the days dropdown, shouldn't we also have it for the parishes dropdown? 
This does make the clear button a little redundant though.

**Comment by itbel** [comment]
Why was this commented out? 
` src/components/RenderRouter/HomeChurchItem.tsx`
Line 322 `//    this.selectControlDay?.select.clearValue();`

It was being used to clear the day selection dropdown. Did it break anything?
@GeorgeBellTMH

**Comment by GeorgeBellTMH** [comment]
There was a compile issue...if it's working you can uncomment it...
