### ISSUE TITLE
Videos from youTube to admin taking too long

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#553]
We need to do some investigating. Some videos don't appear quickly. For example, this week the teaching video from November 8 was uploaded to youTube by noon on Monday November 9th. When we went to /admin to link it to the website, it was not there. Pressing "add all new" did not work.

On Tuesday, November 10th at 9am, we went to admin and the video was still not displayed. Pressed "add all new" and still the video did not appear. 

Finally, on Tuesday, November 10th at 11am we went to admin and pressing "add all new" actually added the video. However, the time displayed for the youTube upload was 4:57pm rather than noon when we got it uploaded.

Help?

**Comment by JonEsparaz** [comment]
@lucastbelem having the video IDs in question would be useful to investigate.

If I had to guess, it seems like YouTube might've changed something with their API endpoint, so I'll ability to fix the issue might be limited.

Assuming this is a viable solution, would the ability to manually enter a video id to force a pull be useful?

**Comment by lucastbelem** [comment]
@JonEsparaz here is the ID for the video I used as an example: izQcyu2yJmM

For sure, if your suggestion is possible, it would be helpful in the meantime. But the weird thing is that it doesn't always happen. Some videos, some weeks appear when they are supposed to.

**Comment by lucastbelem** [comment]
@JonEsparaz did you ever get around to making this possible - The force a pull by entering the id as a workaround solution for now?

**Comment by JonEsparaz** [comment]
I did not - wasn't aware that it was a top priority. 

Implementing this is a little bit involved as we need a new VTL resolver, but definitely doable.

**Comment by lucastbelem** [comment]
Duplicate of #632
