### ISSUE TITLE
Search Style

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#555]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/47749730/98747438-7e35a700-2385-11eb-9d5d-bf9ae78bb75c.png">

1. Did we want to include the thumbnail of the video?
2. Is there some way we can put a border around the results or around the entire search component when it is in this mode, it's a bit confusing without some kind of divider with the next component on the page...

**Comment by JonEsparaz** [comment]
1. The Figma mockup does not include the video thumbnail, but it can be added of course.

2. The search results are supposed to to look like this:
![image](https://user-images.githubusercontent.com/48423418/98747771-32373200-2386-11eb-8eaf-ace2715781d4.png)

Search results are positioned above the other components, background blurs.

**Comment by JonEsparaz** [comment]
I think I have a good solution for the blurred background. I'll take a look.
