### ISSUE TITLE
💨Will changing a page name mess everything up? 💨

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#570]
I want to change /teaching-curated to just /videos
I already changed the Curated Playlists sub-menu button to Video Playlists. More and more of this content will be different than just teaching (eg. music videos and interviews) and I think /videos is an easier place to send people and makes more sense with the button. 

Thoughts? Is this simple or will it ruin our architecture?

**Comment by GeorgeBellTMH** [comment]
I have no idea...try it locally and see...it may...

**Comment by GeorgeBellTMH** [comment]
Closing...let us know if there is a problem...
