### ISSUE TITLE
Home Page Only Pulling 1 Blog Instead of 2

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#573]
I checked the backend on the homepage and it says limit 2, but only pulling 1. 
Help!

**Comment by JonEsparaz** [comment]
This is a bug produced by the ability to hide blogs from the main index. I already addressed this in #565 (pending merge).

**Comment by georgevicbell** [comment]
I’ll put it in tonite.

Sent from my iPhone

On Nov 20, 2020, at 5:36 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

This is a bug produced by the ability to hide blogs from the main index. I already addressed this in #565<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fpull%2F565&data=04%7C01%7C%7Cf5d944b102304f4c7fbe08d88da4b569%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637415085840616005%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5sJSQ%2FnUz3QrHHXS3fD4m1%2B2iuCgtuJ1cV%2ByGdbSTkA%3D&reserved=0> (pending merge).
