### ISSUE TITLE
Home Page Blog Still Only Pulling One Post

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#577]
The issue is back again. Only one blog post being pulled. 
https://www.themeetinghouse.com/

**Comment by JonEsparaz** [comment]
Looks like someone accidently changed the limit field in this commit https://github.com/themeetinghouse/web/commit/1143235347279ed3654d3816813f2b3e7b8ab273.

https://github.com/themeetinghouse/web/blob/a43d9103658e3c24534ce3f78a7f21cf39660a6c/public/static/content/homepage.json#L140-L148

Probably easiest if you make the change @deeinstereo and run syncProd.
