### ISSUE TITLE
Staff UI change

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#579]
@deeinstereo our parish team module looks like this:
<img width="1425" alt="Screen Shot 2020-12-01 at 4 19 09 PM" src="https://user-images.githubusercontent.com/48295718/100798046-0f31f800-33f1-11eb-9802-148a25bc3c2b.png">

But when a parish doesn't have many people, it looks like this:
<img width="1430" alt="Screen Shot 2020-12-01 at 4 18 54 PM" src="https://user-images.githubusercontent.com/48295718/100798088-207b0480-33f1-11eb-8248-75ae01afc080.png">

That's a lot of white space. Should we make it so that the white space is dynamic to the number of rows that exist?

**Comment by deeinstereo** [comment]
Yeah that sucks. Dynamic white space please. Make it look good!

**Comment by GeorgeBellTMH** [comment]
Do we also want a link to show staffs teaching on the web?

**Comment by deeinstereo** [comment]
This might be an interesting feature over on the teaching page.

**Comment by lucastbelem** [comment]
> This might be an interesting feature over on the teaching page. 

What do you mean by this @deeinstereo? Are you thinking of a teacher's carousel like in the app or display the speaker in a teaching that is clickable to a page with all of that speaker's videos?

**Comment by deeinstereo** [comment]
@lucastbelem As in, can you click on a pastor from their parish page and see their teaching. But also, what if we added a carousel to the teaching page that created the ability for people to find teaching by teacher?
