### ISSUE TITLE
Speakers on teaching page

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#585]
Need to discuss:

How to display teachers on teaching page? What design do we use?

**Comment by GeorgeBellTMH** [comment]
I think we can start with a link from the staff page like we have on the app...but if we want to add a teachers list maybe we do it similar to the staff list, but with just the images and name...unless we want to include glam-bot shots? https://www.youtube.com/watch?v=ctujwZ1UtWs&feature=emb_title

**Comment by lucastbelem** [comment]
Closing this...one of our learnings from this past year has been to decrease the spotlighting on any one speaker, so we will not be adding speakers to the website for the foreseeable future.
