### ISSUE TITLE
Christmas map module

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#586]
* [x] Remove postal code box and "current location" button
* [x] Remove map
* [x] Remove click-ability of parish name
* [x] Remove address
* [x] Remove extra white space that is created by the removal of the address
* [x] Remove contact pastor
* [x] "Visit Page" links to /live

**Comment by itbel** [comment]
The "Add to Calendar" feature is broken in `SundayMorningItem.tsx.` I suspect could be due to package updates. 
If you add `optionsOpen={true}` the dropdown and package functionality still works, but clicking on the Add to Calendar label does not trigger the menu to open.
@GeorgeBellTMH

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @JonEsparaz do either of you know what this could be? We're hoping to get the Christmas page live for promo tomorrow and the add to calendar thing is going to be a big part of that.

**Comment by JonEsparaz** [comment]
I would agree with @itbel - likely package updates since the component works at 22eb677d88de002449f43ef8f210c134e36851c6, which is before several packages were bumped.

**Comment by JonEsparaz** [comment]
Rolling react and react-dom to back 16.14.0 appears to resolve the issue @GeorgeBellTMH.

The Add To Calendar component is slated to be replaced anyways (https://github.com/themeetinghouse/web/issues/330), so I would just roll react and react-dom temporarily, then find a suitable replacement for the calendar component.

**Comment by itbel** [comment]
Thanks @JonEsparaz. It is working now.

**Comment by GeorgeBellTMH** [comment]
It's live...
