### ISSUE TITLE
A different youtube channel

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#587]
How complex is the process to pull videos to /admin from a different youtube channel?

For context, we're planning to host kids and youth videos in a curriculum-specific youtube channel. Is it possible to pull from 2 youtube channels? 

In the meantime, we can just continue to upload to both channels and just unlist from the TMH channel.

**Comment by GeorgeBellTMH** [comment]
Some development work needed...we need ability to import from separate channels and remember where they came from...

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH why do we need to remember where the videos came from? 

As I see it, we just run the `ImportYoutube` class twice (once per channel) during ingest, then the videos are uniquely identified by the ID from YouTube (which is the same as the ID in DynamoDB) so all mutations will just work regardless of the channel of origin.

Seems like we just need to duplicate the resolvers or pass the `channelId` as a parameter, right?

**Comment by GeorgeBellTMH** [comment]
Yah so:

- Passing the channelId
- mark all existing videos as coming from our channel via new channel field
- Move existing key in vtl into secret
- We also may need to handle different secrets for each channel (not sure until we try)
- Update any admin that re-pulls data to be smart about how to pull
- Upgrade other channels api limits
- Potentially a way to add playlists to the ignore list

**Comment by lucastbelem** [comment]
Adding videos from other channels to our channel's playlists imports them to the website.
