### ISSUE TITLE
Missing Teacher Photos

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#591]
We need to add the missing teacher photos into the app (they go in the /public/static/photos/teachers folder).... 

Also Danielle's photo is missing on the Staff page.

**Comment by GeorgeBellTMH** [comment]
Also, hide any speakers you don't want....

Let us know when this is good enough to go live...

**Comment by GeorgeBellTMH** [comment]
How are we doing on this @lucastbelem ?

**Comment by lucastbelem** [comment]
@laurengermain could you see if this is done? 

What this refers to is the speaker/teacher carousel in the app. If it's not done, we need to source images for those missing pictures.
