### ISSUE TITLE
"Did it Really Happen?" Series doesn't pull

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#592]
Go to themetinghouse.com/christmas, scroll down to the playlist called "Christmas Series Archive" and click on "Did it Really Happen?". It doesn't load for some reason. It's the only series with this problem.

**Comment by georgevicbell** [comment]
I suspect it might be the ? causing problems...


George Bell
Cell: 416-802-6697

________________________________

**Comment by deeinstereo** [comment]
It's still not working even if I try to access it from the teaching archive page. Any chance you can look into this @lucastbelem ?

**Comment by lucastbelem** [comment]
@deeinstereo @GeorgeBellTMH it's working now - it's the ? that's the problem. I'll have to fix the other series with this problem.
