### ISSUE TITLE
Image names glitch

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#597]
When we update images on the website, if we keep the same name, the image does not update. Can we fix this so we can replace images with the same name?

I.e. staff member wants a new photo. To make this work, we need to change the person's name.

**Comment by georgevicbell** [comment]
It should update eventually. The cache lasts for a few days I think.

Sent from my iPhone

On Dec 15, 2020, at 4:14 PM, Lucas Belem <notifications@github.com> wrote:

﻿

When we update images on the website, if we keep the same name, the image does not update. Can we fix this so we can replace images with the same name?

I.e. staff member wants a new photo. To make this work, we need to change the person's name.

**Comment by GeorgeBellTMH** [comment]
I believe this should now work...I have set it to delete all images every 10 days...another secret may be to do the following...delete the image, syncProd...then add the new image and syncProd again...
