### ISSUE TITLE
Find a Home Church Module Update

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#598]
Can we make the location popups in the map for find a home church and find a location match the design found here: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=773%3A10839

Basically, the colours should be inverted - black background and white text.

@deeinstereo assuming this is still wanted?

**Comment by deeinstereo** [comment]
@lucastbelem yup!
