### ISSUE TITLE
Yellow Livestream Bar Needs to Be Persistent on All Pages

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#603]
Right now it's only visible on the home page. 

When active, every single page on the website needs to have this at the very top (like we did with the old live button).

**Comment by GeorgeBellTMH** [comment]
You need to add “showLive":”true” to whatever pages you want it on...

 "pageConfig": {
      "movingMenu": true,
      "showLogoText": true,
      "logoColor": "black",
      "showSearch": true,
      "showFooter": true,
      "showMenu": true,
      "showLive": true,
      "weatherAlert": false
    },

**Comment by GeorgeBellTMH** [comment]
Just don't put it on the livestream page ;-)

**Comment by deeinstereo** [comment]
Got it! Thanks! 
@GeorgeBellTMH so would I need to do this to every single page? There's no way just to set this across all pages automatically?

**Comment by GeorgeBellTMH** [comment]
Give me a sec, I will do a search replace and put it on all of them...

**Comment by itbel** [comment]
@GeorgeBellTMH 
I did not account for this. 
There is an if statement on HomeMenu.tsx that only fetches live events when on "/". (Line 91) That will need to be removed. More changes may be necessary in order to account for the showLive field.

**Comment by GeorgeBellTMH** [comment]
Yup, I see it...delivering now (but not publishing)

**Comment by deeinstereo** [comment]
I gotta upload some blog images. Can you hold off publishing until like 12/12:30?

**Comment by GeorgeBellTMH** [comment]
Everyone take a look on local now…I will publish it after the service is over and we can verify it works during the afterparty...

**Comment by deeinstereo** [comment]
Also, I'm on the fence about the triangle...

**Comment by GeorgeBellTMH** [comment]
@deeinstereo just don't pull...

**Comment by GeorgeBellTMH** [comment]
We could do a trapezoid?

**Comment by GeorgeBellTMH** [comment]
Livebar doesn't work so good on mobile screens with an X

**Comment by deeinstereo** [comment]
hmmm? @GeorgeBellTMH

**Comment by deeinstereo** [comment]
@GeorgeBellTMH okay i added the pictures but it won't let me push "Can't push refs to remote, try running pull first to integrate your changes."

**Comment by GeorgeBellTMH** [comment]
yup, go ahead and pull

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can we close this?
