### ISSUE TITLE
Shorter blog URLs

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#609]
@deeinstereo mentioned this briefly.

Two solutions:
- Keep the current infrastructure and implement a link shortener 
- Use [nanoid](https://github.com/ai/nanoid) (or a similar library) to get short IDs for blogs

**Comment by GeorgeBellTMH** [comment]
I think we can just let the user set the ID of the blog table to be a url encoded field...so then they can pick a post/xxxx name at blog creation.

**Comment by GeorgeBellTMH** [comment]
I'm also fine if we want to alias tmh.com/b/xxx to tmh.com/post/xxx (but I think /post/xxx is probably fine...)

I think it's better to have a url that relates to the blog post than a random id...

**Comment by GeorgeBellTMH** [comment]
(note url length is also a problem for videos/series)

**Comment by deeinstereo** [comment]
I'm down for whatever @GeorgeBellTMH and @JonEsparaz think is best. My priorities are keeping SEO top of mind, making sure we include keywords, and just keeping the links shorter so that they look nice when shared. 

I'll go with whatever you think is best.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH I think your idea makes sense, but we should enforce some kind of formatting rules so the URLs are consistent.

Most blogs I've seen do all lowercase with hyphens between each word.

**Comment by georgevicbell** [comment]
That works for me
