### ISSUE TITLE
Home Church category pills

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#611]
As per design here: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=773%3A11459

Can we please add "Family Friendly" and "Young Adults" home church label pills? I talked to Roger, and it doesn't look like the data is consistently added to an attribute field in Fellowship One, but it is consistently added to the Home Church name. For example, "Sheridan Young Adult Home Church". 

Can we use the name to create the pills? @GeorgeBellTMH any thoughts on this?

**Comment by lucastbelem** [comment]
@itbel let's plan to use the name to create the pills unless @GeorgeBellTMH has concerns.

**Comment by lucastbelem** [comment]
@itbel I'm guessing it's because of exact wording, but you'll see in the screenshot below that this Young Adult home church did not generate a pill. 

<img width="1433" alt="Screen Shot 2021-01-14 at 9 24 59 PM" src="https://user-images.githubusercontent.com/48295718/104673090-09e1f180-56af-11eb-9b20-525fb9f5489b.png">

**Comment by itbel** [comment]
I accidentally deleted the condition to also insert the pill for Young Adult. I'll be adding this again soon.
