### ISSUE TITLE
Menu Design

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#612]
We need to update the menu on the website to change colour when you scroll over different colour backgrounds. Here is a sample of what we're looking for: https://touchtunesmedia.com/.

To do this, we would also need to adjust every module built that should extend to the edge of the screen, but currently doesn't to accommodate the fact that the menu doesn't change colour.

**Comment by GeorgeBellTMH** [comment]
This one is waiting for detailed design.....

**Comment by JonEsparaz** [comment]
This note in Figma might be what you're looking for: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=719%3A9357

> Menu sidebar would stick to the top of the screen once
> the user reached this point. 
> 
> The color of the menu elements will change to a darker theme
> when the user scrolls onto a darker background.

**Comment by GeorgeBellTMH** [comment]
Ya, no there are more details needed...I talked to Lucas about it...
Some of the questions I have:

1) We need examples of what it will look like at 50% in a white box an 50% in a black box
2) Will there be any problems with accessibility/contrast - can we test our design with people and get some feedback
3) What is the transition (is it a fade, is it just a hard change, where/when does it happen)
4) Is the Text going to be black/white background and white/black background or some shade of grey?
5) Can we fix the footer somehow at the same time?
6) What do we do with left grey boxes?
7) Is the logo going to change as well?
8) When you expand the menu does it impact what state we are in? What happens during that animation
9) What happens in a transition from grey to black, or black to grey (like on the header/footer of the compassion page)

I think most of these questions have some answers, but I think it would be good to mock them up before we do a lot of work on it.

**Comment by lucastbelem** [comment]
Menu scroll should likely stop before the footer.

**Comment by lucastbelem** [comment]
@itbel this is the issue you're solving.
