### ISSUE TITLE
Change to livestream admin - to be confirmed

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#614]
I think the livestream stuff needs to be more customizable for the admin user. Here is what I propose:

StartTime: Yellow banner appears and event appears in the drop down
Event Start Time: Time displayed in drop down for when the event starts;
Join Time: "Join" button changes to clickable and takes user to /live;
End Join Time: Live event disappears from dropdown;
videoStart Time: Time when /live page changes from playing the pre-roll youTube link to the Live youTube link
End Time: Yellow bar disappears

@deeinstereo @GeorgeBellTMH thoughts?

**Comment by GeorgeBellTMH** [comment]
Yup, I would name them:

AdvertisingStartTime - Yellow Bar
ListedStartTime - Shows in Drop down
JoinStartTime - Join Button goes active
VideoStartTime - Video Starts
ExpectedVideoDuration - Potentially used for advertising purposes
JoinEndTime - Join Button Changes to Watch
AdvertisingEndTime - Stops showing in Drop Down

**Comment by GeorgeBellTMH** [comment]
Closing this as I think a lot of it is done already....
