### ISSUE TITLE
Yellow live banner appearance 

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#615]
Pages with baby hero image look a little strange on mobile when the yellow banner is visible.

![image](https://user-images.githubusercontent.com/48423418/103106293-3c458500-4602-11eb-9d70-063ddd8b70e1.png)

![image](https://user-images.githubusercontent.com/48423418/103106295-3ea7df00-4602-11eb-9761-575720898eda.png)

**Comment by deeinstereo** [comment]
Could we close that white gap on mobile so that there's no space between the yellow bar and the top of the grey box with the text?

**Comment by JonEsparaz** [comment]
Another weird case (/give):

![image](https://user-images.githubusercontent.com/48423418/105635893-830de100-5e33-11eb-8f3c-c1d87abc996d.png)

@lucastbelem it seems someone needs to go through every screen to find all these edge cases, then they can all be fixed in one go.

**Comment by deeinstereo** [comment]
@JonEsparaz that's true. @lucastbelem help? I would say with pages like the give one I'd scrap the yellow bar altogether. At that point we should remove all distractions.

**Comment by lucastbelem** [comment]
@itbel can you pls take a look?

**Comment by lucastbelem** [comment]
@itbel
