### ISSUE TITLE
New way of downloading notes PDF? 🗒️

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#628]
It seems we're doing double the work now. Olivia has to enter all the notes in via admin, then create and upload a separate PDF. Is there a way that we could just take the online notes that are made, and automatically save those as a PDF when someone clicks to download? I guess I'm looking for something that would automatically generate a PDF without us having to make one. 
Thoughts?

**Comment by JonEsparaz** [comment]
I think we've discussed with idea previously. Yes, we can build an HTML template and inject the content via Lambda. We would generate the PDF using Puppeteer (or something similar), file is saved to S3.

Formatting will be the biggest issue. Primary concerns:
- Ensuring that notes fit on one page and questions fit on one page (a character limit might not work since line breaks and images use an unknown amount of vertical space)
- Elegant line breaks (for example, a numbered list might get split across the two columns)

Definitely doable, but the PDF might not look as pretty as it does now.

**Comment by JonEsparaz** [comment]
Actually I made something, and this would take legit a couple hours to implement.

The page would be vertical obviously, but how's this? [test.pdf](https://github.com/themeetinghouse/web/files/5783249/test.pdf)

**Comment by JonEsparaz** [comment]
@deeinstereo cleaned up version: [Notes PDF](https://github.com/themeetinghouse/web/files/5783383/bruh.pdf)

Quick, easy and relatively nice looking. We can add more flare/style to the HTML if desired. Thoughts?

**Comment by deeinstereo** [comment]
@JonEsparaz wow, that is impressive! Wow. Yeah I'd love to stylize it a little bit more to match the design on the online notes a little closer. Lemme look at this tomorrow and get back to you. But wow. This is really great!

**Comment by deeinstereo** [comment]
@JonEsparaz a few functions that I'm looking for with the PDF version:

- Can we copy more of the original styling for the notes? Especially the headers of each section.
- Can we drop the title under the header image?
- I'll make another post about this, but would it be possible to create some sort of semi-permanent footer that includes the Q&Eh info and pushes people to download the app to get the full experience? 

That's it for now! If this doesn't take long and we can make it work then this simplified PDF version will save us LOTS of time!

**Comment by JonEsparaz** [comment]
> - Can we copy more of the original styling for the notes? Especially the headers of each section.

Yes.

> - Can we drop the title under the header image?

By drop do you mean add or remove? And we're talking about the episode title, right?

**Comment by deeinstereo** [comment]
@JonEsparaz move under the graphic. So the hierarchy should be header, title, then content of the notes. Let me know about that little app promo footer

**Comment by JonEsparaz** [comment]
Seems simple enough. Would it be at the bottom of every page?

**Comment by deeinstereo** [comment]
@JonEsparaz it would be at the bottom of /notes, but function differently than the normal footer that already exists on the bottom of every page.

**Comment by JonEsparaz** [comment]
I see. I'll need some direction with design, but 100% doable.

Another idea is websites (e.g. Reddit) have a pop up dialogue that says "it's better in the app, download today". Not sure if this is a good direction though - could look a little spammy.

**Comment by deeinstereo** [comment]
Oh! I like that a lot! I'd rather do that, just on /notes and just promoting the app. Can we get that going if I work on getting you the UI design?

**Comment by JonEsparaz** [comment]
Yup, we should be able to get that working. 

I think it makes the most sense if the dialogue only appears on mobile (which is most of web traffic anyways).

**Comment by JonEsparaz** [comment]
[notes-final-draft-template.pdf](https://github.com/themeetinghouse/web/files/5788922/notes-final-draft-template.pdf)
@deeinstereo looking good^^^

Like I mentioned earlier, the page breaks are a little awkward (e.g. the final heading and its content get separated). If desired, a hacky solution would be to temporarily add some extra white space above that heading generate the PDF, then remove the extra white space so it doesn't appear on the website and app.

**Comment by deeinstereo** [comment]
@JonEsparaz Yeah I'm open to what you think is best. I don't think will ever be as good as the app so that's where I want to put all the focus. Any chance we can get it to generate the graphik font?

**Comment by JonEsparaz** [comment]
Hmmm, I'll give that a 70% sure probably. I've written most of the code already, so I can get this working for next Sunday (Jan 17), then we can try playing around with the fonts.

**Comment by deeinstereo** [comment]
Sounds good!

**Comment by JonEsparaz** [comment]
I did a quick test and got the Graphik font face working. 

I had to use the `.oft` files, which I got off the Google Drive folder. The license wasn't present - @GeorgeBellTMH @deeinstereo @lucastbelem can one of you confirm that the following usage is permitted?

- Converting the `.oft` files to base64 string
- Saving the base64 string representation of the font face in a stylesheet
- Loading the stylesheet in a Lambda function (this is technically installing the font on a computer)
- Using the font in a PDF

**Comment by deeinstereo** [comment]
We did pay for the web license for the font, but I have no idea how or where we could confirm this. But I do know we paid.

**Comment by deeinstereo** [comment]
Hey @JonEsparaz just wanted to check in, is there a chance we can try it for this Sunday?

**Comment by JonEsparaz** [comment]
@deeinstereo depends on when #636 gets merged and deployed. I still need to make sure the code works in the cloud.

**Comment by lucastbelem** [comment]
@deeinstereo @JonEsparaz George is really focused on solving things on JC so we can launch in the next few days. Might be good to plan to deliver for the 24th instead, friends. One more week of manual pdfs - sorry!

**Comment by JonEsparaz** [comment]
@lucastbelem since we have an extra week, can you look into the previously mentioned font licensing concern?

This way we can have the Graphik font right away (if allowed).
