### ISSUE TITLE
Proposal: consider migrating to Next.js

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#639]
AWS Amplify added support for Next.js a few months ago and I think it's worth a discussion.

Next.js could solve several open issues and provide performance improvements - an area that continues to be somewhat of an issue. This move would require some refactoring to the React code - mostly changes to routing, data fetching and CSS imports. I'd estimate this undertaking would require 2-3 days with proper planning, but would save time on other issues.

Potential benefits:
- Improved first contentful paint via hybrid server-side rendering.
- Improved SEO performance (could fix #388, #389; removes the need for the social bot Lambda).
- [Automatic image optimization](https://nextjs.org/docs/basic-features/image-optimization) (could fix #561; potentially removes the need for the image resizing Lambda).

Potential drawback: future cost increase. At the moment, the website gets ~3,000 page visits per day (less than 100,000 per month) and we get 1,000,000 free Lambda@Edge invocations per month, so this would only be a problem if traffic increased by a factor of 10.

Potential issue: redirects are a little tricky.

**Comment by JonEsparaz** [comment]
Another potential benefit: reduced API calls. 

For example: blogs could be statically generated since they are virtually unchanging. Video player pages only change once per week too. Even if we regenerated these semi-static pages once per day, there would be significantly less client-side API calls.

**Comment by georgevicbell** [comment]
Redirects were why I didn’t go this way initially.

If we can figure it out, I’m open to it...probably need to verify it works in another environment.

Note: I think a lot of the reason we are having bad performance is more related to optimizing image sizes/formats/compression and setting up local caching...or doing stuff like preloading/prioritizing the hero images..I think there are bigger wins to be had there at the moment.

Also relying on more dynamic library loads and potentially caching some of the API calls would likely help.

There are likely some things we could do with service workers to ensure things are ready to go right off the bat.

Sent from my iPhone

On Jan 11, 2021, at 10:03 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

AWS Amplify added support for Next.js a few months ago and I think it's worth a discussion.

Next.js could solve several open issues and provide performance improvements - an area that continues to be somewhat of an issue. This move would require some refactoring to the React code - mostly changes to routing, data fetching and CSS imports. I'd estimate this undertaking would require 2-3 days with proper planning, but would save time on other issues.

Potential benefits:

  *   Improved first contentful paint via hybrid server-side rendering.
  *   Improved SEO performance (could fix #388<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fissues%2F388&data=04%7C01%7C%7C788fa378853e4a89e55508d8b6a69a0b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637460173955191721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K3ce5dRUifxjTrc7uP5VFDyG%2FkRUpGpmEOVwCyzY8s0%3D&reserved=0>, #389<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fissues%2F389&data=04%7C01%7C%7C788fa378853e4a89e55508d8b6a69a0b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637460173955191721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Nee0hN8tCzGvWMQpj3vmPYrFRpA3b6pTzUAsMbV8kT0%3D&reserved=0>; removes the need for the social bot Lambda).
  *   Automatic image optimization<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnextjs.org%2Fdocs%2Fbasic-features%2Fimage-optimization&data=04%7C01%7C%7C788fa378853e4a89e55508d8b6a69a0b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637460173955201672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ehbOWA8aHJMNFfTUALjB6njd%2F89pIoxq3d0asjo1X08%3D&reserved=0> (could fix #561<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fissues%2F561&data=04%7C01%7C%7C788fa378853e4a89e55508d8b6a69a0b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637460173955201672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OgMbaj7oGYtg83x%2B7aR0olXIIrNIuOFdVMoz9%2FNu75w%3D&reserved=0>; potentially removes the need for the image resizing Lambda).

Potential drawback: future cost increase. At the moment, the website gets ~3,000 page visits per day (less than 100,000 per month) and we get 1,000,000 free Lambda@Edge invocations per month, so this would only be a problem if traffic increased by a factor of 10.

Potential issue: redirects are a little tricky.

**Comment by georgevicbell** [comment]
For caching I think all we need to do is go through s3 and set the Cache-Control on each files metadata. I don’t know if there is a way to do this from amplify or if we have to do it after we deploy with a script or something. Cloudfront should pick it up and pass it on to the client.

Sent from my iPhone

On Jan 11, 2021, at 10:18 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

Another potential benefit: reduced API calls.

For example: blogs could be statically generated since they are virtually unchanging. Video player pages only change once per week too. Even if we regenerated these semi-static pages once per day, there would be significantly less client-side API calls.

**Comment by JonEsparaz** [comment]
> Redirects were why I didn’t go this way initially.

Hypothetically, data could be entered on admin, and when the user saves, we can update `next.config.js` with the current [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewriting-to-an-external-url) in a Lambda, commit to GitHub via the Lambda, then automatically deploy via GitHub Actions.
