### ISSUE TITLE
🔀 New Video Playlist Function 🔀

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#648]
I want to be able to create new video playlists, with any combination of existing videos, regardless of how many other playlists those videos already belong to. These playlists should be able to be embedded on any page of the website as a video carousel, with a limit of "x" videos, before user has to click to view all videos. This is different that our current ability to add videos to a custom teaching playlist, since these playlists exists within a playlist of playlists carousel and cannot be added to unique video carousels. 

One video should be able to live in multiple custom playlists, and e should be able to create and edit these playlist without impacting other existing playlists. 

Example: A Teaching Highlight from a Sermon, can exist in this many custom playlists:

1. The Series Playlist
1. A custom teaching playlist of videos on specific topic
1. A custom carousel playlist of our favourite videos
1. A custom carousel playlist of videos related to a relevant topic
1. A custom carousel playlist of suggested videos for spiritually curious people

To-do:

* [x] many-to-many connections between videos and custom playlists
* [x] video carousel for a single custom playlist
* [ ] video limit + click to view all feature (modified version of the existing video archive)

**Comment by JonEsparaz** [comment]
#702 partially resolves this. Also, you have always been able to add a video to multiple custom playlists, so that's done too.

Remaining task would be the limit + click to view all feature (requires modifying the video archive component).

**Comment by lucastbelem** [comment]
If I'm understanding the task, I believe we actually completed it.
