### ISSUE TITLE
App Promo Dialogue on Notes Page

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#651]
Originates from https://github.com/themeetinghouse/web/issues/628.

Summarizing quotes:
> Another idea is websites (e.g. Reddit) have a pop up dialogue that says "it's better in the app, download today". Not sure if this is a good direction though - could look a little spammy.

> Oh! I like that a lot! I'd rather do that, just on /notes and just promoting the app. Can we get that going if I work on getting you the UI design?

The deliverable is basically a Reddit-style app promo dialogue on the notes page (mobile only). Pending UI design.

**Comment by JonEsparaz** [comment]
@deeinstereo assigned you for the design.

Also, here's the Reddit dialogue for reference:

![image](https://user-images.githubusercontent.com/48423418/105131408-dc35e780-5ab6-11eb-8dd3-0a023cab2cd4.png)

**Comment by deeinstereo** [comment]
@JonEsparaz thank you!
@georgevicbell can we get a designer on this (Jen or Mateus) in the next 2-3 weeks? We can set it up on figma and I can walk them through the vision. @GeorgeBellTMH I hope that we have the dev to support this? Or are we asking too much?

**Comment by JonEsparaz** [comment]
@deeinstereo I'll have time to look at this next week. Did we ever do a mockup? If not, can I just throw something together and you can provide feedback afterwards?

**Comment by deeinstereo** [comment]
@JonEsparaz yeah sorry, don't have much capacity to design. Can you throw something together? Thanks!
