### ISSUE TITLE
Instagram scraper no longer works

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#657]
The fetch request now hits the Instagram log in screen and JSON data is not returned.

Using the Instagram Graph API seems like the best option now. The long-lived tokens can be refreshed via scheduled Lambda.

**Comment by JonEsparaz** [comment]
Temporarily removing the Instagram components might be a good idea. This is what things look like at the moment:

![image](https://user-images.githubusercontent.com/48423418/105754366-fab53c00-5f17-11eb-8a15-2e489711873e.png)

**Comment by lucastbelem** [comment]
@JonEsparaz what page did you find this on? I want to remove the component until we solve this.

**Comment by JonEsparaz** [comment]
https://www.themeetinghouse.com/toronto-uptown

Probably good to remove the component on all site pages. Ancaster for example:
![image](https://user-images.githubusercontent.com/48423418/106218208-e3d74980-61a4-11eb-9f3c-84a4978290be.png)

**Comment by JonEsparaz** [comment]
The Instagram component on the app's homepage can probably remain. It handles errors more elegantly, so there's just an empty component. Example, Uptown Toronto:

![image](https://user-images.githubusercontent.com/48423418/106218487-5b0cdd80-61a5-11eb-9058-12d38a004d14.png)

**Comment by GeorgeBellTMH** [comment]
Ok! I got this all figured out...there is now an option to add the instagram_basic permissions to service users! So I have done that, and created a getInstaPhotos(instaId:String) in graphql...so it should work similar to fb events...

**Comment by GeorgeBellTMH** [comment]
Ok, I've also updated all the code in web to make use of the new getInstaPhotos method...I will make a ticket and someone can update it on mobile as well...

**Comment by JonEsparaz** [comment]
I'll take care of https://github.com/themeetinghouse/mobile/issues/228 tonight.

@GeorgeBellTMH, @branden-eyk: we can take down the Node.js script running on the Mac server.
