### ISSUE TITLE
FAQ Item Image

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#664]
MOBILE ONLY >> Go to /peacemakers and scroll to the bottom. **_I just pushed it so it may take a few more minutes to sync_**
The content styled as "oneImageBlackRight" shifts the photo way too far down and it clashes with the videos horizontal list and the FAQ. I tried "oneImage" as well but the issue persists. 

Screenshots attached 
![Screen Shot 2021-02-04 at 5 27 47 PM](https://user-images.githubusercontent.com/47831068/106966785-01139700-6714-11eb-9d60-2e9a05de62b4.png)
![Screen Shot 2021-02-04 at 5 24 59 PM](https://user-images.githubusercontent.com/47831068/106966787-01ac2d80-6714-11eb-81f4-1efa72088dd5.png)

**Comment by JonEsparaz** [comment]
Fixed.

FYI this issue shows up in other places (I assume it has been like this for a while).

Example: https://www.themeetinghouse.com/pandemicresponse

**Comment by GeorgeBellTMH** [comment]
Weird stuff is happening...

1. Go to homepage everything is fine
2. go to /peacemakers everything is fine
3. click on tmh logo - homepage is busted at the bottom

**Comment by GeorgeBellTMH** [comment]
I think this is a pre-existing issue though...going to this page messes up tmh.com on the live site...

I'm going to merge the big one first...then this one...then we can tackle whatever that issue is...

**Comment by JonEsparaz** [comment]
> Weird stuff is happening...
> 
> 
> 
> 1. Go to homepage everything is fine
> 
> 2. go to /peacemakers everything is fine
> 
> 3. click on tmh logo - homepage is busted at the bottom

My PR should fix this. It's the style targeting the `secondImg` class, which I removed.

**Comment by GeorgeBellTMH** [comment]
Everything looks good...publishing... @deeinstereo please verify it's all the way you want, it'll be up in 5 minutes...

**Comment by deeinstereo** [comment]
@GeorgeBellTMH thanks so much! Looks better! The only part that is odd is the picture of FAQ. It loads below the FAQ on mobile, but I think it should load above it.

**Comment by JonEsparaz** [comment]
@mmacedom, I see you have a PR open. Are you moving the image like @deeinstereo requested? Or should I do it?

**Comment by JonEsparaz** [comment]
Another issue: the image overlaps with the footer on desktop.

![image](https://user-images.githubusercontent.com/48423418/106987330-3384ba80-673b-11eb-8ee0-c7cd68b0652d.png)

**Comment by mmacedom** [comment]
@JonEsparaz I'm fixed it on mobile and can adjust on desktop as well.

**Comment by mmacedom** [comment]
@JonEsparaz @deeinstereo this has been fixed on desktop and inverted on mobile as requested.

**Comment by deeinstereo** [comment]
@mmacedom @JonEsparaz THANK YOU!!! <3
