### ISSUE TITLE
Users Table, Profiles, Groups, Permissions

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#667]
Create a people tab that does the following:

* [ ] Allows admins to create new people/edit people/delete people with the following fields:
* [ ] First Name, Last Name, Title, Email, Phone Number
* [ ] Allows admins to upload image for these people
* [ ] Allows admins to select a parish for these people (choose from a dropdown)
* [ ] Allows admin to give the following attributes to these people:
* [ ] Speaker, Staff, Coordinator, Blogger, Notes maker, Admin
* [ ] Allows admins to give these users specific admin permission/groups (i.e. blogs, notes)

What happens then:

* [ ] Users with "speaker" attribute are added to the app's speakers' carousel and "all teachers" directory
* [ ] Users who Staff attribute are added to the staff directory on the website and the app. 
* [ ] When the user has a staff attribute and a parish associated with them, they are also added to that parish's team page on the website and the app
* [ ] Users with the coordinator attribute are added to their respective parish pages on the website and the app
* [ ] Users with "Blogger" attribute are added to the "Blog" permission group
* [ ] Users with the "Note Taker" attribute are added to the "Notes" permission group

There may be a couple more requirements, but getting these would help a lot.

@GeorgeBellTMH could you please time tag this? We'll prioritize it at some point soon.

**Comment by lucastbelem** [comment]
Create a people tab that does the following:
- [ ] Allows admins to create new people/edit people/delete people with the following fields:
- First Name
- Last Name
- Title
- Email
- Phone Number
- [ ] Allows admins to upload image for these people (restrict image size to appropriately small size)
- [ ] Allows admins to select a parish for these people (choose from a dropdown)
- [ ] Allows admin to give the following attributes to these people:
- Speaker
- Staff
- Coordinator
- Blogger
- Notes maker
- Admin
- [ ] Allows admins to give these users specific admin permission/groups (i.e. blogs, notes)

What happens then:
- [ ] Users with "speaker" attribute are added to the app's speakers' carousel and "all teachers" directory
- [ ] Users who Staff attribute are added to the staff directory on the website and the app. 
- [ ] When the user has a staff attribute and a parish associated with them, they are also added to that parish's team page on the website and the app
- [ ] Users with the coordinator attribute are added to their respective parish pages on the website and the app
- [ ] Users with "Blogger" attribute are added to the "Blog" permission group
- [ ] Users with the "Note Taker" attribute are added to the "Notes" permission group

There may be a couple more requirements, but getting these would help a lot.

@GeorgeBellTMH could you please time tag this? We'll prioritize it at some point soon.

**Comment by GeorgeBellTMH** [comment]
I'd like to actually change this up a bit...

**Comment by GeorgeBellTMH** [comment]
I think a better way to do this is as follows:

1. Create a users table in dynamo with a bunch of the above fields...
2. Create a cognito link to the users table - such that a cognito user is linked to the dynamo user, but the dynamo user can exist without a cognito user
3. When a user logs into cognito for the first time, we link them up based on their email address if it exists
4. User can then edit a subset of fields
5. Admins can edit whether users are staff (probably via a staff group) and/or volunteers (via multiple groups - overseers etc.)

**Comment by GeorgeBellTMH** [comment]
Note that this needs to work in web and app...but primarily in the app, with the web interface primarily for admin (groups and updating users before they exist)

**Comment by GeorgeBellTMH** [comment]
Closing this, as most of it is done under the payments piece...
