### ISSUE TITLE
Peacemakers pie graph

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#668]
The pie graph has a small gap and isn't a perfect circle (you can see the outer edge is flat in a couple places).

Will this component be used in future years? If so, I think it is worth re-implementing with SVG or HTML5 canvas.

There's low-weight packages specifically for making graphs that use SVG/canvas. Or it's pretty easy to implement from scratch.

![image](https://user-images.githubusercontent.com/48423418/107065607-f821d480-67aa-11eb-8ac5-b56df4ebb18a.png)

**Comment by georgevicbell** [comment]
Ya if there is a better solution let’s do it. This one was made in a rush.

I think actually there was a better one in the course menu on Jesus collective.

Sent from my iPhone

On Feb 5, 2021, at 12:14 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

The pie graph has a small gap and isn't a perfect circle (you can see the outer edge is flat in a couple places).

Will this component be used in future years? If so, I think it is worth re-implementing with SVG or HTML5 canvas.

There's low-weight packages that specifically for making graphs that use SVG/canvas. Or it's pretty easy to implement from scratch,

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48423418%2F107065607-f821d480-67aa-11eb-8ac5-b56df4ebb18a.png&data=04%7C01%7C%7C085d4442cbcb4f3ec89508d8c9f97f22%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637481420695973746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dwa61YFiNtzEucZovB9OE0UbA2JOJ9BmQ%2Bz5jm6TGPg%3D&reserved=0>
