### ISSUE TITLE
Refactor stylesheets

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#670]
In my opinion, the following issues should be addressed:

* [ ] The float property and absolute positioning are used where flexbox is likely more appropriate.
* [ ] There's lots of repeated styles in different stylesheets, so [mixins](https://sass-lang.com/documentation/at-rules/mixin) could be useful.
* [ ] If styles appear within the scope of every media query, they can be moved to the top of the stylesheet.
* [ ] The entire website uses Graphik Web. Instead of defining the font everywhere, this could work:

```css
body {
   font-family: Graphik Web;
}
```

* [ ] As observed in https://github.com/themeetinghouse/web/issues/664, there might be styles causing conflicts. In general, if a selector appears in `foo.scss`, but not in `foo.tsx`, it should be removed (or add a comment explaining what it does).

Rationale:

* Improved readability/maintainability
* Smaller files
* Improved reliability

**Comment by GeorgeBellTMH** [comment]
I think we tried that Graphic Web in body bit and it was being overridden in some of the themes, and was causing headaches...that may be resolved with some of the other work here...

**Comment by lucastbelem** [comment]
@RAidanM
