### ISSUE TITLE
Image resizer not handling PNGs

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#673]
## Current issue
The resizer Lambda seemingly does not handle PNGs properly (JPGs work fine). Potentially stopped work after this commit: https://github.com/themeetinghouse/web/commit/be6c179f94590b9337b5059719c8f3746df02b3e

## Original issue (fixed)
App and website are affected, see: https://www.themeetinghouse.com/teaching-curated

![image](https://user-images.githubusercontent.com/48423418/107132724-74054500-68af-11eb-926e-d503de0f1920.png)

Possibly because the images are PNG? (Everything else is JPG).

**Comment by GeorgeBellTMH** [comment]
Did this ever work? It looks like this is all stuff added today? I looked on the image logs and the png files do fail...but it's weird because it's more like the s3 getobjecthead (checking if the image exists in s3) fails with some crazy internal error...I have updated the version of aws-sdk and it persists....suggest we switch to jpg....

**Comment by JonEsparaz** [comment]
> Did this ever work? It looks like this is all stuff added today?

Yes, definitely used to work. 

I believe the PNGs have existed since this commit 5 months ago: https://github.com/themeetinghouse/web/commit/69d150acd79d85be3b2d41169a56139e743428db

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH is this something you are planning on investigating/fixing? 

If not, PNGs should be replaced with JPGs throughout the website. Example of PNG failure on /locations:
![image](https://user-images.githubusercontent.com/48423418/112035916-6c73c580-8b16-11eb-91c6-25aeaf12e52c.png)

**Comment by GeorgeBellTMH** [comment]
Thank you for pointing this out…I was hoping to figure it out at some point and thought it was low priority, but now I remember we added more scaled images on other objects…so more pngs...

I will take a look at this before Sunday.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH was this addressed?

**Comment by lucastbelem** [comment]
Pls investigate to ensure not happening.
