### ISSUE TITLE
Add TikTok link to Footer

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#682]
@deeinstereo thoughts?

**Comment by deeinstereo** [comment]
@GeorgeBellTMH yeah! Why not? It's small but we have to do something to grow it! Any chance you can also add our discord?

**Comment by GeorgeBellTMH** [comment]
We have a discord? Fun! Send me the info!

**Comment by deeinstereo** [comment]
Yeah TMH Waterloo is basically running it as one of their Go Challenge initiatives. I'll email you to get info.

**Comment by GeorgeBellTMH** [comment]
Publishing now.
