### ISSUE TITLE
Schedule releases

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#685]
It would be great to have a way to make updates ahead of time and then schedule a release for a later date/time. 

What does that look like?

**Comment by GeorgeBellTMH** [comment]
What kind of updates? Admin updates we would have to write into the db (blogs, videos etc.). 

For content updates we could write a lambda that renamed files...so you could create a file:

community.json.[timestamp] that would overwrite community.json when the timestamp is hit. That would be a relatively quick way to do it.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH we'd probably want to do both eventually, but if we could start with the easy one, I'm down.

Use case: peacemakers totals need to be updated, but Matt doesn't want them updated until Monday am. Sometimes we need to update stuff over the weekend, but people are technically off.

**Comment by GeorgeBellTMH** [comment]
Good news! This is now possible...the format is:

content: [
....,
{
        "type": "timer",
        "after": "2021-09-09",
        "contentNow": [],
        "contentFuture": []
,...
]

**Comment by GeorgeBellTMH** [comment]
Basically any of the components that are in contentNow will show up until "after" is hit...at which point contentFuture will show up...

you can have any, or all of the content on a page in the timer...

**Comment by GeorgeBellTMH** [comment]
cc: @nadamico @laurengermain @CarrissaReffell may make some of your tasks a bit less time dependent...

**Comment by GeorgeBellTMH** [comment]
Note: you can test this by changing your clock on your local machine...ideally we remove these after they have switched over unless they will be reused...

**Comment by lucastbelem** [comment]
@laurengermain
