### ISSUE TITLE
Instagram styling and data filtering

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#689]
After https://github.com/themeetinghouse/web/commit/be6c179f94590b9337b5059719c8f3746df02b3e, the thumbnails are not strictly square, so some images are getting stretched vertically.

Also, some of the results are videos, not images, which need to be filtered out as the thumbnail is `.mp4` (example: bottom left item in the screen shot).

![image](https://user-images.githubusercontent.com/48423418/109706973-9bc29280-7b67-11eb-980a-888a725db53e.png)

**Comment by JonEsparaz** [comment]
When this is fixed, using media queries and relative units in the `.scss` file instead of the inline styles would be better IMO.

**Comment by deeinstereo** [comment]
I was just about to add this one! Some of our instagram posts are 4:5, but should be cropped down to 1:1 when pulled to the parish sites and app home feeds

**Comment by deeinstereo** [comment]
@lucastbelem can this be moved up on the priority list?
