### ISSUE TITLE
Fade in images in teaching

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#691]
Teaching pages could probably feel a bit nicer if the mini-hero images faded in, and if we animated the lists (not sure what the best animation would be)...

**Comment by GeorgeBellTMH** [comment]
The fade can be copied from the existing fade on the main hero....

**Comment by lucastbelem** [comment]
@itbel you worked on this right? Just didn't finish?

**Comment by itbel** [comment]
I think so. I'll have a look.
