### ISSUE TITLE
Scaling issue on homepage

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#693]
When scaling in Safari on homepage, there is a zone of 20-30 pixels just after the switch from desktop->mobile where the horizontal scroll occurs...it looks like an issue with the arrows in the teaching section...likely the media query use different numbers...

**Comment by JonEsparaz** [comment]
FYI, on Windows, there's horizontal scrolling on pretty much the entire website, regardless of window width. 

(Note the horizontal scroll bar at the bottom of the screenshots).

## Home
![image](https://user-images.githubusercontent.com/48423418/117554071-56b55380-b023-11eb-9d62-e576027202b9.png)

## Teaching
![image](https://user-images.githubusercontent.com/48423418/117554077-62087f00-b023-11eb-920f-b9b3f7cfb4d3.png)

## Blog
![image](https://user-images.githubusercontent.com/48423418/117554091-6df44100-b023-11eb-95ca-fb7273f557ad.png)

**Comment by JonEsparaz** [comment]
> FYI, on Windows, there's horizontal scrolling on pretty much the entire website, regardless of window width.

This was supposedly fixed (per discussion in https://github.com/themeetinghouse/web/issues/486), but seems like it wasn't.

**Comment by GeorgeBellTMH** [comment]
Hmmm...interesting...any idea which component is causing it? I don't have access to windows...might try installing the Mac IE and see if I can replicate....

**Comment by lucastbelem** [comment]
@itbel not for now, but there is a recommendation here from Jon on what could solve this.

**Comment by GeorgeBellTMH** [comment]
Done.
