### ISSUE TITLE
Update Livestream Button on Parish Pages

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#695]
Hey, time to update this one—it's been too long. Any chance we can do the following:

* [x] Monday-Sunday 12:01 am : Add to Calendar button appears (stylized as it was before) and gives you the chance to add a reminder for the Sunday livestream to your calendar for Sunday at 10:00am ET with the link to themeetinghouse.com/live
* [x] Sunday 12:02am : that button turns into a Watch Live button (styled the same as calendar) which opens /live
* [ ] Just for Easter: can we also find a way to add the Good Friday date + time in the calendar (it's unique for some parishes)
* [x] Just for Good Friday: can the Watch Live button link directly to the parish Good Friday link?

Please let me know if any of these are possible. If none are, then can we at least update the Livestream button and stylize it properly.

**Comment by deeinstereo** [comment]
@CarrissaReffell tagging you so you know what I'm trying to make happen for GF

**Comment by lucastbelem** [comment]
@deeinstereo text changes seem to be done. 1 and 2 are clear, but number 3 is a bit foggy for me. Why would we add a good Friday date and time on Easter Sunday?

**Comment by lucastbelem** [comment]
@CarrissaReffell can you please send @itbel the Good Friday times and links?

**Comment by CarrissaReffell** [comment]
@itbel Attached are the Good Friday links. We are currently missing links for three places. TODT and TOHP don't need links in their add-to-calendars for Good Friday but I will try to get you the Hamilton Mountain link asap. 

Links: https://docs.google.com/spreadsheets/d/1jNGMx0jIGAseJr3WU7kKC_CCa0ByIBM03e3DAM4xl_4/edit#gid=0

**Comment by itbel** [comment]
With the current implementation, it is not possible to add multiple events with a single button click. Another button would be required.
Clicking on `Add to calendar` with the implementation in PR #715 will only add Sunday to the calendar.

**Comment by GeorgeBellTMH** [comment]
@lucastbelem @deeinstereo you may want to do some tests on this by setting your clock to multiple different dates/times and making sure it does what you guys want...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH thanks! @CarrissaReffell is doing some tests on this on Monday :)
