### ISSUE TITLE
Change Copy on "Contact the Pastor"

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#697]
Can we make it say "Contact Pastor" please? Just remove "the"

![Screen Shot 2021-03-16 at 2 32 09 PM](https://user-images.githubusercontent.com/47831068/111361795-7a33d180-8664-11eb-862f-28dee10aaff7.png)

**Comment by JonEsparaz** [comment]
This is hard-coded (can't be changed from the JSON files).
