### ISSUE TITLE
MAIN BUTTON MISSING ON HOME PAGE * URGENT*

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#730]
Hey, so the Why Jesus? CTA button just disappeared from our website. HELP?!?!? 
https://www.themeetinghouse.com/

@JonEsparaz @GeorgeBellTMH @lucastbelem

**Comment by JonEsparaz** [comment]
This was removed in https://github.com/themeetinghouse/web/pull/715:
```typescript
this.renderLinkButton(this.state.content.button1)
```

**Comment by lucastbelem** [comment]
@deeinstereo where was this before?

@itbel can you fix pls?

**Comment by deeinstereo** [comment]
You mean the button? https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=220%3A6248

**Comment by itbel** [comment]
I'm on it.
