### ISSUE TITLE
Wrong Font Weight + Box Styling

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#731]
I noticed on figma: https://www.figma.com/file/Ym6BNDP4qWHnwZ8Atfk0B06k/TMH-Website?node-id=220%3A6248
That the Locations box on mobile should have a lighter weight of font for the description, and that the locations drop down should line up on the left side with the title and the copy (see Figma for what it should look like vs attached of what it looks like now on the home page. 

![Screen Shot 2021-03-31 at 3 38 04 PM](https://user-images.githubusercontent.com/47831068/113202874-50200900-9239-11eb-9b78-a56300d8e7ae.png)

**Comment by deeinstereo** [comment]
@lucastbelem would love an update on this one

**Comment by lucastbelem** [comment]
@RAidanM the dropdown box is not aligned with the text on the left. Could you please revisit?
