### ISSUE TITLE
Apply "add to calendar" goes blank

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#734]
I've received reports from Apple users that click "apple" under add to calendar is giving them a blank screen rather than a calendar card.

@JonEsparaz tagging you cause you I think did a bunch of work on add to calendar. Please let @itbel if you don't have time to take care of it today.

Thanks :)

**Comment by JonEsparaz** [comment]
@lucastbelem fixed. 

Note: the Apple link will work in iOS Safari, but not necessarily other mobile browsers (this is how the previous Add To Calendar component behaved too).
