### ISSUE TITLE
Add to calendar is hidden on Easter page

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#737]
<img src=https://user-images.githubusercontent.com/48423418/113318716-bf036d80-92de-11eb-9fb4-52d4dd094319.png width=300>

Likely introduced in 9532ddb211b1f6a4c53766d77f3d30d6ced223aa.

**Comment by JonEsparaz** [comment]
I've confirmed that my fix for #725 does not cause this issue.

**Comment by lucastbelem** [comment]
This issue still occurs, although with Easter behind us, it's low priority.

**Comment by JonEsparaz** [comment]
@lucastbelem I believe the changes have been merged, but not deployed.

Please test on localhost, the issue is certainly resolved:

<img src=https://user-images.githubusercontent.com/48423418/114584400-a1c08e80-9c50-11eb-8e20-aea699c8d5ff.png width=300>

**Comment by lucastbelem** [comment]
Ah! Ok thank you!

**Comment by lucastbelem** [comment]
@CarrissaReffell
