### ISSUE TITLE
Download App Notes prompt new issue

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#739]
Jon told me to make it a new issue. 

You know what to do ;)

**Comment by JonEsparaz** [comment]
> ...here's some feedback from Jen. On my end, can we lose the little TMH logo, and try to fit "Notes are better on our app" into  one line?
> 
> Feedback:
> - I like that it sits on the bottom, unassuming but always present until action is taken (close or download)
> - It's a little clunky? Maybe it's the relationship between the logo and text? Especially when the line of text knocks to 2+ lines and grows taller than the logo. And I know that spacing probably can't be controlled. Maybe taking the text "Notes are better in the app" down one weight (to regular?) or decreasing the size overall of the text and "x" and "download" would help?  This I'm not 100% sure until I see it. I could be wrong.
> - You think the house logo is necessary? If the text contained more TMH wit (ex. "Pssst, notes look better in the app."), then maybe you can get rid of the logo to gain space but still have brand presence/personality in the text? Just asking the question. I have arguments for both.
> -Ultimately, if you ran with this I think it's totally acceptable and fulfills its purpose.

_Originally posted by @deeinstereo in https://github.com/themeetinghouse/web/issues/704#issuecomment-811474900_
