### ISSUE TITLE
Double live event creation

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#743]
Sometimes when we create a live event, 2 of the same event are created. I'm guessing it's not when we create it, but we edit. I'm thinking that if I edit a live event, rather than editing in Dynamo, it just creates a new one. 

This usually isn't a big deal, except today it was a little problem. We had a typo in the live event id. When we went to edit the id to remove the extra space, we couldn't do it because "live event overlapped with another live event of the same name". We did it by going to dynamo and editing the event there. 

Is there anything we can do to make sure the database doesn't get multiple events created for the same event to prevent issues like this? Not a high priority, but I wanted to post this one so we have that in mind for the future.

**Comment by lucastbelem** [comment]
closing for #744

**Comment by JonEsparaz** [comment]
> Sometimes when we create a live event, 2 of the same event are created. I'm guessing it's not when we create it, but we edit. I'm thinking that if I edit a live event, rather than editing in Dynamo, it just creates a new one.

This sounds like a separate problem than #744 (and seems like #679 persists). @lucastbelem am I misunderstanding something here?

I'll note that this problem never occurred before custom live events were implemented, so I suspect that's when the issue was introduced.

**Comment by lucastbelem** [comment]
@JonEsparaz you got it right. I only closed this because as custom events are now allowed to overlap and we never have more than 1 live event at the same time, this isn't usually an issue. Unless of course, we have typos, missed spaces etc, which is why I thought #744 would address most of the time this could be a problem. However, ideally, I'd love for the double event thing to disappear.

**Comment by JonEsparaz** [comment]
Do you have the database export from today's issue? 

Also, are you fairly certain this issue occurs during editing (rather than creation)?

**Comment by lucastbelem** [comment]
@JonEsparaz I can get the report...but I had to fix the problem right away so I don't know if it's helpful to you at all at this point?

I can't be certain the issue occurs at editing...that's my guess.

**Comment by JonEsparaz** [comment]
Just send it over - could be helpful.

To confirm exactly what happened because I'm a little unclear:
- You created an event (on the admin page)
- You edited that event (in the DynamoDB AWS console)
- Then duplicates appeared?

**Comment by GeorgeBellTMH** [comment]
Has this ever happened again, or can we close?

**Comment by GeorgeBellTMH** [comment]
Closing
