### ISSUE TITLE
🖥️  Add Facebook pixel to Website  🖥️

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#746]
This should be our top priority for the website right now. 

Here's what I need done:

<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '636068959887237');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=636068959887237&ev=PageView&noscript=1"
/></noscript>

Paste the pixel code into the bottom of the header section just above the </head> tag. Install the base code on every page of your website.

I was also hoping to track some custom events as we don't have the typical purchase type of events on the website: https://developers.facebook.com/docs/facebook-pixel/implementation/conversion-tracking/#custom-events

Custom events for things like going to the giving page (then later actually giving once we have that set up), spiritually curious, community curious, teaching, locations, connect, etc. << Connect is the most important custom one I am interested in.

ALSO>> There's a big iOS14 update coming that will supposedly ruin everything, so read this first to make sure we're all covered: https://www.facebook.com/business/help/126789292407737?id=1205376682832142

**Comment by GeorgeBellTMH** [comment]
Pixel code is on the site now.
