### ISSUE TITLE
Notes admin performance optimization

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#750]
@vanderwalrus reported that clicking the Bible passages button for today's notes (4/25/2021) caused Chrome to crashed. There were >70 Bible passages in total.

I tested on my machine and the process took ~10 minutes and used ~6 GB of memory. There weren't any crashes on my machine, but for an average machine with 8 GB RAM, Chrome would likely crash because of the memory usage.

To-do (in order of priority):

* [ ] reduce memory usage so the browser does not crash
* [ ] speed improvement

**Comment by lucastbelem** [comment]
@itbel please investigate?
