### ISSUE TITLE
😧 New Baby Hero Image for Curated Teaching 😧

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#757]
I was playing around on /teaching-curated and decided to replace BBQ's from the featured baby hero with other content to see if it gets more interaction. 

It's now pulling said video's thumbnail, but that doesn't look very good as a baby hero. 

How can i upload a customized baby hero image for this video/playlist in this format on this page?

https://www.themeetinghouse.com/teaching-curated

**Comment by lucastbelem** [comment]
@itbel is this a bug in how the website processes the image? Or do we need to upload a new thumbnail? Or @GeorgeBellTMH should we just add those videos to a series within that category and create a baby hero image for that series (which will result in the website pulling the image as it does for teaching series)?
