### ISSUE TITLE
🔎 Search on the teaching page? 🔎

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#758]
I know @GeorgeBellTMH has been working on the main search function, but I was just combing  our CrazyEgg data and a lot of users are accessing the search function on our teaching page and getting frustrated with the results (lots of rage clicks and dead clicks). 
![Screen Shot 2021-05-17 at 4 35 17 PM](https://user-images.githubusercontent.com/47831068/118555471-bea91f80-b730-11eb-99d3-1bd65debfce8.png)

I just tried it now and the search results aren't very good... type in the word Jesus and you wouldn't think we just did a 5 week series called Jesus 101.

@GeorgeBellTMH can you:

1. Remember this search section as you work on the new search function.
2. Maybe turn this off or pause it until we're ready for better results?

**Comment by GeorgeBellTMH** [comment]
I'm closing and adding this to the main search ticket
