### ISSUE TITLE
Jesus Collective Logo not showing up on Locations page

### ISSUE THREAD

**Issue by RAidanM** [themeetinghouse/web#767]
/static/images/about-us-5.png
This is the logo that should be appearing.
Other images do work in place of it as long as they are .jpg. My assumption on why it doesn't work is because it is .png unlike every other image inside of /static/images/ which are .jpg

Is the image's file type wrong or has .png functionality broken?

**Comment by JonEsparaz** [comment]
This is a known issue: #673

**Comment by GeorgeBellTMH** [comment]
Let's convert it to a JPG for now....the png stuff is complicated by a bunch of stuff that I don't have time to fix right now...basically there is an issue with our forwarding code on (somewhere in the code on cloud front, s3, api gateway or lambda...)
