### ISSUE TITLE
Teaching Series Experience Highlights Overload

### ISSUE THREAD

**Issue by deeinstereo** [themeetinghouse/web#776]
Click on any series and a new window opens with the 1st video, scroll down you get highlights, scroll lower and you get episodes. 

For series like Faithful One where there are 20+ highlights, it gets really messy when you have to scroll through rows and rows before you can see the teaching videos. 

We should fix this so that you never have to scroll through more than one row, and then you can always click on see more or scrub through the carousel, or something. 

Video was too big to attach so watch here: https://youtu.be/kUmNMQoJ-kc

**Comment by lucastbelem** [comment]
Closing for now as without content this becomes irrelevant...temporarily.
