### ISSUE TITLE
UI for new giving experience

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#786]
Design Stuff - Desktop/Mobile (@itbel)

* [ ] Giving Page
* [ ] Login page design
* [ ] Create user design
* [x] Customizable Menu for Account Portal Landing Page
* [ ] Page components for Account Portal Landing Page (My Total Giving, Recent Transactions, Profile, Payment Methods, Tax Receipts)

Design found here: https://www.figma.com/file/pm8jTuHb1eshVL2HkwRQS9/TMH-UI-Jen?node-id=1669%3A15384

**Comment by GeorgeBellTMH** [comment]
I've repointed the features/payments branch to a new test environment....https://d1bp8606u0j0nh.cloudfront.net

Just note that the db is essentially empty, so no videos etc...

cc @lucastbelem

**Comment by GeorgeBellTMH** [comment]
@itbel  -I added the stripe components for credit card/cvc and expiry, can you go in and restyle them...
 
- [ ] Style the creditcard/cvc/expiry using the stripe objects
- [ ] Make the disabled style of the add card button look disabled...

**Comment by itbel** [comment]
> @itbel  -I added the stripe components for credit card/cvc and expiry, can you go in and restyle them...
> 
>  
> 
> - [ ] Style the creditcard/cvc/expiry using the stripe objects
> 
> - [ ] Make the disabled style of the add card button look disabled... 

Ok. Will do!

**Comment by GeorgeBellTMH** [comment]
Closing this ticket and starting to create separate tickets for improvements/fixes.
