### ISSUE TITLE
Events module is gone

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#794]
After merging of the events module, no events appear for any location on the website. @RAidanM could you pls take a look?

**Comment by GeorgeBellTMH** [comment]
<img width="1041" alt="Screen Shot 2021-07-16 at 12 11 40 PM" src="https://user-images.githubusercontent.com/47749730/125997425-c1f289b1-13b2-4dfe-a9bd-79cbc1986109.png">

@RAidanM can you hide the header if there are no events....

**Comment by GeorgeBellTMH** [comment]
(that's toronto-downtown)
