### ISSUE TITLE
Pull leaders from F1

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#801]
In preparation for the home church leader experience, pull the leaders from F1 and put users in the correct group.

[ ] - On login get the householdId and personId from F1 based on the verified email address
[ ] - Get list of groups in F1 that the user is associated with, and the membership type (leader or member)
[ ] - Setup groups as appropriate in cognito....

Static Groups:
 - leader
 - leader-manual

Generated Groups:
 - homechurch-[id]
 - homechurch-[id]-manual

Others that would be nice to be able to figure out:
 - site-[id]
 - site-[id]-manual
 - staff
 - youthleader
 - kidleader
 - youth-[id]

**Comment by lucastbelem** [comment]
Others worth considering - welcome/connect, tech, setup, music coordinators, lead pastors...there may use for having all of them there...but the priority is Home church leaders.

**Comment by GeorgeBellTMH** [comment]
This is done. Group names match what is in F1
