### ISSUE TITLE
Livestream setting issue

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#803]
This morning, the livestream didn't appear on the website. I checked admin and sure enough it was NOT there. I checked with Carrissa and she did set it up. Somehow, between Wednesday and today, it disappeared.

I was able to set it up this morning. My guess is that it's that logout/log in issue. However, with that issue, the livestream doesn't save at all. In @CarrissaReffell's case, it looks like it saved and then disappeared.

@GeorgeBellTMH Carrissa will set it up again this week, but it'd be great if you could be on standby in case there are problems next Sunday. If there are problems, you'd like hear either from Natalie Burtch or Carrissa. 

@CarrissaReffell, before you set it up this week, try logging out and logging back in.

Thanks team!

**Comment by JonEsparaz** [comment]
I was working on other stuff and saw this issue.

If I can provide two recommendations:
1. Create a cron Lambda, that on Friday morning, checks that the livestream is found in the database and email people with the result: all good ✅ or whoop whoop it's not there ⚠️.
2. Create a testing page `/livestream-test` that uses the _exact same_ GraphQL queries (move them to a shared file) as the actual livestream components (only difference being the date can be forced to a particular Sunday). Then the admins can go to this page, set the date to next Sunday, and be absolutely sure that the livestream is showing up in the frontend.

Implementing one or both of the above is probably a good idea as the livestream is more or less mission critical.

**Comment by lucastbelem** [comment]
Turns out, users are overwriting old livestreams rather than creating new ones. That's why it appears that we don't have any older ones.
