### ISSUE TITLE
Secondary action link on hero box

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#815]
@JonEsparaz Do you know if we ever developed the secondary action in the attached image?
![Content Modules](https://user-images.githubusercontent.com/48295718/129117899-0fdee599-6382-4081-8dc2-99e3df9d241d.png)

**Comment by lucastbelem** [comment]
I'm referring to the action in the black box right at the top, in the first hero.

**Comment by JonEsparaz** [comment]
This hasn't been implemented in the React code.

**Comment by lucastbelem** [comment]
Dang! Ok. I'll line it up for implementation.

**Comment by lucastbelem** [comment]
@itbel please develop a way for us to be able to have a secondary link/button in a hero black box as per the Figma file attache.
