### ISSUE TITLE
Blog banner not appearing

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#835]
I uploaded a blog banner as required (correct spec and format) but it's not appearing in the blog. Any ideas why?

Here is an example: https://www.themeetinghouse.com/posts/oakville-in-person-gatherings

**Comment by GeorgeBellTMH** [comment]
I don't see it in the static/photos/blogs folder...

**Comment by GeorgeBellTMH** [comment]
I think we may have upload functionality, but not sure if it's been tested or validated to work...

**Comment by lucastbelem** [comment]
@itbel can you take a look pls?

**Comment by JonEsparaz** [comment]
A few notes as there seems to be some confusion.

> I think we may have upload functionality, but not sure if it's been tested or validated to work...

This was implemented (and tested) in https://github.com/themeetinghouse/web/pull/804. The post "Oakville in-person gatherings", found here: https://www.themeetinghouse.com/oakville, uses an image uploaded via the admin page.

> I uploaded a blog banner as required (correct spec and format) but it's not appearing in the blog. Any ideas why?

@lucastbelem the blog banner image does not get magically injected into the blog post body. You need to upload the image separately via the text editor. 

You need to upload: the banner image, the square image, the baby hero image AND any images you want to appear in the body of the blog post.

Hope this helps.

**Comment by GeorgeBellTMH** [comment]
Thanks @JonEsparaz, I didn't realize it was done...cool!

@lucastbelem I am closing unless you have further problems...
