### ISSUE TITLE
Popular teaching and highlights broken?

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#836]
If you go themeetinghouse.com/teaching you'll see that these 2 playlists seem off. There are only 3 videos in popular teaching and none in highlights. @GeorgeBellTMH could this be related to the maintenance you did this weekend?

**Comment by GeorgeBellTMH** [comment]
This is due to the code not pulling the number of views from YouTube...currently this happens when you import the video (and the number of views is going to be below the threshold)...we need to move the logic into a scheduled lambda and run it a few times a week.

**Comment by GeorgeBellTMH** [comment]
For now you can just change the duration and views so that something is visible...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH sorry dude...I didn't follow what you said. 

This is the first time we've had this issue. Did something change?

**Comment by GeorgeBellTMH** [comment]
Basically when you import the view information the number is gonna be pretty close to zero…I think we need to make a lambda that runs each night and gets updated numbers.

**Comment by lucastbelem** [comment]
Irrelevant now.
