### ISSUE TITLE
Videos from youtube outside of a playlist

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#840]
Can we make it possible to pull videos from youtube into our website without them having to be in a playlist? Not every video belongs with a playlist, so in order to bring some videos in, sometimes I have to add them to a playlist that has nothing to do with the video to get the video imported. For a few moments, the video appears in an unrelated playlist. This is also a problem because some videos should actually remain invisible on youtube.

**Comment by GeorgeBellTMH** [comment]
something like an inline video? or the ability to make the left/right white/black box images videos?

**Comment by lucastbelem** [comment]
Sorry, I wasn't clear. No difference to the end user...just the way videos are pulled from youtube.
