### ISSUE TITLE
Graphic won't upload to visual code

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#842]
Any ideas why? When I drop it in the correct folder, it tells me it'll replace the old graphic with the same (which is exactly what I want to do). But then it creates 2 changes instead of 1. And one of the changes I cannot stage, but it doesn't tell me why. The file name is the exact same.

**Comment by GeorgeBellTMH** [comment]
maybe it is capitals or something messing it up?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH the file I'm using has the exact same name...it replaces when I drop it but then when I go to commit the change in source control, it creates 2 changes...one that I can't click on or stage.

Help?
![Screen Shot 2021-09-10 at 6 21 09 PM](https://user-images.githubusercontent.com/48295718/132923725-054246d3-fa5c-4666-879e-e2ae1dd29c2c.png)

**Comment by GeorgeBellTMH** [comment]
You should still be able to click +…

**Comment by lucastbelem** [comment]
I know, but I can't. Can I send you the file to try and upload on your end?

**Comment by GeorgeBellTMH** [comment]
Sure

**Comment by lucastbelem** [comment]
@GeorgeBellTMH 
![adult-sunday-Jesus People](https://user-images.githubusercontent.com/48295718/132985780-78d486ac-c420-479b-aca1-2d49b6dd77c6.jpg)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this is the issue I was talking about. This Jesus People graphic won't upload. Also, the new Welcome Home series should have the new graphic, but it displays the old graphic in the carousel...once I click to see the entire series archive, it display the correct series with the correct graphic.

**Comment by GeorgeBellTMH** [comment]
Should be working now...
