### ISSUE TITLE
X is out of place on mobile (iPhone X)

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#845]
![IMG_007F8D329D1E-1](https://user-images.githubusercontent.com/47749730/132156282-845117a2-1894-4660-91e1-95628d056663.jpeg)

**Comment by lucastbelem** [comment]
@itbel

**Comment by lucastbelem** [comment]
@itbel can you see if this got fixed?

**Comment by itbel** [comment]
This should be fixed in #941 
Appears to be working correctly now.
