### ISSUE TITLE
Leaders day webpage

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#859]
**Creating spaces that work for the whole family**
**Creating Community In An Online World**
**Caring for others while caring for yourself**
**What are Fresh Expressions of Church?**
**Idea sharing lobby: Coordinators connect**
**Walking Through Divisive Days As a Leader**
**Simple Ways To Become More Invested In Your Neighbourhood**

**Comment by GeorgeBellTMH** [comment]
Huh? How did I create this?

**Comment by lucastbelem** [comment]
It was me...whenever I create something through wrike it says you created
it haha

**Comment by GeorgeBellTMH** [comment]
Closing
