### ISSUE TITLE
UI bug in "Notes are better in the app" component

### ISSUE THREAD

**Issue by JonEsparaz** [themeetinghouse/web#861]
I noted this in the breaking commit a couple months ago: https://github.com/themeetinghouse/web/commit/8874f74b371e53797b909215bdee5cc07e8d2c63#r53662073

See screenshot:
<img src=https://user-images.githubusercontent.com/48423418/134816774-e4fc074a-a01f-451a-9670-e7c406b17e1c.png width=300>

The close button's styles are broken.

**Comment by GeorgeBellTMH** [comment]
Fixed
