### ISSUE TITLE
Giving improvements

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#863]
George

* [x] My Total Giving not calculated (temporarily hidden)
* [x] Profile image not working (temporarily hidden)
* [ ] Home->Payment Methods - default payment method needs to be loaded from customer info....
* [x] Home->Recent Transactions needs to be sorted by date
* [ ] Give->Recurring->1/15 doesn't work yet, requires some extra code for subscriptions
* [x] Ability to see all subscriptions
* [x] Ability to delete subscriptions
* [ ] Ability to update payment method?
* [x] Ability to delete payment method?

Igor

* [ ] Add CAD$ to amount - or Canadian flag icon
* [x] Recurring->Starting date should only be able to be set to future dates
* [ ] Recurring->Starting date should only be able to be set to 1/15 on 1/15 monthly freq option
* [ ] Transactions->Need a UI if there is no connection to F1
* [x] Transactions->Amount needs to be trimmed to two decimal places
* [ ] Home->Recent Transactions likely needs less info on smaller screens (or smaller font)
* [x] Long emails overflow the right profile box in some situations/screen sizes
* [x] Secure payment should be below New Credit Card Information in some smaller screen-sizes
* [ ] Add recurring gift button doesn't underline on mouseover

Lucas

* [ ] Transactions->Need to understand Payment Method field
* [ ] Transactions->Need to understand Fund field
* [ ] Stripe->Setup email and receipts in Stripe
* [ ] Not sure I like defaulting frequency to every week...likely should require a choice, or be set to monthly by default?
* [ ] We need some copy on the transactions page regarding how long it takes for transactions to show up...
* [ ] Is there a reason we have: This is a secure 128-bit SSL encrypted payment. Not sure this is correct anymore...
* [ ] Terms and conditions, privacy policy go nowhere...should these be in the credit card section or in the footer?

**Comment by lucastbelem** [comment]
- [ ] Recurring button doesn't do anything.

**Comment by lucastbelem** [comment]
@itbel when you publish, can you check this issue and close it?
