### ISSUE TITLE
Cannot create livestream event

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#866]
Lauren tried to create the livestreams for this weekend and was unable to. It won't save. It won't appear. She tried logging out and back in and no luck.

Could somebody pls take a look before Sunday?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH whatever you did, fixed the church link, but didn't make the After Party appear. Here is the id: Live-65a55e39-bb75-4fb9-8f5c-5c3b7388638a. It's in Dynamo, but isn't appearing on the website. I changed my clock to test and no luck.

**Comment by GeorgeBellTMH** [comment]
Basically it looks like an issue with too many items in the DB...I just deleted the old items...should be good for another 2 years...
