### ISSUE TITLE
Typo on COVID Registration page

### ISSUE THREAD

**Issue by nadamico** [themeetinghouse/web#882]
The fourth bullet point should be split in two so it should read:

- You (or anyone you live with) have not received a COVID alert exposure notification on your mobile in the last 14 days. 
- You have no been out of Canada in the last 14 days.
![Screenshot](https://user-images.githubusercontent.com/58789466/138730063-7d69f0da-c9e7-45b1-98dd-889d4a421dc9.jpg)

**Comment by GeorgeBellTMH** [comment]
Copy is different now...
