### ISSUE TITLE
Staff photo looking squished

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#885]
Christian Nikodemus's photo is squished on the staff page. I've replaced it with a new photo but it's not appearing.

![Screen Shot 2021-10-27 at 11 54 30 AM](https://user-images.githubusercontent.com/89869101/139102199-38dbceac-c27e-4210-b3ac-d7abf4e46f7a.png)
![Screen Shot 2021-10-27 at 11 55 00 AM](https://user-images.githubusercontent.com/89869101/139102221-a321e01a-9f55-4f5f-a712-4ef1ed54b78c.png)
.

**Comment by GeorgeBellTMH** [comment]
I've reset the photos, please take a look...
