### ISSUE TITLE
App sending reminders at wrong time

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#896]
The TMH app has been sending reminders at 8:55am to say that church starts in 5 min. I assume it has something to do with the time change.

**Comment by lucastbelem** [comment]
@laurengermain this should be fixed. Could you pls report next week?

**Comment by laurengermain** [comment]
I actually don't receive any reminders from tmh app -- how can I test this? 
This issue was flagged by someone that attends tmh.

**Comment by lucastbelem** [comment]
@laurengermain you would need to turn on push notifications in your phone settings for the tmh app.

**Comment by laurengermain** [comment]
@lucastbelem mmmh, I do have notifications for the app turned on.

**Comment by GeorgeBellTMH** [comment]
I think the notification only works for iPhone...

**Comment by GeorgeBellTMH** [comment]
Closing...
