### ISSUE TITLE
Screenshot (Dec. 8, 2021 5:30:13 p.m.)

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#899]
Weird crop on homepage on mobile.

**Comment by GeorgeBellTMH** [comment]
screen shot?

**Comment by lucastbelem** [comment]
![Screenshot_20211208-173013.png](https://user-images.githubusercontent.com/48295718/145629611-e808f6df-3418-4d73-aed6-f4d93b3aa353.png)

**Comment by GeorgeBellTMH** [comment]
Closing
