### ISSUE TITLE
Ottawa service time needs to be pm, not am

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#900]
On the locations page, all the service times default to 'am' but the Ottawa service time is at 3:00pm. The page previously said "15:00am" so I tried changing it by putting in "3:00pm" but obviously that didn't work!
![Screen Shot 2021-12-16 at 10 54 33 AM](https://user-images.githubusercontent.com/89869101/146405029-e13d01d3-dc96-4a8f-8cee-b9b98f884fce.png)

**Comment by lucastbelem** [comment]
@itbel can you see what's going and fix it? But also pls let me know so we can do it ourselves?

**Comment by lucastbelem** [comment]
@itbel this is done right?
