### ISSUE TITLE
Change "add to calendar" to "register"

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#902]
In every parish page, in the hero image, there is a black box with basic location and time info for that parish. There are also 2 actions/buttons please can engage with: "Add to Calendar" and "Contact the Pastor". 

Could you please replace the "Add to Calendar" with "Early Registration" or if that's too long, just "Register"? And point that button to "themeetinghouse.com/registration"? 

Lastly, the logic that is currently in place that changes the "add to calendar" to "Watch Live" and points people to "themeetinghouse.com/live" should remain in place (but obviously going from "Early Registration" instead.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH could we pls have this done by Jan 9?

**Comment by GeorgeBellTMH** [comment]
Do we still need this?

**Comment by lucastbelem** [comment]
Yes pls.

"Add to Calendar" on parishes pages should change to "register" and go to /registration".

**Comment by GeorgeBellTMH** [comment]
Done
