### ISSUE TITLE
Contact leader email subject

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#904]
When someone clicks "contact leader" in a home church in the HC finder, the email subject displays "homechurch". Can we please change this to "Home Church"?

**Comment by GeorgeBellTMH** [comment]
This should be fixed.

**Comment by lucastbelem** [comment]
@laurengermain could you pls test and let Jordan know?

**Comment by laurengermain** [comment]
@lucastbelem there's no email subject that I can see after clicking "contact leaders"...

![Screen Shot 2022-02-02 at 2 45 11 PM](https://user-images.githubusercontent.com/89869101/152225996-f29bb4a6-ca73-4d30-ac60-254bc8af7f2b.png)
