### ISSUE TITLE
Home Church finder displaying incorrect data

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#906]
The image below shows a Home Church that meets on Tuesday (as per the description) but the pill appears as Wednesday.

![image](https://user-images.githubusercontent.com/48295718/150023990-265000ad-dd82-4bee-a0f9-999934307615.png)

**Comment by lucastbelem** [comment]
@itbel could you pls see if this is an easy fix today?

**Comment by itbel** [comment]
Recurrence data appears to be missing for the following home churches:
1. Taylor Home Church
2. Sapling Family Friendly Home Church
3. Downtown Hamilton Online Home Church
4. Grimsby Home Church
5. After Church Home Church -- launching Feb 6
6. Nightstar Home Church
7. Parent Connect Online Home Church

![image](https://user-images.githubusercontent.com/42515854/150386561-8dad4fb3-dd6b-4922-bba8-14707252eef8.png)

**Comment by lucastbelem** [comment]
@itbel so what you're saying is that our data team needs to enter that data so the system populates the correct date?

**Comment by itbel** [comment]
I believe so.

**Comment by GeorgeBellTMH** [comment]
Is this ok?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @itbel this seems fixed now.
