### ISSUE TITLE
Testing upgrades

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#910]
@lucastbelem I did a bunch of version updates and did a fast scan to check if any problems...let me know if anything else comes up this week...

**Comment by lucastbelem** [comment]
@laurengermain could you pls go through the TMH website on mobile and web and see if you can find any problems? Buttons that don't click, images that cut off strangely, anything that doesn't load or takes too long, etc?

**Comment by GeorgeBellTMH** [comment]
I am doing another round of this today...on Monday/Tuesday we will need to test...

**Comment by GeorgeBellTMH** [comment]
Running list of things to test:
- [ ] Admin Functionality (specifically user related)
- [ ] Image generation is working
- [ ] Playlists, Blogs, Video Import, Moving a Video to playlist
- [ ] Mobile app, playlists, videos playing, blogs, notes
- [ ] Notes
- [ ] Sunday morning experience (set clock to Sunday and test)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH something is seriously broken...most of the images on the website became the "angels and demons" playlist image. Can you pls revert this asap?

**Comment by lucastbelem** [comment]
<img width="1424" alt="Screen Shot 2022-02-07 at 8 47 10 AM" src="https://user-images.githubusercontent.com/48295718/152800126-f7d8ea0d-ef19-48c4-9888-ef5f779e57bd.png">
<img width="1436" alt="Screen Shot 2022-02-07 at 8 46 43 AM" src="https://user-images.githubusercontent.com/48295718/152800130-c1ff6807-0228-4fd9-82d0-7522ee2115e9.png">
<img width="1436" alt="Screen Shot 2022-02-07 at 8 46 49 AM" src="https://user-images.githubusercontent.com/48295718/152800135-74aa20c3-d17a-4e4a-9137-9de2b5444aa7.png">
<img width="1430" alt="Screen Shot 2022-02-07 at 8 46 57 AM" src="https://user-images.githubusercontent.com/48295718/152800138-39ba0bdd-c532-4d82-b242-7549f27d786f.png">

**Comment by georgevicbell** [comment]
Taking a look at this now…looks like something wrong with the image caching…was working after the upgrade but seems to not be now…

**Comment by lucastbelem** [comment]
@GeorgeBellTMH thanks man. Let me know when you've got something. I got a couple people asking.

**Comment by georgevicbell** [comment]
Ok…it’s fixed…temporarily….

So I think what happened is that they changed the caching for our image system…before it was caching based on the parameters, now it is not…I have turned off the cache…and will play around with it tonite to try to get it back on…

I don’t think this had anything to do with the amplify updates…

G



On Feb 7, 2022, at 11:40 AM, Lucas Belem ***@***.******@***.***>> wrote:



@GeorgeBellTMH<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGeorgeBellTMH&data=04%7C01%7C%7C52ba7e94367c4524d16b08d9ea71a21c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798596040211043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b52v05sa%2FMztoOlIrv1Dm8DLjW21CpeUR6D3zkShXIY%3D&reserved=0> thanks man. Let me know when you've got something. I got a couple people asking.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fissues%2F910%23issuecomment-1031846695&data=04%7C01%7C%7C52ba7e94367c4524d16b08d9ea71a21c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798596040211043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9IQXQRMZLxZatkU04DsLSTBzsP%2B0ib1VKytPvpNOtw0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABBNL7ZP3GZJZ3JNLSMB26TU2ANZDANCNFSM5NE7IJPQ&data=04%7C01%7C%7C52ba7e94367c4524d16b08d9ea71a21c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798596040211043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MCXgfslqaACq%2FIAnuwYWYM1Ser5kW9VV0K8Ip9gY4bk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C52ba7e94367c4524d16b08d9ea71a21c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798596040211043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EDSU%2F066RtbEGVDCgu99fSzeK4eeAcqSNXSMOtsNH1k%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C52ba7e94367c4524d16b08d9ea71a21c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637798596040211043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zCsRFx8cn5iNOoWb1RfzvEkZj5NREx5UJ96FKRomiBc%3D&reserved=0>.
