### ISSUE TITLE
Blog photos not appearing for social posts

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#925]
The website isn't pulling images from blogs when we try to post them on socials.

Example from blog post: https://www.themeetinghouse.com/posts/god-loves-culture
This image is missing in the Facebook preview.
![Facebook Preview](https://user-images.githubusercontent.com/89869101/154339636-05b74ebe-96b2-498f-953f-63242f46a68d.png)

**Comment by laurengermain** [comment]
@nadamico tagging you in this one to follow:)

**Comment by itbel** [comment]
This is working again.
