### ISSUE TITLE
After Party carousel missing thumbnails

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#927]
I re-added the After Party carousel to the teaching-curated page last week and the youtube thumbnails are not appearing from previous weeks.
https://www.themeetinghouse.com/teaching-curated
![After Party](https://user-images.githubusercontent.com/89869101/154533310-11268715-a2ff-42a8-9fc4-24cdcd0a6452.png)

**Comment by georgevicbell** [comment]
Are those videos private on YouTube? Or have they been deleted and re-added?

G

On Feb 17, 2022, at 9:07 AM, laurengermain ***@***.******@***.***>> wrote:



I re-added the After Party carousel to the teaching-curated page last week and the youtube thumbnails are not appearing from previous weeks.
https://www.themeetinghouse.com/teaching-curated<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.themeetinghouse.com%2Fteaching-curated&data=04%7C01%7C%7C68a92fee56d74abe483c08d9f237fd36%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807144542781218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XYMLD6Vgtq4SDrnbe4SyJ5dWIjYIZwJAnmAJwS4p1Sg%3D&reserved=0>
[After Party]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F89869101%2F154533310-11268715-a2ff-42a8-9fc4-24cdcd0a6452.png&data=04%7C01%7C%7C68a92fee56d74abe483c08d9f237fd36%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807144542781218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BY0J6XnJ5HanSSPa1eNJueBN0x92RkWKnZW1ihZK97o%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthemeetinghouse%2Fweb%2Fissues%2F927&data=04%7C01%7C%7C68a92fee56d74abe483c08d9f237fd36%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807144542781218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uAgSOCU6121u9tzIyGVEAXzyV1lMXMzNoj2JUBgv5PQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABBNL7YBQW2INVZRA6MYKYLU3UTNLANCNFSM5OVJLURQ&data=04%7C01%7C%7C68a92fee56d74abe483c08d9f237fd36%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807144542781218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZjRqHeYTAaSlX7bts1vhFI9jSQOtyPa9hmtbpv7ImVI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C68a92fee56d74abe483c08d9f237fd36%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807144542781218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FjQ1qdfv20D4owfj9triVc9li3oALNPJnLV91StQEBQ%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C68a92fee56d74abe483c08d9f237fd36%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637807144542781218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9HZ0JCxd26j719aVTBaSWkUZowRnjEqyG%2Byp8WWCIfU%3D&reserved=0>.

**Comment by lucastbelem** [comment]
@laurengermain could you pls check if the after party is private? I think we did move it to private...I don't think we want it public, so maybe you can just make it public, pull the videos in, then unlist it again.

**Comment by GeorgeBellTMH** [comment]
This is fixed...other problems, but this is fixed.
