### ISSUE TITLE
Kids videos aren't importing for this Sunday

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#929]
The kids videos for this Sunday aren't importing into admin. Neither is the livestream video from March 6. Links below.

Early Years Pray: https://www.youtube.com/watch?v=_JN1keVQb5Q&list=PLB5r2P47beqKcw--wi3iCdP-i_Ksnx_9-&index=5
Kids Mark Because Jesus: https://www.youtube.com/watch?v=jUu-w3QVo2g&list=PLB5r2P47beqKcw--wi3iCdP-i_Ksnx_9-&index=6
Church livestream: https://www.youtube.com/watch?v=_Q4kLI_x0N4&list=PLB5r2P47beqKcw--wi3iCdP-i_Ksnx_9-&index=9

**Comment by GeorgeBellTMH** [comment]
The church livestream video needs to be a part of a playlist before it will import...

**Comment by GeorgeBellTMH** [comment]
They are all there now...I just ran it and it worked...
