### ISSUE TITLE
Find a home church info

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#947]
It seems like any recent updates to Home Church information is not displaying on the website.

**Comment by itbel** [comment]
This appears to be working.

**Comment by itbel** [comment]
I think something is wrong with `tmhF1HomeChurch` lambda.

**Comment by GeorgeBellTMH** [comment]
This should be resolved...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH is the fix published for testing?

**Comment by GeorgeBellTMH** [comment]
yup
