### ISSUE TITLE
Cannot update staff photo with newer version

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#964]
@GeorgeBellTMH can you clear the cache so this photo will appear? I am trying to update Chris Murphy's staff photo with a newer version today.

I tried using "2" at the end of one photo's file name, but that doesn't seem to be working (i.e., Jamie van Manen's photo is named, "Jamie_van Manen_app_2" but his photo is not appearing in the overseers section. I know you said this might fix the cache issue?

**Comment by laurengermain** [comment]
@GeorgeBellTMH @lucastbelem

**Comment by GeorgeBellTMH** [comment]
I have some stuff I will publish tonite, will get this done then.
