### ISSUE TITLE
Find and bring back code for live unite page from May 2020

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#967]
We made a live page in May 2020 for the live unite event. Can you look for it in the code and bring it back? We need to do it again? Maybe we can just re-create it via a new livestream event. The problem is that we don't want it to show as a live event in the TMH website and they are under the impression that we branded it as JC last time. Can you pls find this?

**Comment by GeorgeBellTMH** [comment]
Please send me the content for this.
