### ISSUE TITLE
Admin not loading

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#978]
Some issues have been found:

* [x] Cannot log in to admin side of tmh website
![](https://user-images.githubusercontent.com/48295718/165329821-c6fad152-8593-4d5b-b221-37a9bf17c2f4.png)
* [ ] Could not generate pdf from teaching notes
* [ ] Livestream bar did not appear on the website

**Comment by GeorgeBellTMH** [comment]
Can you verify this is still happening? I can't replicate...

**Comment by laurengermain** [comment]
@lucastbelem I've been able to sign in without issue today, so might be on your end?

**Comment by lucastbelem** [comment]
@laurengermain thanks! I did a password reset and things seem ok now.
