### ISSUE TITLE
Home church times in finder are showing time zone oddly

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#989]
See the screenshot below. Instead of "EDT" or "EST" or "ET", the time zone location appears (i.e. -03). 
<img width="1440" alt="Screen Shot 2022-05-05 at 3 35 16 PM" src="https://user-images.githubusercontent.com/48295718/166997844-5de79259-99e7-4b7e-9fcf-8f96e4fe475e.png">

**Comment by itbel** [comment]
Is this issue still occurring? @lucastbelem

**Comment by itbel** [comment]
Can this be closed? @lucastbelem

**Comment by lucastbelem** [comment]
@itbel still occuring. Also appears to be occurring in the live banner dropdown.
<img width="1418" alt="Screen Shot 2022-05-15 at 9 50 56 AM" src="https://user-images.githubusercontent.com/48295718/168139686-791387e3-b650-4db5-9ca3-ef9e3d42df5e.png">

**Comment by itbel** [comment]
Appears to be an issue with moment timezone package, and only affects specific time zones.

https://github.com/moment/moment-timezone/issues/780#issuecomment-550491645

**Comment by itbel** [comment]
as discussed with @lucastbelem this issue is no longer a priority.
