### ISSUE TITLE
New admin

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#990]
Guys, I'd love us to talk through what we can do to improve admin data management. 

I'd like to include:

* [ ] Series descriptions
* [ ] Graphic/image uploads
* [ ] A new infrastructure for playlists and series that allows any video to be a part of any number of playlists/categories
* [ ] Allow staff add/edit/delete from admin
* [ ] Video importing regardless of playlists

**Comment by GeorgeBellTMH** [comment]
Yes...all this is good ideas...

1,4 are easy...2 is doable but will mean things won't work locally very well...3/5 are doable...

**Comment by lucastbelem** [comment]
Closing this. Will reopen when we have a clearer sense of what scope for this.
