### ISSUE TITLE
External urls using FadeScaledImage do not load

### ISSUE THREAD

**Issue by itbel** [themeetinghouse/web#999]
![image](https://user-images.githubusercontent.com/42515854/167958596-6e4d9f12-c7e1-40c4-b32c-9d5238c60bde.png)

**Comment by georgevicbell** [comment]
Is this on local host or on the site itself?

Sent from my iPhone

On May 11, 2022, at 6:36 PM, Igor Belem ***@***.***> wrote:

﻿

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42515854%2F167958596-6e4d9f12-c7e1-40c4-b32c-9d5238c60bde.png&data=05%7C01%7C%7C4cb0114dbdd84a5c861508da339ea189%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637879053663819104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZzXa%2FOXig32Oo1criJXkz0kXM5OoUKZMbQbux9Ypxfk%3D&reserved=0>

**Comment by itbel** [comment]
occuring in prod
